#!/usr/bin/env node
/**
 * Writer's Studio — developmental edit runner.
 *
 * Reads a candidate manifest, ranks the candidates against the doctrine, emits
 * a Jarvis governance gate when the referent is undecided, and writes one
 * editorial letter per candidate.
 *
 *   node scripts/writers-studio/develop-chapter.mjs \
 *     --manifest scripts/writers-studio/works/elemental-alchemy-ch10.json \
 *     [--out docs/book-studio/CHAPTER_10_DEVELOPMENTAL_EDIT_v1.md]
 *
 * Writes ONLY to --out. It never touches the manuscript.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  loadDoctrine, readWorkReferent, analyze, compareCandidates, workBindingGate, editorialLetter,
  REFERENT_MODE, requireWorkBinding,
} from './developmental-editor.mjs';
import { validateWorkerGate } from '../builder/jarvis-governance-gate.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const arg = (n, d = null) => {
  const i = process.argv.indexOf(`--${n}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : d;
};

const manifestPath = arg('manifest');
if (!manifestPath) { console.error('--manifest is required'); process.exit(2); }
const manifest = JSON.parse(readFileSync(path.resolve(repoRoot, manifestPath), 'utf8'));
const doctrine = loadDoctrine(path.resolve(repoRoot, 'scripts/writers-studio/doctrine', `${manifest.doctrine}.json`));

const mode = manifest.mode ?? REFERENT_MODE.FIXTURE_ANALYSIS;
const fx = manifest.fixture_referent;
const fixture = readWorkReferent({
  artifact: path.resolve(repoRoot, fx.artifact), fromLine: fx.fromLine, toLine: fx.toLine, label: fx.label,
});

// Archaeology only. These are NOT candidates for the Work.
const corpus = (manifest.comparison_corpus ?? []).map((c) => readWorkReferent({
  artifact: path.resolve(repoRoot, c.artifact), fromLine: c.fromLine, toLine: c.toLine, label: c.label,
}));
const ranked = compareCandidates(corpus.length ? corpus : [fixture], doctrine);

// A gate is owed only to CHANGE the Work. Reading a named fixture needs none:
// marking these findings provisional pending manuscript custody would imply the
// fixture was a candidate for the Work. It is not.
const binding = requireWorkBinding(mode, manifest.work_referent);
if (!binding.ok) {
  const claim = workBindingGate(ranked, { target: manifest.work ?? 'chapter' });
  const v = validateWorkerGate(claim, { run_id: null, objective: manifest.objective ?? null, packet: { work_unit_id: null } });
  if (!v.ok) { console.error(`gate refused: ${v.refusal} — ${v.reason}`); process.exit(3); }
  console.error(`GATE  ${claim.gate_class} :: ${claim.reason}`);
  process.exit(4); // modification without a bound Work refuses; it does not proceed
}

const out = [];
out.push(`# Chapter 10 — Developmental Edit (fixture analysis)`);
out.push('');
out.push(`> Generated by \`scripts/writers-studio/develop-chapter.mjs\` against doctrine \`${doctrine.doctrine_id}\`.`);
out.push(`> Deterministic — no model call. Findings are line-addressable in the named artifact.`);
out.push(`> The editor diagnoses; it does not rewrite. Revision is the author's act.`);
out.push('');
out.push('## Referents');
out.push('');
out.push('| | |');
out.push('|---|---|');
out.push(`| **Fixture referent** | \`${fx.label}\` — \`${fx.artifact}\` L${fx.fromLine}–${fx.toLine}, sha256 \`${fixture.sha256.slice(0, 12)}\` |`);
out.push(`| **Fixture status** | ${fx.status} |`);
out.push(`| **Work referent** | ${manifest.work_referent?.status ?? 'UNRESOLVED / OUT OF SCOPE'} |`);
out.push(`| **Protagonist** | ${doctrine.protagonist.name} — settled fixture doctrine (Founder) |`);
out.push('');
out.push(`**Selecting this fixture asserts nothing about which artifact is the authoritative Chapter 10.** ${fx.not_a_claim ?? ''}`);
out.push('');
out.push('**These findings are valid against the named fixture and are not provisional.** A bound Work referent is required only to *modify* the book — a separate founder act, out of scope here.');
out.push('');
out.push(`**Governing principle.** ${doctrine.governing_principle}`);
out.push('');
out.push(`**Developmental thesis.** ${doctrine.developmental_thesis}`);
out.push('');
out.push('## Comparison corpus — archaeology');
out.push('');
out.push(`_${manifest.comparison_corpus_note ?? ''}_`);
out.push('');
out.push('| # | draft | words | protagonist | framework | crit | maj | min |');
out.push('|---:|---|---:|---:|---:|---:|---:|---:|');
ranked.forEach((r, i) => out.push(`| ${i + 1} | \`${r.label}\` | ${r.words} | ${r.protagonist} | ${r.framework} | ${r.critical} | ${r.major} | ${r.minor} |`));
out.push('');
out.push('_Order is doctrine distance across drafts, not canonicity. Nothing here nominates a Work._');
out.push('');
out.push('---');
out.push('');
out.push(`## Editorial letter — fixture: ${fx.label}`);
out.push('');
out.push(editorialLetter(analyze(fixture, doctrine), doctrine), '', '---', '');
for (const w of corpus.filter((c) => c.sha256 !== fixture.sha256)) {
  out.push(`## Comparison letter (archaeology only) — ${w.label}`);
  out.push('');
  out.push(editorialLetter(analyze(w, doctrine), doctrine), '', '---', '');
}

const outPath = path.resolve(repoRoot, arg('out', 'docs/book-studio/CHAPTER_10_DEVELOPMENTAL_EDIT_v1.md'));
writeFileSync(outPath, out.join('\n'));
console.log(`WROTE ${path.relative(repoRoot, outPath)}`);
console.log(`MODE  ${mode} :: fixture=${fx.label} :: work_referent=${manifest.work_referent?.status}`);
for (const r of ranked) console.log(`  ${r.label.padEnd(42)} crit=${r.critical} maj=${r.major} min=${r.minor}`);
