/** Optional member-selected questions, never findings or evaluations. */
export const EDITORIAL_QUESTIONS = [
  { id: 'intention', label: 'Intention and recurrence', question: 'Help me examine what each appearance contributes. Ask about any intention I have not made clear. Explore ways to preserve, deepen, redirect, or amplify the approach, and alternatives if it does not serve the reader. Present possibilities for me to choose, not a presumption that recurrence should be removed.' },
  { id: 'proportion', label: 'Length, depth, and proportion', question: 'Help me consider whether this section has the room it needs: too compressed, overextended, too abstract, or only introductory. Relate your suggestions to what I intend and what the reader needs. Offer alternatives rather than a target length.' },
  { id: 'flow', label: 'Chapter flow and book arc', question: 'How does this passage connect with what comes before and after, and with the movement of the book? Distinguish what the supplied passages establish from what needs a wider reading. Do not claim to have assessed an unread chapter or book.' },
  { id: 'examples', label: 'Examples and lived experience', question: 'Where might a concrete example, story, or lived experience help the reader understand or practice this idea? Explain what each would contribute and where it might belong. Ask me for real material; do not invent personal experiences or client accounts.' },
  { id: 'forms', label: 'Images, quotations, and practices', question: 'Explore whether an illustration, metaphor, quotation, question, or practice would help convey this meaning. Offer possible placements and tradeoffs. Do not invent quotations or attribution; mark any source that needs verification.' },
  { id: 'voice', label: 'Voice, rhythm, and what stays unsaid', question: 'Help me hear the voice, rhythm, image, and space in this passage. Consider whether explanation strengthens the work or crowds out what it lets the reader discover. Preserve my intended form rather than assuming every work should teach explicitly.' },
] as const;
