export const dynamic = 'force-dynamic';
/**
 * Practitioner — Spiralogic Report for a specific client
 *
 * GET  /api/practitioner/clients/[clientId]/spiralogic-report
 *      List reports generated by this practitioner for this client.
 *
 * POST /api/practitioner/clients/[clientId]/spiralogic-report
 *      Generate (and persist) a new report for the client.
 *
 * Auth: requireMemberId (practitioner session)
 * DB:   lib/db/postgres.ts
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireMemberId } from '@/lib/auth/session';
import { query } from '@/lib/db/postgres';

interface RouteParams {
  params: Promise<{ clientId: string }>;
}

// ---- GET — list reports ----------------------------------------------------

export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const practitionerId = await requireMemberId();
    const { clientId } = await params;

    const result = await query(
      `SELECT id, birth_data, created_at,
              report_data->>'beingArchetype'    AS being_archetype,
              report_data->>'becomingArchetype' AS becoming_archetype
       FROM spiralogic_reports
       WHERE member_id = $1
         AND practitioner_id = $2
       ORDER BY created_at DESC
       LIMIT 20`,
      [clientId, practitionerId],
    );

    return NextResponse.json({
      success: true,
      reports: result.rows.map((r) => ({
        id: r.id,
        birthData: r.birth_data,
        createdAt: r.created_at,
        beingArchetype: r.being_archetype,
        becomingArchetype: r.becoming_archetype,
      })),
    });
  } catch (err) {
    if (err instanceof Error && err.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('[practitioner/clients/[clientId]/spiralogic-report] GET error:', err);
    return NextResponse.json({ error: 'Failed to load reports' }, { status: 500 });
  }
}

// ---- POST — generate report for client -------------------------------------

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const practitionerId = await requireMemberId();
    const { clientId } = await params;

    let body: {
      birthData: {
        date: string;
        time: string;
        name?: string;
        location?: { placeName?: string };
      };
      lifeStage?: string;
      personalityNotes?: string[];
    };

    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const { birthData, lifeStage, personalityNotes } = body;

    if (!birthData?.date || !birthData?.time) {
      return NextResponse.json(
        { error: 'birthData.date and birthData.time are required' },
        { status: 400 },
      );
    }

    // Delegate to the member report generator via internal fetch
    // so we don't duplicate the AI generation logic.
    // We pass the practitionerId as x-member-id so the internal
    // route trusts it, then override the stored practitioner_id.
    const Anthropic = (await import('@anthropic-ai/sdk')).default;
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    const month = new Date(birthData.date).getMonth();
    const seasonalElement =
      month >= 2 && month <= 4 ? 'fire' :
      month >= 5 && month <= 7 ? 'water' :
      month >= 8 && month <= 10 ? 'earth' : 'air';

    const elements = ['fire', 'water', 'earth', 'air'] as const;
    type Elem = typeof elements[number];
    const elementStrengths: Record<Elem, number> = { fire: 25, water: 25, earth: 25, air: 25 };
    elementStrengths[seasonalElement as Elem] += 15;
    elements.filter((e) => e !== seasonalElement).forEach((e) => {
      elementStrengths[e] -= 5;
    });

    const contextNote = [
      lifeStage ? `Life stage: ${lifeStage}.` : '',
      (personalityNotes ?? []).length > 0 ? `Notes: ${(personalityNotes ?? []).join(', ')}.` : '',
    ].filter(Boolean).join(' ');

    const prompt = `You are the Spiralogic Evolutionary Report engine. Generate a personalized report in JSON.

Birth date: ${birthData.date}
Birth time: ${birthData.time}
Location: ${birthData.location?.placeName ?? 'unspecified'}
Name: ${birthData.name ?? 'the client'}
Dominant seasonal element: ${seasonalElement}
${contextNote}

Return ONLY valid JSON matching this structure (no markdown):
{
  "personalOverview": "<2-3 sentence soul narrative>",
  "beingArchetype": "<short archetype name>",
  "becomingArchetype": "<short archetype name>",
  "elementalInsights": {
    "fire": { "element": "Fire", "strength": ${Math.round(elementStrengths.fire)}, "planets": [], "interpretation": "<2 sentences>", "challenges": ["<c1>","<c2>"], "gifts": ["<g1>","<g2>"], "practices": ["<p1>","<p2>"] },
    "water": { "element": "Water", "strength": ${Math.round(elementStrengths.water)}, "planets": [], "interpretation": "<2 sentences>", "challenges": ["<c1>","<c2>"], "gifts": ["<g1>","<g2>"], "practices": ["<p1>","<p2>"] },
    "earth": { "element": "Earth", "strength": ${Math.round(elementStrengths.earth)}, "planets": [], "interpretation": "<2 sentences>", "challenges": ["<c1>","<c2>"], "gifts": ["<g1>","<g2>"], "practices": ["<p1>","<p2>"] },
    "air": { "element": "Air", "strength": ${Math.round(elementStrengths.air)}, "planets": [], "interpretation": "<2 sentences>", "challenges": ["<c1>","<c2>"], "gifts": ["<g1>","<g2>"], "practices": ["<p1>","<p2>"] }
  },
  "karmicAxis": {
    "northNode": { "placement": { "planet": "North Node", "sign": "", "house": 0, "degree": 0, "retrograde": false }, "interpretation": "<2 sentences>", "lessons": ["<l1>"], "evolutionary_direction": "<one-liner>" },
    "southNode": { "placement": { "planet": "South Node", "sign": "", "house": 0, "degree": 0, "retrograde": false }, "interpretation": "<2 sentences>", "lessons": ["<l1>"], "evolutionary_direction": "<one-liner>" },
    "saturn": { "placement": { "planet": "Saturn", "sign": "", "house": 0, "degree": 0, "retrograde": false }, "interpretation": "<2 sentences>", "lessons": ["<l1>"], "evolutionary_direction": "<one-liner>" },
    "pluto": { "placement": { "planet": "Pluto", "sign": "", "house": 0, "degree": 0, "retrograde": false }, "interpretation": "<2 sentences>", "lessons": ["<l1>"], "evolutionary_direction": "<one-liner>" }
  },
  "reflectiveProtocols": [
    { "name": "<ritual>", "element": "${seasonalElement}", "description": "<one sentence>", "steps": ["<s1>","<s2>","<s3>"], "timing": "<timing>" },
    { "name": "<ritual>", "element": "water", "description": "<one sentence>", "steps": ["<s1>","<s2>"], "timing": "<timing>" }
  ],
  "generatedAt": "${new Date().toISOString()}"
}`;

    const message = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 2048,
      messages: [{ role: 'user', content: prompt }],
    });

    const text = message.content[0].type === 'text' ? message.content[0].text : '';
    const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
    const reportData = JSON.parse(cleaned);

    // Persist with practitioner_id
    const result = await query(
      `INSERT INTO spiralogic_reports (member_id, practitioner_id, birth_data, report_data)
       VALUES ($1, $2, $3, $4)
       RETURNING id, created_at`,
      [clientId, practitionerId, JSON.stringify(birthData), JSON.stringify(reportData)],
    );

    const row = result.rows[0];
    return NextResponse.json({
      success: true,
      reportId: row.id,
      createdAt: row.created_at,
      report: reportData,
    });
  } catch (err) {
    if (err instanceof Error && err.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('[practitioner/clients/[clientId]/spiralogic-report] POST error:', err);
    return NextResponse.json(
      { error: 'Failed to generate report', detail: String(err) },
      { status: 500 },
    );
  }
}
