import type { A29Design } from './model';
export type Mutator=(x:any)=>void;
export const mutant=(base:A29Design,mutate:Mutator):A29Design=>{const x=structuredClone(base) as any;mutate(x);return x;};
export const defeatCandidates: readonly [string,string,Mutator][] = [
['D1-review-first','L1',x=>{x.census.find((r:any)=>r.receiver==='REVIEW_DISCUSS').standing='ADMISSION_DESIGNABLE';}],
['D2-focus-first','L2',x=>{x.census.find((r:any)=>r.receiver==='FOCUS').standing='ADMISSION_DESIGNABLE';x.census.find((r:any)=>r.receiver==='FOCUS').exactCompletionIdentity=true;}],
['D3-reuse-same-thread-producer','L7',x=>{x.first.producerId='system.writer_editorial_history';x.first.reusesSameThreadHistoryProducer=true;}],
['D4-generic-context-bag','L8',x=>{x.first.usesGenericContextBag=true;}],
['D5-carry-member-turn','L9',x=>{x.first.carriesMemberTurn=true;}],
['D6-whole-transcript','L9',x=>{x.first.carriesWholeEpisodeTranscript=true;}],
['D7-latest-source','L6',x=>{x.first.selectionBasis='LATEST';}],
['D8-first-source','L6',x=>{x.first.selectionBasis='FIRST';}],
['D9-other-relationship','L10',x=>{x.first.sourceRelationshipId='rel-2';}],
['D10-other-member','L11',x=>{x.first.sourceMemberId='member-2';}],
['D11-other-work-manuscript','L11',x=>{x.first.sourceWorkId='work-2';x.first.sourceManuscriptId='manuscript-2';}],
['D12-non-editorial-source','L12',x=>{x.first.sourceChildKind='REVIEW_DISCUSS';}],
['D13-source-index-missing','L12',x=>{x.first.sourceMaiaTurnIndex=-1;}],
['D14-source-not-maia','L13',x=>{x.first.sourceSpeaker='author';}],
['D15-unavailable-reconstructed','L14',x=>{x.first.sourceAvailable=false;}],
['D16-passage-to-section','L16',x=>{x.first.sourceScope='passage';x.first.admittedScope='section';}],
['D17-passage-to-chapter','L16',x=>{x.first.sourceScope='passage';x.first.admittedScope='chapter';}],
['D18-temporal-current','L15',x=>{x.first.sourceTemporal='CURRENT';}],
['D19-current-thread-history-producer','L7',x=>{x.first.reusesSameThreadHistoryProducer=true;}],
['D20-member-instruction-shape','L19',x=>{x.first.producerAuthorship='member';}],
['D21-source-read-proof-omitted','L18',x=>{x.first.sourceReadProofRequired=false;}],
['D22-receiver-proof-omitted','L18',x=>{x.first.receiverAdmissionProofRequired=false;}],
['D23-receiver-parent-omitted','L10',x=>{x.first.receiverRelationshipId='';}],
['D24-receiver-thread-omitted','L17',x=>{x.first.receiverThreadId='';}],
['D25-provider-authority','L20',x=>{x.first.providerAuthority=true;}],
['D26-mutation-authority','L20',x=>{x.first.mutationAuthority=true;}],
['D27-reread-locus','L20',x=>{x.first.rereadsSourceLocus=true;}],
['D28-reread-surround','L20',x=>{x.first.rereadsSurroundingWork=true;}],
['D29-summary-instead-of-turn','L9',x=>{x.first.generatesSummary=true;}],
['D30-multiple-first-classes','L5',x=>{x.first.materialClass='MULTIPLE';}],
];
