/**
 * Execution Types for AIN → Agent Zero Integration
 *
 * These types define the contract between the AIN committee deliberation system
 * and the Agent Zero execution layer. The committee decides, the executor runs.
 *
 * Phase 1: HTTP bridge to Agent Zero
 * Future: A2A protocol, MCP server integration
 */

// ─── Task Types ────────────────────────────────────────────────────────────────

export type ExecutionTaskType =
  | 'web_research'      // Search, fetch, summarize web content
  | 'repo_change'       // Git operations, code modifications
  | 'run_command'       // Shell command execution
  | 'data_migration'    // Database operations, data transforms
  | 'file_ops'          // Read, write, transform files
  | 'code_analysis'     // Static analysis, linting, type checking
  | 'test_execution'    // Run test suites
  | 'deployment'        // Deploy, build, release operations
  | 'other';            // Fallback for uncategorized tasks

// ─── Risk Levels (Sovereignty Controls) ────────────────────────────────────────

export type ExecutionRisk =
  | 'low'     // Read-only, safe operations (web research, file reads)
  | 'medium'  // Writes files, but constrained to specific paths
  | 'high';   // Shell execution, network access, installs

// ─── Execution Task ────────────────────────────────────────────────────────────

export interface ExecutionTask {
  /** Unique task identifier (UUID) */
  id: string;

  /** ISO timestamp when task was created */
  createdAt: string;

  /** Type of execution being requested */
  type: ExecutionTaskType;

  /** Risk level for sovereignty controls */
  risk: ExecutionRisk;

  /** Human-readable title for the task */
  title: string;

  /** Detailed instructions for the executor */
  instructions: string;

  // ─── Optional Context ────────────────────────────────────────────────────────

  /** Repository path for code operations */
  repoPath?: string;

  /** Specific files to operate on */
  files?: string[];

  /** URLs for web research tasks */
  urls?: string[];

  /** Additional context from the deliberation */
  context?: Record<string, unknown>;

  // ─── Sovereignty Controls (defaults are restrictive) ─────────────────────────

  /** Allow network access (default: false) */
  allowNetwork?: boolean;

  /** Allow shell command execution (default: false) */
  allowShell?: boolean;

  /** Allow file writes (default: false) */
  allowWrites?: boolean;

  /** Maximum execution time in milliseconds (default: 30000) */
  timeoutMs?: number;

  // ─── Traceability ────────────────────────────────────────────────────────────

  /** Agent or route that requested the execution */
  requestedBy?: string;

  /** Correlation ID for tracing (deliberation_id, session_id, etc.) */
  correlationId?: string;

  /** User ID for audit trail */
  userId?: string;

  /** Session ID for context */
  sessionId?: string;
}

// ─── Execution Result ──────────────────────────────────────────────────────────

export interface ExecutionResult {
  /** Task ID this result corresponds to */
  taskId: string;

  /** Whether execution succeeded */
  ok: boolean;

  /** Human-readable summary of what happened */
  summary: string;

  // ─── Artifact Outputs (optional) ─────────────────────────────────────────────

  /** Standard output from command execution */
  stdout?: string;

  /** Standard error from command execution */
  stderr?: string;

  /** File patches generated by the execution */
  patches?: Array<{
    file: string;
    diff: string;
  }>;

  /** Files created or modified */
  filesModified?: string[];

  /** Web research findings */
  webFindings?: Array<{
    url: string;
    title: string;
    summary: string;
  }>;

  // ─── Execution Trace ─────────────────────────────────────────────────────────

  /** ISO timestamp when execution started */
  startedAt?: string;

  /** ISO timestamp when execution finished */
  finishedAt?: string;

  /** Execution duration in milliseconds */
  durationMs?: number;

  /** Provider that handled the execution */
  provider?: string;

  // ─── Error Information ───────────────────────────────────────────────────────

  /** Error code if execution failed */
  errorCode?: string;

  /** Detailed error message if execution failed */
  errorMessage?: string;

  /** Whether the error is retryable */
  retryable?: boolean;

  // ─── Raw Payload ─────────────────────────────────────────────────────────────

  /** Raw response from the executor (for debugging) */
  raw?: unknown;
}

// ─── Executor Provider Types ───────────────────────────────────────────────────

export type ExecutorProvider =
  | 'agent_zero'    // Agent Zero HTTP bridge
  | 'local_shell'   // Direct local shell execution (future)
  | 'mcp_tool'      // MCP tool invocation (future)
  | 'a2a_agent';    // A2A protocol agent (future)

// ─── Delegation Decision Types ─────────────────────────────────────────────────

export interface DelegationDecision {
  /** Whether to delegate to an executor */
  shouldDelegate: boolean;

  /** Reason for the decision */
  reason: string;

  /** Suggested executor provider */
  suggestedProvider?: ExecutorProvider;

  /** Suggested risk level */
  suggestedRisk?: ExecutionRisk;

  /** Extracted actions from deliberation meta */
  extractedActions?: string[];
}

// ─── Execution Log Entry (for database) ────────────────────────────────────────

export interface ExecutionLogEntry {
  /** Auto-generated ID */
  id?: number;

  /** ISO timestamp */
  createdAt: string;

  /** Deliberation ID that triggered this execution */
  deliberationId?: string;

  /** Execution task ID */
  taskId: string;

  /** Executor provider used */
  provider: ExecutorProvider;

  /** Task type */
  taskType: ExecutionTaskType;

  /** Risk level */
  risk: ExecutionRisk;

  /** Execution succeeded */
  ok: boolean;

  /** Human-readable summary */
  summary: string;

  /** Execution duration in milliseconds */
  durationMs?: number;

  /** User ID for audit */
  userId?: string;

  /** Full result as JSON (for debugging) */
  resultJson?: ExecutionResult;
}
