import type { CustodyDesign } from './model';

export type LawResult = { id: string; pass: boolean; detail: string };

export function evaluate(d: CustodyDesign): LawResult[] {
  return [
    { id:'F1', pass:d.parentIdentitySource!=='ASK_THREAD_ID', detail:'ask_thread is never parent identity' },
    { id:'F2', pass:d.parentIdentitySource!=='SESSION_ID', detail:'sessionId is never parent identity' },
    { id:'F3', pass:d.parentIdentitySource!=='PROPOSAL_CHAIN_ID', detail:'proposalChainId is never parent identity' },
    { id:'F4', pass:d.parentIdentitySource!=='READING_ID', detail:'readingId is never parent identity' },
    { id:'F5', pass:d.parentIdentitySource==='A2_OPAQUE', detail:'A2 parent identity is independently opaque' },
    { id:'F6', pass:!d.parentStoresManuscriptProse, detail:'parent stores no manuscript prose' },
    { id:'F7', pass:!d.parentGrantsDisclosure&&!d.parentGrantsCognition, detail:'parent grants no disclosure/cognition authority' },
    { id:'F8', pass:d.bindingProof==='SERVER_VERIFIED_MEMBER_LIVING_WORK_MANUSCRIPT_DECLARATION'&&!d.browserSuppliedIdsTrustedForOwnership, detail:'ownership is server-derived from declaration custody' },
    { id:'F9', pass:d.storesLivingWorkId&&d.storesManuscriptId&&d.appendReverifiesCurrentDeclaration, detail:'foreign Work child cannot be admitted' },
    { id:'F10', pass:d.storesMemberId&&d.bindingProof==='SERVER_VERIFIED_MEMBER_LIVING_WORK_MANUSCRIPT_DECLARATION', detail:'foreign member child cannot be admitted' },
    { id:'F11', pass:d.childReferenceShape==='CLOSED_DISCRIMINATED_UNION'&&d.exactlyOneChildKind, detail:'exactly one child kind' },
    { id:'F12', pass:d.childReferenceShape==='CLOSED_DISCRIMINATED_UNION'&&d.exactlyOneChildKind, detail:'zero-child episode is unrepresentable' },
    { id:'F13', pass:d.reviewUsesReadingLocalAddress&&!d.observationIdSubstitutesForReadingLocalAddress, detail:'Review address remains readingId + observationKey' },
    { id:'F14', pass:d.parentOrder==='RELATIONSHIP_SEQUENCE_UNDER_PARENT_LOCK', detail:'timestamp is not parent ordering authority' },
    { id:'F15', pass:d.parentOrder!=='CHILD_TURN_INDEX', detail:'heterogeneous child indexes do not order parent' },
    { id:'F16', pass:d.concurrentAppend==='SERIALIZE_AND_UNIQUE', detail:'concurrent append has one unambiguous order' },
    { id:'F17', pass:!d.admitsPrePersistenceRefusalAsCompleted, detail:'pre-persistence refusal is not completed episode' },
    { id:'F18', pass:!d.admitsAttemptedFocusCrossingAsCompleted, detail:'attempted Focus crossing is not completed cognition' },
    { id:'F19', pass:!d.relationshipMembershipImpliesCognitionCarry, detail:'relationship membership grants no cognition carry' },
    { id:'F20', pass:d.requestedExecutedScopeMustMatch, detail:'requested/executed scope must match for executable episode' },
    { id:'F21', pass:!d.chapterIdentityFromHeading, detail:'heading string is not chapter identity' },
    { id:'F22', pass:!d.wholeWorkExecutableFromRouteVocabulary, detail:'route vocabulary does not establish whole-Work conversation' },
    { id:'F23', pass:!d.sentenceExecutableFromArbitrarySelection, detail:'arbitrary selection is not sentence locator' },
    { id:'F24', pass:!d.latestEpisodeIsPlace&&!d.latestScopeIsPlace&&!d.parentClaimsDurablePlace, detail:'parent custody is not durable place' },
    { id:'F25', pass:d.pluralityRepresentable&&d.relationshipSelection==='EXPLICIT_SELECTION', detail:'plurality is explicit; latest/first never wins silently' },
    { id:'F26', pass:!d.parentStoresChildResponseProse&&!d.copiedParentProseSurvivesChildDeletion, detail:'child deletion cannot leave copied prose in parent' },
    { id:'F27', pass:!d.parentDeletionCascadesToChildren, detail:'deleting parent does not delete child semantic objects' },
    { id:'F28', pass:!d.childReferenceMutable&&d.childDeletionPolicy==='OPAQUE_REF_BECOMES_UNAVAILABLE', detail:'missing child never repoints existing episode' },
    { id:'F29', pass:d.storesHistoryPolicySnapshot&&!d.priorEpisodePositionMutable, detail:'episode cannot mutate child history policy or prior succession' },
    { id:'F30', pass:!d.parentGrantsMutation, detail:'parent grants no Work mutation authority' },

    { id:'P1', pass:d.parentIdentitySource==='A2_OPAQUE', detail:'parent id independent from children' },
    { id:'P2', pass:d.pluralityRepresentable, detail:'multiple relationships per Work remain representable' },
    { id:'P3', pass:d.storesMemberId&&d.storesLivingWorkId&&d.storesManuscriptId, detail:'member + Living Work + manuscript binding explicit' },
    { id:'P4', pass:d.parentOrder==='RELATIONSHIP_SEQUENCE_UNDER_PARENT_LOCK'&&!d.priorEpisodePositionMutable, detail:'parent succession explicit and immutable' },
    { id:'P5', pass:d.concurrentAppend==='SERIALIZE_AND_UNIQUE', detail:'concurrency invariant specified' },
    { id:'P6', pass:d.childReferenceShape==='CLOSED_DISCRIMINATED_UNION'&&d.exactlyOneChildKind, detail:'typed child reference union' },
    { id:'P7', pass:d.focusGranularity==='FOCUS_COMPLETED_EXCHANGE'&&d.editorialGranularity==='EDITORIAL_COMPLETED_TURN_PAIR'&&d.reviewGranularity==='REVIEW_COMPLETED_ACT', detail:'exact child-act granularity decided' },
    { id:'P8', pass:!d.parentStoresManuscriptProse&&!d.parentStoresChildResponseProse, detail:'parent duplicates no child prose' },
    { id:'P9', pass:d.childDeletionPolicy==='OPAQUE_REF_BECOMES_UNAVAILABLE', detail:'missing child remains unavailable, never reconstructed' },
    { id:'P10', pass:d.storesRequestedScopeSnapshot&&d.storesExecutedScopeSnapshot&&d.storesTemporalPostureSnapshot&&d.storesHistoryPolicySnapshot&&d.storesContinuationSnapshot&&d.storesAuthorityClassSnapshot&&d.storesCarryPolicySnapshot, detail:'dangerous reinterpretation fields snapshot at admission' },
    { id:'P11', pass:!d.admitsPrePersistenceRefusalAsCompleted&&!d.admitsAttemptedFocusCrossingAsCompleted&&!d.admitsIncompleteReviewAsAnswered&&!d.admitsEditorialThreadOpenAsCompletedMaiaTurn, detail:'only truthful completed child acts admitted' },
    { id:'P12', pass:!d.priorDisclosurePointerGrantsStanding&&!d.parentGrantsDisclosure, detail:'authority pointers remain provenance only' },
    { id:'P13', pass:d.reviewUsesReadingLocalAddress&&!d.observationIdSubstitutesForReadingLocalAddress, detail:'Review identity remains reading-local' },
    { id:'P14', pass:d.reviewGranularity==='REVIEW_COMPLETED_ACT'&&d.storesHistoryPolicySnapshot, detail:'Review single-act/history NONE can be preserved' },
    { id:'P15', pass:!d.admitsPrePersistenceRefusalAsCompleted, detail:'Sanctuary refusal cannot become completed episode' },
    { id:'P16', pass:d.requestedExecutedScopeMustMatch&&d.storesRequestedScopeSnapshot&&d.storesExecutedScopeSnapshot, detail:'scope truth is durable' },
    { id:'P17', pass:!d.wholeWorkExecutableFromRouteVocabulary&&!d.sentenceExecutableFromArbitrarySelection&&!d.chapterIdentityFromHeading, detail:'unsupported scopes remain explicit' },
    { id:'P18', pass:!d.parentGrantsMutation, detail:'parent grants no Work mutation' },
    { id:'P19', pass:!d.parentGrantsPersonalMemory, detail:'parent grants no personal-memory widening' },
    { id:'P20', pass:!d.parentClaimsDurablePlace&&!d.latestEpisodeIsPlace&&!d.latestScopeIsPlace, detail:'parent is not place' },
    { id:'P21', pass:!d.parentDeletionCascadesToChildren&&!d.copiedParentProseSurvivesChildDeletion, detail:'deletion semantics preserve child sovereignty without prose backdoor' },
    { id:'P22', pass:d.bindingProof==='SERVER_VERIFIED_MEMBER_LIVING_WORK_MANUSCRIPT_DECLARATION'&&d.expressionRemovalMakesHistoricalOnly, detail:'Work/manuscript relation is explicit and removal does not rewrite history' },
    { id:'P23', pass:d.readProjection==='CONTENT_FREE_RELATIONSHIP_INDEX'&&d.provenanceRemainsChildAuthoritative, detail:'parent read works without child prose' },
    { id:'P24', pass:!d.reusesAskThreadsAsParent&&d.parentIdentitySource==='A2_OPAQUE', detail:'existing child stores are not semantically overloaded' },
    { id:'P25', pass:d.completionDerivedFromAdmission, detail:'design proves custody without runtime/schema implementation' },
  ];
}
