/**
 * PHI ACCESSOR: practitioner_client_notes.content
 *
 * Free-Text PHI Doctrine — practitioner-private notes on Studio clients.
 *
 * UNLIKE the other accessors in this directory, this surface has NO Stage A /
 * Stage B / Stage C progression. The table was created encrypted-from-birth
 * with no plaintext `content` column, so there is nothing to dual-write and
 * nothing to fall back to. Reads decrypt or they fail — there is no plaintext
 * path to silently degrade into.
 *
 * @see docs/security/free-text-phi-doctrine.md
 * @see database/migrations/20260730000001_practitioner_client_notes.sql
 */

import {
  encryptForDB,
  decryptFromDB,
  stripEncryptedColumns,
  PHIContext,
  PHIEncryptionMeta,
} from '@/lib/security/phiEncryption';

const TABLE = 'practitioner_client_notes';
const COLUMN = 'content';

export interface ClientNotePHIContext {
  /** practitioner_client_notes.id — must be known before encrypting (AAD binds to it) */
  rowId: string;
  /** practitioner_client_notes.practitioner_id — the owner */
  practitionerId: string;
}

/** Raw DB row shape (ciphertext columns present, no plaintext sibling). */
export interface ClientNoteRow {
  id: string;
  client_id: string;
  practitioner_id: string;
  content_enc: string;
  content_enc_meta: PHIEncryptionMeta | string;
  note_date: string | Date;
  created_at: string | Date;
  updated_at: string | Date;
}

/** Decrypted, API-safe note. */
export interface ClientNote {
  id: string;
  clientId: string;
  content: string;
  noteDate: string;
  createdAt: string;
  updatedAt: string;
}

function buildContext(ctx: ClientNotePHIContext): PHIContext {
  return {
    table: TABLE,
    column: COLUMN,
    rowId: ctx.rowId,
    ownerId: ctx.practitionerId,
  };
}

/**
 * Encrypt note content for INSERT/UPDATE.
 *
 * `rowId` must be generated by the caller BEFORE this call (randomUUID()) —
 * the additional authenticated data is bound to it, so encrypting against a
 * placeholder id would produce a row that can never be decrypted.
 */
export function encryptClientNoteContent(
  content: string,
  ctx: ClientNotePHIContext
): { contentEnc: string; contentEncMeta: string } {
  const { ciphertext, meta } = encryptForDB(content, buildContext(ctx));
  return { contentEnc: ciphertext, contentEncMeta: JSON.stringify(meta) };
}

/**
 * Decrypt note content.
 * Throws if the ciphertext or AAD do not match — callers must handle it.
 */
export function decryptClientNoteContent(
  contentEnc: string,
  contentEncMeta: PHIEncryptionMeta | string,
  ctx: ClientNotePHIContext
): string {
  const meta =
    typeof contentEncMeta === 'string' ? JSON.parse(contentEncMeta) : contentEncMeta;
  return decryptFromDB(contentEnc, meta, buildContext(ctx));
}

function toIsoDate(value: string | Date): string {
  return value instanceof Date ? value.toISOString() : String(value);
}

/**
 * Convert a raw row into the API-safe shape, decrypting content.
 *
 * Returns `null` when decryption fails rather than emitting a row with an
 * empty or placeholder body — a note that cannot be decrypted must not be
 * presented as an empty note, because that reads as "the practitioner wrote
 * nothing" rather than "this content is unavailable".
 */
export function decryptClientNoteRow(row: ClientNoteRow): ClientNote | null {
  const ctx: ClientNotePHIContext = {
    rowId: row.id,
    practitionerId: row.practitioner_id,
  };

  let content: string;
  try {
    content = decryptClientNoteContent(row.content_enc, row.content_enc_meta, ctx);
  } catch (error) {
    console.error('[PHI] practitioner_client_notes decrypt failed for note:', row.id, error);
    return null;
  }

  return {
    id: row.id,
    clientId: row.client_id,
    content,
    noteDate: toIsoDate(row.note_date),
    createdAt: toIsoDate(row.created_at),
    updatedAt: toIsoDate(row.updated_at),
  };
}

/** Decrypt a list of rows, dropping any that fail to decrypt. */
export function decryptClientNoteRows(rows: ClientNoteRow[]): ClientNote[] {
  return rows
    .map(decryptClientNoteRow)
    .filter((note): note is ClientNote => note !== null);
}

/**
 * SECURITY: strip *_enc columns before anything leaves the data layer.
 * The API shape above never carries them, but this guards ad-hoc `SELECT *`
 * paths that might otherwise return ciphertext to a client.
 */
export function sanitizeClientNoteRow<T>(row: T): T {
  return stripEncryptedColumns(row);
}

export function sanitizeClientNoteRows<T>(rows: T[]): T[] {
  return rows.map(sanitizeClientNoteRow);
}
