#!/usr/bin/env bash
# =============================================================================
# Worktree reclaim plan — reads a worktree-census TSV, WRITES A PROPOSAL.
#
#   scripts/ops/worktree-reclaim-plan.sh ~/MAIA-SOVEREIGN/logs/worktrees-2026-09-22.tsv
#   PLAN_DIR=... ARCHIVE_DIR="/Volumes/T7 Shield/worktree-bundles" REPO=~/MAIA-SOVEREIGN ...
#
# Produces, under PLAN_DIR (default: logs/reclaim-plan-<date>/ beside the TSV):
#   PLAN.txt          GB per act, per class, projected internal free space
#   act-a-regen.sh    delete node_modules/.next/.turbo/coverage/dist in clean,
#                     pushed worktrees (REMOVABLE + RETAIN) on the INTERNAL disk
#   act-b-remove.sh   git worktree remove for REMOVABLE worktrees on the internal disk
#   act-c-preserve.sh push (policy-allowed branch names) or bundle (everything
#                     else) every PRESERVE worktree and every HOLD row with
#                     unpushed commits, into ARCHIVE_DIR
#   inspect.txt       INSPECT and HOLD rows, for a person, no commands
#
# THIS SCRIPT CHANGES NOTHING. The act scripts it writes refuse to run unless
# RECLAIM_AUTHORIZED=1 is set, re-verify each worktree is still clean at
# execution time, and stop on the first unexpected state. Authorization is a
# founder act per script, not per run of this generator.
# =============================================================================
set -u
TSV="${1:?usage: $0 <worktrees-YYYY-MM-DD.tsv>}"
[[ -f "$TSV" ]] || { echo "no such file: $TSV" >&2; exit 2; }
REPO="${REPO:-$HOME/MAIA-SOVEREIGN}"
CANON="${CANON:-clean-main-no-secrets}"
ARCHIVE_DIR="${ARCHIVE_DIR:-/Volumes/T7 Shield/worktree-bundles}"
STAMP="$(basename "$TSV" .tsv | sed 's/^worktrees-//')"
PLAN_DIR="${PLAN_DIR:-$(dirname "$TSV")/reclaim-plan-$STAMP}"
mkdir -p "$PLAN_DIR"
A="$PLAN_DIR/act-a-regen.sh"; B="$PLAN_DIR/act-b-remove.sh"; C="$PLAN_DIR/act-c-preserve.sh"
I="$PLAN_DIR/inspect.txt"; P="$PLAN_DIR/PLAN.txt"

guard() {  # common prologue for every generated act script
cat <<EOG
#!/usr/bin/env bash
# Generated by worktree-reclaim-plan.sh from $TSV on $(date -u +%FT%TZ)
# $1
set -u
if [[ "\${RECLAIM_AUTHORIZED:-0}" != "1" ]]; then
  echo "NOT AUTHORIZED: this script would $2." >&2
  echo "Read it, then run: RECLAIM_AUTHORIZED=1 \$0" >&2
  exit 3
fi
REPO="$REPO"
clean_or_stop() {  # refuse to touch a worktree whose state moved since the census
  local wt="\$1"
  if [[ ! -d "\$wt" ]]; then echo "STOP: \$wt no longer exists" >&2; exit 4; fi
  if [[ -n "\$(git -C "\$wt" status --porcelain 2>/dev/null)" ]]; then
    echo "STOP: \$wt is no longer clean (modified or untracked files). Re-run the census." >&2; exit 4
  fi
  if [[ "\$(git -C "\$wt" rev-list --count HEAD --not --remotes 2>/dev/null)" != "0" ]]; then
    echo "STOP: \$wt now has commits on no remote." >&2; exit 4
  fi
}
freed_before=\$(df -k "\$HOME" | awk 'NR==2{print \$4}')
EOG
}
epilogue() {
cat <<'EOG'
freed_after=$(df -k "$HOME" | awk 'NR==2{print $4}')
awk -v a="$freed_before" -v b="$freed_after" 'BEGIN{printf "internal free: %.1f GB -> %.1f GB (+%.1f GB)\n", a/1048576, b/1048576, (b-a)/1048576}'
EOG
}

guard "ACT A: delete regenerable build state in clean, pushed worktrees on the internal disk." \
      "delete node_modules/.next/.turbo/coverage/dist directories" > "$A"
guard "ACT B: remove REMOVABLE worktrees (clean, pushed, merged into $CANON) on the internal disk." \
      "run git worktree remove on merged worktrees" > "$B"
guard "ACT C: push or bundle every worktree holding commits that exist on no remote." \
      "push branches and write git bundles to $ARCHIVE_DIR" > "$C"
echo "mkdir -p \"$ARCHIVE_DIR\" || { echo 'STOP: archive dir unavailable' >&2; exit 4; }" >> "$C"
: > "$I"

a_gb=0; a_n=0; b_gb=0; b_n=0; c_n=0
while IFS=$'\t' read -r path vol branch head total regen source mod unt unp merged cls nest; do
  [[ "$path" == "path" ]] && continue
  [[ "$total" == "-" ]] && { echo "HOLD  $path  (missing or unreadable)" >> "$I"; continue; }
  case "$cls" in
    REMOVABLE|RETAIN)
      if [[ "$vol" == "internal" ]] && awk -v r="$regen" 'BEGIN{exit !(r>0)}'; then
        printf '\n# %s  %s GB regenerable  [%s]\nclean_or_stop "%s"\n' "$path" "$regen" "$cls" "$path" >> "$A"
        find "$path" -maxdepth 4 -type d \( -name node_modules -o -name .next -o -name .turbo -o -name coverage -o -name dist \) -prune -print 2>/dev/null \
          | while IFS= read -r d; do printf 'rm -rf "%s"\n' "$d" >> "$A"; done
        a_gb=$(awk -v x="$a_gb" -v y="$regen" 'BEGIN{print x+y}'); a_n=$((a_n+1))
      fi
      if [[ "$cls" == "REMOVABLE" && "$vol" == "internal" ]]; then
        printf '\n# %s  %s GB  branch %s  merged into %s\nclean_or_stop "%s"\ngit -C "$REPO" worktree remove "%s"\n' \
          "$path" "$total" "$branch" "$CANON" "$path" "$path" >> "$B"
        b_gb=$(awk -v x="$b_gb" -v y="$total" 'BEGIN{print x+y}'); b_n=$((b_n+1))
      fi ;;
  esac
  if [[ "$unp" != "0" && "$unp" != "?" ]]; then
    c_n=$((c_n+1))
    safe=$(echo "${branch:-detached}-${head}" | tr '/ ' '__')
    case "$branch" in
      main|clean-main-no-secrets|feature/*|fix/*|chore/*)
        printf '\n# %s  %s commit(s) on no remote\ngit -C "%s" push -u origin "%s" || { echo "STOP: push refused for %s; bundle instead" >&2; exit 4; }\n' \
          "$path" "$unp" "$path" "$branch" "$branch" >> "$C" ;;
      *)
        printf '\n# %s  %s commit(s) on no remote  (branch %s not pushable under branch policy -> bundle)\ngit -C "%s" bundle create "%s/%s.bundle" "origin/%s..HEAD" && git bundle verify "%s/%s.bundle" >/dev/null || { echo "STOP: bundle failed for %s" >&2; exit 4; }\n' \
          "$path" "$unp" "$branch" "$path" "$ARCHIVE_DIR" "$safe" "$CANON" "$ARCHIVE_DIR" "$safe" "$path" >> "$C" ;;
    esac
  fi
  case "$cls" in
    INSPECT*|HOLD*) printf '%-10s %6s GB  mod=%s unt=%s unpushed=%s merged=%s  %s  %s\n' "$cls" "$total" "$mod" "$unt" "$unp" "$merged" "$branch" "$path" >> "$I" ;;
  esac
done < "$TSV"
epilogue >> "$A"; epilogue >> "$B"
echo 'echo "ACT C complete: every listed worktree now has its commits on origin or in a verified bundle."' >> "$C"
chmod +x "$A" "$B" "$C"

free_now=$(df -k "$HOME" 2>/dev/null | awk 'NR==2{printf "%.1f", $4/1048576}')
{
  echo "WORKTREE RECLAIM PLAN — proposal only, generated $(date -u +%FT%TZ) from $TSV"
  echo "internal free now: ${free_now:-?} GB"
  echo
  printf 'ACT A  regen delete in %d clean pushed internal worktrees   ~%.1f GB   %s\n' "$a_n" "$a_gb" "$A"
  printf 'ACT B  worktree remove, %d REMOVABLE internal worktrees      ~%.1f GB   %s\n' "$b_n" "$b_gb" "$B"
  printf 'ACT C  push or bundle %d worktrees with unpushed commits     0 GB freed  %s\n' "$c_n" "$C"
  printf 'INSPECT/HOLD rows for a person (no commands):                %s\n' "$I"
  echo
  awk -v a="$a_gb" -v b="$b_gb" -v f="${free_now:-0}" 'BEGIN{printf "projected internal free after A then B: ~%.1f GB (A and B overlap on REMOVABLE regen; B removes it either way)\n", f+a+b}'
  echo
  echo "Order: C first (nothing is lost if C never runs, but it must precede any removal of a PRESERVE row),"
  echo "       then A (lossless everywhere: npm ci / next build regenerates), then B (merged worktrees only)."
  echo "Each act script refuses without RECLAIM_AUTHORIZED=1, re-checks cleanliness per worktree, stops on drift."
  echo "Nothing in this generator modified the filesystem."
} | tee "$P"
