#!/usr/bin/env bash
# =============================================================================
# Worktree reclaim plan — reads a worktree-census TSV, WRITES A PROPOSAL.
#
#   scripts/ops/worktree-reclaim-plan.sh ~/MAIA-SOVEREIGN/logs/worktrees-2026-09-22.tsv
#   PLAN_DIR=... ARCHIVE_DIR="/Volumes/T7 Shield/worktree-bundles" REPO=~/MAIA-SOVEREIGN ...
#
# Produces, under PLAN_DIR (default: logs/reclaim-plan-<date>/ beside the TSV):
#   PLAN.txt          GB per act, per class, projected internal free space
#   act-a-regen.sh    delete node_modules/.next/.turbo/coverage/dist in clean,
#                     pushed worktrees (REMOVABLE + RETAIN) on the INTERNAL disk
#   act-b-remove.sh   git worktree remove for REMOVABLE worktrees on the internal disk
#   act-c-preserve.sh push (policy-allowed branch names) or bundle (everything
#                     else) every PRESERVE worktree and every HOLD row with
#                     unpushed commits, into ARCHIVE_DIR
#   inspect.txt       INSPECT and HOLD rows, for a person, no commands
#
# THIS SCRIPT CHANGES NOTHING. The act scripts it writes refuse to run unless
# RECLAIM_AUTHORIZED=1 is set, re-verify each worktree is still clean at
# execution time, and stop on the first unexpected state. Authorization is a
# founder act per script, not per run of this generator.
# =============================================================================
set -u
TSV="${1:?usage: $0 <worktrees-YYYY-MM-DD.tsv>}"
[[ -f "$TSV" ]] || { echo "no such file: $TSV" >&2; exit 2; }
REPO="${REPO:-$HOME/MAIA-SOVEREIGN}"
CANON="${CANON:-clean-main-no-secrets}"
ARCHIVE_DIR="${ARCHIVE_DIR:-/Volumes/T7 Shield/worktree-bundles}"
STAMP="$(basename "$TSV" .tsv | sed 's/^worktrees-//')"
PLAN_DIR="${PLAN_DIR:-$(dirname "$TSV")/reclaim-plan-$STAMP}"
mkdir -p "$PLAN_DIR"
A="$PLAN_DIR/act-a-regen.sh"; B="$PLAN_DIR/act-b-remove.sh"; C="$PLAN_DIR/act-c-preserve.sh"
I="$PLAN_DIR/inspect.txt"; P="$PLAN_DIR/PLAN.txt"

guard() {  # common prologue for every generated act script
cat <<EOG
#!/usr/bin/env bash
# Generated by worktree-reclaim-plan.sh from $TSV on $(date -u +%FT%TZ)
# $1
set -u
if [[ "\${RECLAIM_AUTHORIZED:-0}" != "1" ]]; then
  echo "NOT AUTHORIZED: this script would $2." >&2
  echo "Read it, then run: RECLAIM_AUTHORIZED=1 \$0" >&2
  exit 3
fi
REPO="$REPO"
# A worktree whose state differs from the census is never touched. Default
# RECLAIM_ON_DRIFT=stop ends the act there (S4: stop on unexpected state);
# RECLAIM_ON_DRIFT=skip leaves that worktree alone, continues with the rest,
# and exits non-zero at the end naming every skipped path.
ON_DRIFT="\${RECLAIM_ON_DRIFT:-stop}"; SKIPPED=""
drift() { echo "DRIFT: \$1" >&2; if [[ "\$ON_DRIFT" == "skip" ]]; then SKIPPED="\$SKIPPED"$'\n'"\$1"; return 1; fi; exit 4; }
clean_or_stop() {
  local wt="\$1"
  [[ -d "\$wt" ]] || { drift "\$wt no longer exists"; return; }
  [[ -z "\$(git -C "\$wt" status --porcelain 2>/dev/null)" ]] || { drift "\$wt has modified or untracked files"; return; }
  [[ "\$(git -C "\$wt" rev-list --count HEAD --not --remotes 2>/dev/null)" == "0" ]] || { drift "\$wt has commits on no remote"; return; }
}
freed_before=\$(df -k "\$HOME" | awk 'NR==2{print \$4}')
EOG
}
epilogue() {
cat <<'EOG'
freed_after=$(df -k "$HOME" | awk 'NR==2{print $4}')
awk -v a="$freed_before" -v b="$freed_after" 'BEGIN{printf "internal free: %.1f GB -> %.1f GB (+%.1f GB)\n", a/1048576, b/1048576, (b-a)/1048576}'
if [[ -n "$SKIPPED" ]]; then echo "SKIPPED (state differed from the census; re-run the census before touching these):$SKIPPED" >&2; exit 5; fi
EOG
}

guard "ACT A: delete regenerable build state in clean, pushed worktrees on the internal disk." \
      "delete node_modules/.next/.turbo/coverage/dist directories" > "$A"
guard "ACT B: remove REMOVABLE worktrees (clean, pushed, merged into $CANON) on the internal disk." \
      "run git worktree remove on merged worktrees" > "$B"
guard "ACT C: push or bundle every worktree holding commits that exist on no remote." \
      "push branches and write git bundles to $ARCHIVE_DIR" > "$C"
cat >> "$C" <<EOG
mkdir -p "$ARCHIVE_DIR" || { echo 'STOP: archive dir unavailable' >&2; exit 4; }
# push_or_bundle <worktree> <branch-or-empty> <bundle-file>
# A push is attempted only for a policy-allowed branch name and only as a
# fast-forward; a refusal (diverged remote) is not an error to force through,
# it is the signal to preserve these commits in a bundle instead.
push_or_bundle() {
  local wt="\$1" br="\$2" bf="\$3"
  if [[ -n "\$br" ]]; then
    if git -C "\$wt" push -u origin "\$br"; then return 0; fi
    echo "push refused for \$br (remote diverged or policy); preserving as bundle instead" >&2
  fi
  git -C "\$wt" bundle create "\$bf" "origin/$CANON..HEAD" && git -C "\$wt" bundle verify "\$bf" >/dev/null \\
    || { echo "STOP: bundle failed for \$wt" >&2; exit 4; }
}
EOG
: > "$I"

a_gb=0; a_n=0; b_gb=0; b_n=0; c_n=0
while IFS=$'\t' read -r path vol branch head total regen source mod unt unp merged cls nest; do
  [[ "$path" == "path" ]] && continue
  [[ "$total" == "-" ]] && { echo "HOLD  $path  (missing or unreadable)" >> "$I"; continue; }
  case "$cls" in
    REMOVABLE|RETAIN)
      if [[ "$vol" == "internal" ]] && awk -v r="$regen" 'BEGIN{exit !(r>0)}'; then
        printf '\n# %s  %s GB regenerable  [%s]\nif clean_or_stop "%s"; then\n' "$path" "$regen" "$cls" "$path" >> "$A"
        find "$path" -maxdepth 4 -type d \( -name node_modules -o -name .next -o -name .turbo -o -name coverage -o -name dist \) -prune -print 2>/dev/null \
          | while IFS= read -r d; do printf '  rm -rf "%s"\n' "$d" >> "$A"; done
        echo "fi" >> "$A"
        a_gb=$(awk -v x="$a_gb" -v y="$regen" 'BEGIN{print x+y}'); a_n=$((a_n+1))
      fi
      if [[ "$cls" == "REMOVABLE" && "$vol" == "internal" ]]; then
        printf '\n# %s  %s GB  branch %s  merged into %s\nif clean_or_stop "%s"; then git -C "$REPO" worktree remove "%s"; fi\n' \
          "$path" "$total" "$branch" "$CANON" "$path" "$path" >> "$B"
        b_gb=$(awk -v x="$b_gb" -v y="$total" 'BEGIN{print x+y}'); b_n=$((b_n+1))
      fi ;;
  esac
  if [[ "$unp" != "0" && "$unp" != "?" ]]; then
    c_n=$((c_n+1))
    safe=$(echo "${branch:-detached}-${head}" | sed 's/(detached)/detached/' | tr '/ ' '__')
    case "$branch" in
      main|clean-main-no-secrets|feature/*|fix/*|chore/*) pushable="$branch" ;;
      *) pushable="" ;;
    esac
    printf '\n# %s  %s commit(s) on no remote  branch=%s  %s\npush_or_bundle "%s" "%s" "%s/%s.bundle"\n' \
      "$path" "$unp" "$branch" "$([[ -n "$pushable" ]] && echo 'push if fast-forward, else bundle' || echo 'not pushable under branch policy -> bundle')" \
      "$path" "$pushable" "$ARCHIVE_DIR" "$safe" >> "$C"
  fi
  case "$cls" in
    INSPECT*|HOLD*) printf '%-10s %6s GB  mod=%s unt=%s unpushed=%s merged=%s  %s  %s\n' "$cls" "$total" "$mod" "$unt" "$unp" "$merged" "$branch" "$path" >> "$I" ;;
  esac
done < "$TSV"
epilogue >> "$A"; epilogue >> "$B"
echo 'echo "ACT C complete: every listed worktree now has its commits on origin or in a verified bundle."' >> "$C"
chmod +x "$A" "$B" "$C"

free_now=$(df -k "$HOME" 2>/dev/null | awk 'NR==2{printf "%.1f", $4/1048576}')
{
  echo "WORKTREE RECLAIM PLAN — proposal only, generated $(date -u +%FT%TZ) from $TSV"
  echo "internal free now: ${free_now:-?} GB"
  echo
  printf 'ACT A  regen delete in %d clean pushed internal worktrees   ~%.1f GB   %s\n' "$a_n" "$a_gb" "$A"
  printf 'ACT B  worktree remove, %d REMOVABLE internal worktrees      ~%.1f GB   %s\n' "$b_n" "$b_gb" "$B"
  printf 'ACT C  push or bundle %d worktrees with unpushed commits     0 GB freed  %s\n' "$c_n" "$C"
  printf 'INSPECT/HOLD rows for a person (no commands):                %s\n' "$I"
  echo
  awk -v a="$a_gb" -v b="$b_gb" -v f="${free_now:-0}" 'BEGIN{printf "projected internal free after A then B: ~%.1f GB (A and B overlap on REMOVABLE regen; B removes it either way)\n", f+a+b}'
  echo
  echo "Order: C first (nothing is lost if C never runs, but it must precede any removal of a PRESERVE row),"
  echo "       then A (lossless everywhere: npm ci / next build regenerates), then B (merged worktrees only)."
  echo "Each act script refuses without RECLAIM_AUTHORIZED=1, re-checks cleanliness per worktree, stops on drift."
  echo "Nothing in this generator modified the filesystem."
} | tee "$P"
