import { ganeshaEmail } from '@/lib/services/emailService';

export async function GET() {
  try {
    // Get the template directly from the email service
    const preview = await ganeshaEmail.previewCampaign('consciousness-revolution', 'beta-testers');

    if (!preview.template) {
      return new Response('Template not found', { status: 404 });
    }

    // Return the HTML template as a web page
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Consciousness Revolution Email - Full Template</title>
  <style>
    body {
      margin: 0;
      padding: 20px;
      background-color: #f5f5f5;
      font-family: Arial, sans-serif;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background-color: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #2C5530;
    }
    .info {
      background-color: #e8f5e8;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 30px;
      border-left: 4px solid #2C5530;
    }
    .template-content {
      border: 1px solid #ddd;
      border-radius: 8px;
      overflow: hidden;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🧠 GAIA Email Template - Complete View</h1>
      <p><strong>Ganesha Attention Intelligence Assistant</strong></p>
      <p>Consciousness Revolution Announcement</p>
    </div>

    <div class="info">
      <p><strong>📊 Campaign Stats:</strong></p>
      <ul>
        <li>Recipients: ${preview.recipientCount} consciousness pioneers</li>
        <li>Template: Consciousness Revolution</li>
        <li>Status: Ready to send</li>
        <li>Format: Email-optimized HTML</li>
      </ul>
    </div>

    <div class="template-content">
      ${preview.template.htmlContent}
    </div>

    <div style="margin-top: 30px; text-align: center; color: #666; font-size: 14px;">
      <p>This is the complete email template that will be sent to consciousness pioneers.</p>
      <p>Generated by GAIA Email Service • ${new Date().toLocaleString()}</p>
    </div>
  </div>
</body>
</html>
    `.trim();

    return new Response(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/html',
      },
    });

  } catch (error) {
    console.error('Template view error:', error);
    return Response.json({
      success: false,
      error: 'Failed to load template view'
    }, { status: 500 });
  }
}