import type { ArrivalFacts, ArrivalMachine, ResumeState, State } from './contract';
export interface LawResult { readonly id: string; readonly ok: boolean; readonly detail: string; }
const law = (id: string, ok: boolean, detail: string): LawResult => ({ id, ok, detail });
const W = 'work-river'; const M = 'm-kelly';
const RESUME: ResumeState = { memberId: M, workId: W, mode: 'write', sectionId: 'ds-6', updatedAt: 't1' };
const F = (over: Partial<ArrivalFacts> = {}): ArrivalFacts => ({ workId: W, title: 'The River Between', isNew: false, imported: null, routeSectionId: 'ds-6', hasReading: true, readingStale: false, resume: null, admitted: [], memberDeclaredPurpose: null, workLine: null, reviewHasMaterial: false, ...over });
const arrive = (m: ArrivalMachine, f: ArrivalFacts) => m.arrive(m.selectWork(f.workId, 'route'), f);
const out = (s: State) => ('output' in s ? s.output : null);
const CLASSES: Partial<ArrivalFacts>[] = [{ isNew: true }, {}, { resume: RESUME }, { imported: { detectedChapters: 9, unnamedSections: 2, memberConfirmed: false } }, { hasReading: false }, { readingStale: true }];

export function runArrivalMachineLaws(make: () => ArrivalMachine): readonly LawResult[] {
  const o: LawResult[] = []; const run = (id: string, f: () => LawResult) => { try { o.push(f()); } catch (e) { o.push(law(id, false, `threw: ${(e as Error).message}`)); } };
  run('F8-O1-work-before-explanation', () => { const s = arrive(make(), F()); const r = out(s)?.regions ?? []; const iw = r.indexOf('work'); const ix = r.findIndex((x) => x === 'explanation' || x === 'tour' || x === 'dashboard'); return law('F8-O1-work-before-explanation', iw === 0 && (ix === -1 || iw < ix), `regions: ${r.join(' → ')}`); });
  run('F8-O2-place-clear-when-route-provides', () => { const s = arrive(make(), F()); return law('F8-O2-place-clear-when-route-provides', out(s)?.place === 'ds-6', `place ${out(s)?.place}`); });
  run('F8-O3-three-modes-only', () => { const bad = CLASSES.map((c) => out(arrive(make(), F(c)))?.modes ?? []).filter((m) => m.join() !== 'write,develop,review'); return law('F8-O3-three-modes-only', bad.length === 0, bad.length ? `modes: ${bad.map((m) => m.join('·')).join(' | ')}` : 'Write · Develop · Review in every class'); });
  run('F8-O4-no-false-home', () => { const hits = CLASSES.flatMap((c) => { const x = out(arrive(make(), F(c))); return [...(x?.modes ?? []), ...(x?.actions ?? [])].filter((a) => /^home$/i.test(a)); }); return law('F8-O4-no-false-home', hits.length === 0, hits.length ? `Home offered ${hits.length}x` : 'no Home destination'); });
  run('F8-O5-keep-writing-enters-write-at-place', () => { const m = make(); const s = arrive(m, F()); const w = m.keepWriting(s, F()); const kw = (out(s)?.actions ?? []).some((a) => /keep writing/i.test(a)); return law('F8-O5-keep-writing-enters-write-at-place', kw && w.name === 'WRITE' && 'sectionId' in w && w.sectionId === 'ds-6' && m.commissions() === 0, `${w.name} @ ${'sectionId' in w ? w.sectionId : '?'} · offered ${kw} · commissions ${m.commissions()}`); });
  run('F8-O6-no-expertise-test', () => { const bad = CLASSES.filter((c) => out(arrive(make(), F(c)))?.asksSkillLevel); return law('F8-O6-no-expertise-test', bad.length === 0, `${bad.length} class(es) ask for a level`); });
  run('F8-O7-no-tutorial-required', () => { const bad = CLASSES.filter((c) => out(arrive(make(), F(c)))?.tutorialRequired); return law('F8-O7-no-tutorial-required', bad.length === 0, `${bad.length} class(es) require a tour`); });
  run('F8-O8-recognition-uses-lawful-sources', () => {
    const a = out(arrive(make(), F({ memberDeclaredPurpose: 'a book about staying' })))?.recognition; const b = out(arrive(make(), F({ workLine: { text: 'The river had always moved', sectionId: 'ds-1', reason: 'the opening line' } })))?.recognition; const c = out(arrive(make(), F()))?.recognition;
    const ok = a?.source === 'member-declared' && b?.source === 'work-line' && c?.source === 'work-fact' && ![a, b, c].some((r) => /about (grief|belonging|transformation)/i.test(r?.text ?? '') && r?.source !== 'member-declared');
    return law('F8-O8-recognition-uses-lawful-sources', ok, `${a?.source} · ${b?.source} · ${c?.source}`); });
  run('F8-O9-arrival-commissions-nothing', () => { const m = make(); for (const c of CLASSES) arrive(m, F(c)); return law('F8-O9-arrival-commissions-nothing', m.commissions() === 0, `${m.commissions()} act(s) across six arrivals`); });
  run('F8-O10-returning-copy-needs-durable-fact', () => { const ex = out(arrive(make(), F()))?.copy.join(' ') ?? ''; const re = out(arrive(make(), F({ resume: RESUME })))?.copy.join(' ') ?? ''; const ok = !/last worked/i.test(ex) && /last worked in ds-6/i.test(re) && !/working on (voice|structure)|stuck|struggling/i.test(re); return law('F8-O10-returning-copy-needs-durable-fact', ok, `existing: "${ex.slice(0, 40)}" · returning: "${re.slice(0, 60)}"`); });
  run('F8-O11-cold-start-never-guesses', () => { const m = make(); m.writeResume(RESUME); const s = m.coldStart(RESUME); return law('F8-O11-cold-start-never-guesses', s.name === 'NO_WORK_SELECTED', `${s.name}`); });
  run('F8-O12-import-honesty', () => { const c = out(arrive(make(), F({ imported: { detectedChapters: 9, unnamedSections: 2, memberConfirmed: false } })))?.copy.join(' ') ?? ''; const ok = /identified 9 chapters/i.test(c) && !/you named|you chose/i.test(c); return law('F8-O12-import-honesty', ok, `"${c.slice(0, 70)}"`); });
  run('F8-O13-unread-is-inhabitable', () => { const x = out(arrive(make(), F({ hasReading: false }))); const ok = !!x && x.actions.some((a) => /keep writing/i.test(a)) && !x.copy.some((t) => /error|cannot|unable/i.test(t)) && x.regions.includes('manuscript'); return law('F8-O13-unread-is-inhabitable', ok, ok ? 'no reading, still a room' : `actions ${x?.actions.join(' · ')}`); });
  run('F8-O14-stale-disclosed-not-refreshed', () => { const m = make(); const x = out(arrive(m, F({ readingStale: true }))); const ok = !!x && x.copy.some((t) => /changed since MAIA last read/i.test(t)) && x.actions.some((a) => /read this chapter again/i.test(a)) && x.actions.some((a) => /not now/i.test(a)) && m.commissions() === 0; return law('F8-O14-stale-disclosed-not-refreshed', ok, `commissions ${m.commissions()}`); });
  run('F8-O15-discovery-only-from-admitted', () => { const none = out(arrive(make(), F()))?.discovery; const some = out(arrive(make(), F({ admitted: [{ observationId: 'dobs_1', text: 'The river appears three times here.', sectionId: 'ds-6' }] })))?.discovery; const ok = none === null && !!some && some.observationId === 'dobs_1' && some.provenance === 'maia-observation'; return law('F8-O15-discovery-only-from-admitted', ok, `no evidence → ${none === null ? 'none' : 'INVENTED'} · evidence → ${some?.observationId}`); });
  run('F8-O16-resume-is-one-row-and-review-cta-is-honest', () => { const m = make(); m.writeResume(RESUME); m.writeResume({ ...RESUME, sectionId: 'ds-7', updatedAt: 't2' }); const rows = m.resumeRows(M, W); const noMat = out(arrive(make(), F({ reviewHasMaterial: false })))?.actions ?? []; const cta = noMat.filter((a) => /noticed/i.test(a)); return law('F8-O16-resume-is-one-row-and-review-cta-is-honest', rows === 1 && cta.length === 0, `resume rows ${rows} · dead Review CTA ${cta.length}`); });
  return o;
}
