/**
 * Individual Aspect Detail Page (Server Component)
 *
 * Shows archetypal synthesis + Spiralogic interpretation for a specific aspect
 * URL pattern: /astrology/aspects/sun-square-saturn
 */

import AspectDetailClient from './AspectDetailClient';

// Generate static params for all available aspect interpretations
// URL format: planet1-aspectType-planet2 (e.g., sun-square-saturn)
export async function generateStaticParams() {
  // Define all aspects we have interpretations for
  // Format: planet1-aspectType-planet2 (matches link generation in /astrology page)
  const aspectSlugs = [
    // Sun aspects
    'sun-conjunction-moon',
    'sun-opposition-moon',
    'sun-trine-moon',
    'sun-square-moon',
    'sun-sextile-moon',
    'sun-conjunction-mercury',
    'sun-opposition-mercury',
    'sun-trine-mercury',
    'sun-square-mercury',
    'sun-sextile-mercury',
    'sun-conjunction-venus',
    'sun-opposition-venus',
    'sun-trine-venus',
    'sun-square-venus',
    'sun-sextile-venus',
    'sun-conjunction-mars',
    'sun-square-mars',
    'sun-trine-mars',
    'sun-opposition-mars',
    'sun-sextile-mars',
    'sun-trine-jupiter',
    'sun-square-jupiter',
    'sun-conjunction-jupiter',
    'sun-opposition-jupiter',
    'sun-sextile-jupiter',
    'sun-square-saturn',
    'sun-conjunction-saturn',
    'sun-opposition-saturn',
    'sun-trine-saturn',
    'sun-sextile-saturn',
    'sun-conjunction-uranus',
    'sun-square-uranus',
    'sun-trine-uranus',
    'sun-opposition-uranus',
    'sun-square-neptune',
    'sun-trine-neptune',
    'sun-conjunction-neptune',
    'sun-opposition-neptune',
    'sun-square-pluto',
    'sun-conjunction-pluto',
    'sun-trine-pluto',
    'sun-opposition-pluto',
    'sun-conjunction-chiron',
    'sun-square-chiron',
    'sun-trine-chiron',
    'sun-conjunction-northnode',
    'sun-conjunction-southnode',
    'sun-conjunction-lilith',
    'sun-conjunction-ceres',
    'sun-conjunction-pallas',
    'sun-conjunction-juno',
    'sun-conjunction-vesta',
    // Moon aspects
    'moon-conjunction-mercury',
    'moon-opposition-mercury',
    'moon-trine-mercury',
    'moon-square-mercury',
    'moon-sextile-mercury',
    'moon-conjunction-venus',
    'moon-opposition-venus',
    'moon-trine-venus',
    'moon-square-venus',
    'moon-sextile-venus',
    'moon-conjunction-mars',
    'moon-opposition-mars',
    'moon-trine-mars',
    'moon-square-mars',
    'moon-sextile-mars',
    'moon-trine-jupiter',
    'moon-square-jupiter',
    'moon-conjunction-jupiter',
    'moon-opposition-jupiter',
    'moon-square-saturn',
    'moon-conjunction-saturn',
    'moon-trine-saturn',
    'moon-opposition-saturn',
    'moon-sextile-saturn',
    'moon-conjunction-uranus',
    'moon-square-uranus',
    'moon-trine-uranus',
    'moon-opposition-uranus',
    'moon-square-neptune',
    'moon-conjunction-neptune',
    'moon-trine-neptune',
    'moon-conjunction-pluto',
    'moon-square-pluto',
    'moon-trine-pluto',
    'moon-opposition-pluto',
    'moon-conjunction-chiron',
    'moon-square-chiron',
    'moon-conjunction-northnode',
    'moon-conjunction-lilith',
    // Mercury aspects
    'mercury-conjunction-venus',
    'mercury-opposition-venus',
    'mercury-trine-venus',
    'mercury-square-venus',
    'mercury-sextile-venus',
    'mercury-conjunction-mars',
    'mercury-opposition-mars',
    'mercury-trine-mars',
    'mercury-square-mars',
    'mercury-sextile-mars',
    'mercury-conjunction-saturn',
    'mercury-square-saturn',
    'mercury-trine-saturn',
    'mercury-opposition-saturn',
    'mercury-conjunction-uranus',
    'mercury-square-uranus',
    'mercury-trine-uranus',
    'mercury-square-neptune',
    'mercury-trine-neptune',
    'mercury-conjunction-neptune',
    'mercury-square-pluto',
    'mercury-trine-pluto',
    'mercury-conjunction-pluto',
    'mercury-conjunction-northnode',
    // Venus aspects
    'venus-square-saturn',
    'venus-conjunction-saturn',
    'venus-trine-saturn',
    'venus-opposition-saturn',
    'venus-conjunction-uranus',
    'venus-square-uranus',
    'venus-trine-uranus',
    'venus-opposition-uranus',
    'venus-conjunction-neptune',
    'venus-square-neptune',
    'venus-trine-neptune',
    'venus-opposition-neptune',
    'venus-conjunction-pluto',
    'venus-square-pluto',
    'venus-trine-pluto',
    'venus-opposition-pluto',
    'venus-conjunction-chiron',
    'venus-conjunction-northnode',
    'venus-conjunction-lilith',
    'venus-conjunction-mars',
    'venus-opposition-mars',
    'venus-trine-mars',
    'venus-square-mars',
    'venus-sextile-mars',
    // Mars aspects
    'mars-square-saturn',
    'mars-conjunction-saturn',
    'mars-trine-saturn',
    'mars-opposition-saturn',
    'mars-sextile-saturn',
    'mars-conjunction-uranus',
    'mars-square-uranus',
    'mars-trine-uranus',
    'mars-opposition-uranus',
    'mars-square-neptune',
    'mars-trine-neptune',
    'mars-conjunction-neptune',
    'mars-conjunction-pluto',
    'mars-square-pluto',
    'mars-trine-pluto',
    'mars-opposition-pluto',
    'mars-conjunction-chiron',
    'mars-conjunction-northnode',
    // Jupiter aspects
    'jupiter-conjunction-saturn',
    'jupiter-square-saturn',
    'jupiter-trine-saturn',
    'jupiter-opposition-saturn',
    'jupiter-conjunction-uranus',
    'jupiter-trine-uranus',
    'jupiter-square-uranus',
    'jupiter-conjunction-neptune',
    'jupiter-trine-neptune',
    'jupiter-square-neptune',
    'jupiter-conjunction-pluto',
    'jupiter-trine-pluto',
    'jupiter-square-pluto',
    'jupiter-opposition-pluto',
    'jupiter-conjunction-northnode',
    // Outer planet aspects
    'saturn-square-uranus',
    'saturn-trine-uranus',
    'saturn-conjunction-uranus',
    'saturn-opposition-uranus',
    'saturn-square-neptune',
    'saturn-trine-neptune',
    'saturn-conjunction-neptune',
    'saturn-opposition-neptune',
    'saturn-conjunction-pluto',
    'saturn-trine-pluto',
    'saturn-square-pluto',
    'saturn-opposition-pluto',
    'saturn-conjunction-chiron',
    'saturn-square-chiron',
    'saturn-conjunction-northnode',
    'uranus-conjunction-neptune',
    'uranus-conjunction-pluto',
    'uranus-trine-pluto',
    'uranus-square-pluto',
    'neptune-conjunction-pluto',
    'neptune-trine-pluto',
    // Chiron aspects
    'chiron-conjunction-pluto',
    'chiron-conjunction-uranus',
    'chiron-conjunction-neptune',
    'chiron-conjunction-saturn',
    'chiron-square-saturn',
  ];

  return aspectSlugs.map((slug) => ({
    slug,
  }));
}

export default function AspectDetailPage() {
  return <AspectDetailClient />;
}