import { CONSEQUENCE_FORBIDDEN_FIELDS, CONSEQUENCE_FINDING_FIELDS, CONSEQUENCE_PROJECTION_FIELDS, CONSEQUENCE_SOURCE, CONSEQUENCE_SOURCE_PREFIX, O1_CANDIDATE_STANDING, PROPOSAL_SOURCE_PREFIX } from './contract.mjs';
import { deliverLaneProjection, makeEnvelope, makeLaneWorld, makeProgramme, protectedView, stable } from './substrate.mjs';

const safe=(id,fn)=>{try{return fn()}catch(e){return [`${id}: threw ${e?.message||e}`]}};
const proposal=()=>({kind:'proposal',source_act:'wu-r4',summary:'inspect adjacent resolver',proposed_kind:'INSPECT'});
const ordinaryFinding=()=>({kind:'finding',source_act:'wu-r4',summary:'unexpected sibling state',urgency:'high'});
const consequence=()=>({kind:'finding',source_act:'wu-r4',affected_lane:'lane-b',reason:'identity resolution differs',evidence_refs:['w4:a1'],urgency:'normal'});

export const FALSIFIERS=Object.freeze([
  {id:'R4-E1',law:'finding/proposal append changes only its W4 evidence array',run:(d)=>safe('R4-E1',()=>{const f=[];for(const e of [proposal(),ordinaryFinding(),consequence()]){const env=makeEnvelope();const before=protectedView(env);const r=d.appendEvidence(env,e);if(!r?.ok)f.push(`${e.kind}: refused`);else if(protectedView(r.envelope)!==before)f.push(`${e.kind}: protected surface changed`);}return f;})},
  {id:'R4-E2',law:'schemas are closed; consequence findings carry no executable/write authority',run:(d)=>safe('R4-E2',()=>{const f=[];for(const k of CONSEQUENCE_FORBIDDEN_FIELDS){const r=d.appendEvidence(makeEnvelope(),{...consequence(),[k]:'x'});if(r?.ok)f.push(`${k}: admitted`);}const extra=d.appendEvidence(makeEnvelope(),{...consequence(),target_file:'lane-b/x.ts'});if(extra?.ok)f.push('unlisted field admitted');const ok=d.appendEvidence(makeEnvelope(),consequence());if(!ok?.ok)f.push('lawful consequence refused');else{const rec=ok.envelope.work_unit.evaluation.findings[0];for(const k of Object.keys(rec).filter(k=>k!=='_evidence_identity'))if(!CONSEQUENCE_FINDING_FIELDS.includes(k))f.push(`record carries ${k}`);}return f;})},
  {id:'R4-E3',law:'canonical evidence identity makes duplicate append explicit and immutable',run:(d)=>safe('R4-E3',()=>{const f=[];const env=makeEnvelope(),e=proposal();const a=d.appendEvidence(env,e);if(!a?.ok)return ['first append refused'];const b=d.appendEvidence(a.envelope,e);if(b?.ok)f.push('duplicate accepted');if(b?.reason!=='DUPLICATE_EVIDENCE_RECORD')f.push(`duplicate reason ${b?.reason}`);const changed=d.appendEvidence(a.envelope,{...e,summary:'different'});if(!changed?.ok)f.push('different evidence collapsed into duplicate');return f;})},
  {id:'R4-E4',law:'W4 append does not mutate O1/O2/O3; proposal projection is separate',run:(d)=>safe('R4-E4',()=>{const f=[];const p=makeProgramme();const before=stable(p);const r=d.appendEvidence(makeEnvelope(),proposal(),p);if(stable(p)!==before)f.push('programme mutated by append');if(r?.programme && stable(r.programme)!==before)f.push('append returned mutated programme');return f;})},
  {id:'R4-E5',law:'proposal projects only as one O1 CANDIDATE with stable source_ref and no grants',run:(d)=>safe('R4-E5',()=>{const f=[];const c=d.projectProposal(proposal());if(!c)return ['no candidate'];if(c.standing!==O1_CANDIDATE_STANDING)f.push(`standing ${c.standing}`);if(!String(c.source_ref||'').startsWith(PROPOSAL_SOURCE_PREFIX))f.push('no stable source_ref');if(!Array.isArray(c.authority_grants)||c.authority_grants.length)f.push('candidate carries grants');return f;})},
  {id:'R4-E6',law:'finding never projects to O1, O2 or O3',run:(d)=>safe('R4-E6',()=>{const f=[];for(const e of [ordinaryFinding(),consequence()])if(d.projectProposal(e)!=null)f.push('finding projected as candidate');return f;})},
  {id:'R4-E7',law:'re-reading one proposal is idempotent by evidence source_ref, not summary text',run:(d)=>safe('R4-E7',()=>{const f=[];const e=proposal();const cs=d.projectProposalSet([e,e,{...e}]);if(!Array.isArray(cs)||cs.length!==1)f.push(`candidate count ${cs?.length}`);const other={...e,source_act:'wu-other'};const ds=d.projectProposalSet([e,other]);if(ds.length!==2)f.push('distinct evidence collapsed by summary');return f;})},
  {id:'R4-E8',law:'historical W4 v1 has no live non-test runtime caller',run:(d)=>safe('R4-E8',()=>{const live=d.v1RuntimeCallers();return live.length?live.map(x=>'live v1 caller: '+x):[];})},
  {id:'R4-E9',law:'a lawful consequence finding projects as evidence to exactly its affected lane and nowhere else',run:(d)=>safe('R4-E9',()=>{const f=[];const e=consequence();const p=d.projectConsequenceFinding(e);if(!p)return ['no cross-lane projection'];if(p.target_lane!==e.affected_lane)f.push(`target ${p.target_lane} != ${e.affected_lane}`);if(p.source!==CONSEQUENCE_SOURCE)f.push(`source ${p.source}`);if(!String(p.source_ref||'').startsWith(CONSEQUENCE_SOURCE_PREFIX))f.push('no stable finding source_ref');for(const k of Object.keys(p))if(!CONSEQUENCE_PROJECTION_FIELDS.includes(k))f.push(`projection carries ${k}`);if(stable(p.evidence)!==stable(e))f.push('projected evidence changed');const w=makeLaneWorld();deliverLaneProjection(w,p);if(w.lanes['lane-b'].inbox.length!==1)f.push('affected lane did not receive finding');if(w.lanes['lane-a'].inbox.length||w.lanes['lane-c'].inbox.length)f.push('finding broadcast to another lane');if(d.projectConsequenceFinding(ordinaryFinding())!=null)f.push('ordinary finding projected cross-lane');return f;})},
]);
