-- ═══════════════════════════════════════════════════════════════
-- IMPROVEMENT HYPOTHESES TABLE
--
-- Stores automated improvement hypotheses generated by the
-- ImprovementHypothesisGenerator. This is the "self-improvement
-- loop" that closes the gap between observation and action.
--
-- Philosophy: MAIA proposes; Mentors approve; Production is human-signed.
-- MAIA can observe, hypothesize, test - but deployment requires mentor sign-off.
--
-- Created: 2025-12-30
-- ═══════════════════════════════════════════════════════════════

-- Hypothesis types
DO $$ BEGIN
  CREATE TYPE hypothesis_type AS ENUM (
    'prompt_modification',
    'skill_parameter',
    'gating_threshold',
    'response_constraint',
    'new_skill',
    'skill_deprecation'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Hypothesis status lifecycle
-- Lifecycle: proposed → approved → testing → validated/failed → deployed
DO $$ BEGIN
  CREATE TYPE hypothesis_status AS ENUM (
    'proposed',    -- Generated by MAIA, awaiting mentor review
    'approved',    -- Mentor approved, ready for testing
    'testing',     -- Active A/B test in staging
    'validated',   -- Test passed, awaiting production deploy
    'failed',      -- Test failed, needs redesign
    'deployed',    -- In production (human-signed)
    'rejected',    -- Mentor rejected
    'rolled_back'  -- Reverted after production issues
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Add statuses to existing type if upgrading
DO $$ BEGIN
  ALTER TYPE hypothesis_status ADD VALUE IF NOT EXISTS 'approved' BEFORE 'testing';
  ALTER TYPE hypothesis_status ADD VALUE IF NOT EXISTS 'failed' AFTER 'validated';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Priority levels
DO $$ BEGIN
  CREATE TYPE hypothesis_priority AS ENUM (
    'critical',
    'high',
    'medium',
    'low'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Main hypotheses table
CREATE TABLE IF NOT EXISTS improvement_hypotheses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Classification
  type hypothesis_type NOT NULL,
  priority hypothesis_priority NOT NULL DEFAULT 'medium',
  status hypothesis_status NOT NULL DEFAULT 'proposed',

  -- What triggered this hypothesis
  trigger JSONB NOT NULL,

  -- The specific modification proposed
  modification JSONB NOT NULL,

  -- Expected outcome
  expected_outcome JSONB NOT NULL,

  -- Test configuration (optional)
  test_config JSONB,

  -- Test results (populated after testing)
  results JSONB,

  -- Lifecycle timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tested_at TIMESTAMPTZ,
  deployed_at TIMESTAMPTZ,
  rolled_back_at TIMESTAMPTZ,

  -- Audit trail
  created_by TEXT DEFAULT 'hypothesis_generator',
  deployed_by TEXT,  -- MUST be mentor-signed for production

  -- Link to applied changes (for rollback capability)
  applied_commit_hash TEXT,
  rollback_commit_hash TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_hypotheses_status ON improvement_hypotheses(status);
CREATE INDEX IF NOT EXISTS idx_hypotheses_priority ON improvement_hypotheses(priority);
CREATE INDEX IF NOT EXISTS idx_hypotheses_type ON improvement_hypotheses(type);
CREATE INDEX IF NOT EXISTS idx_hypotheses_created_at ON improvement_hypotheses(created_at DESC);

-- Hypothesis test runs (for A/B testing tracking)
CREATE TABLE IF NOT EXISTS hypothesis_test_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hypothesis_id UUID NOT NULL REFERENCES improvement_hypotheses(id),

  test_group TEXT NOT NULL,
  percentage DECIMAL(5,2) NOT NULL,

  sample_size INTEGER NOT NULL DEFAULT 0,
  metric_sum DECIMAL(10,4) NOT NULL DEFAULT 0,
  metric_count INTEGER NOT NULL DEFAULT 0,

  metrics JSONB NOT NULL DEFAULT '{}',

  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,

  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_test_runs_hypothesis ON hypothesis_test_runs(hypothesis_id);

-- Function to update test run metrics
CREATE OR REPLACE FUNCTION update_hypothesis_test_metric(
  p_hypothesis_id UUID,
  p_test_group TEXT,
  p_metric_value DECIMAL
) RETURNS VOID AS $$
BEGIN
  UPDATE hypothesis_test_runs
  SET
    sample_size = sample_size + 1,
    metric_sum = metric_sum + p_metric_value,
    metric_count = metric_count + 1
  WHERE hypothesis_id = p_hypothesis_id
    AND test_group = p_test_group
    AND is_active = TRUE;
END;
$$ LANGUAGE plpgsql;

-- View for hypothesis overview
CREATE OR REPLACE VIEW hypothesis_overview AS
SELECT
  h.id,
  h.type,
  h.priority,
  h.status,
  h.trigger->>'patternDescription' as pattern,
  h.modification->>'rationale' as rationale,
  h.expected_outcome->>'metric' as target_metric,
  (h.expected_outcome->>'targetImprovement')::DECIMAL as target_improvement,
  h.results->>'verdict' as test_verdict,
  (h.results->>'improvement')::DECIMAL as actual_improvement,
  h.created_at,
  h.tested_at,
  h.deployed_at,
  h.deployed_by
FROM improvement_hypotheses h
ORDER BY
  CASE h.status
    WHEN 'proposed' THEN 1
    WHEN 'testing' THEN 2
    WHEN 'validated' THEN 3
    WHEN 'deployed' THEN 4
    ELSE 5
  END,
  CASE h.priority
    WHEN 'critical' THEN 1
    WHEN 'high' THEN 2
    WHEN 'medium' THEN 3
    ELSE 4
  END,
  h.created_at DESC;

COMMENT ON TABLE improvement_hypotheses IS
  'Self-improvement loop: MAIA proposes, Mentors approve, Production is human-signed.';
