-- ─────────────────────────────────────────────────────────────────────────────
-- Field invitations — the bridge between practitioner work and member sovereignty
--
-- This migration exists to close a false affordance. `field_program_positions
-- .stated_by` has carried 'practitioner_seeded' since 20260712000001, the UI
-- described it to members, and NO WRITER EVER EXISTED. CF-D2 ruled that a
-- visible promise with no authority chain must not stand.
--
-- The rule this schema enforces, structurally rather than by convention
-- (CF-D5c, ratified 2026-08-03):
--
--     Attribution follows AUTHORSHIP. Meaning ownership follows the MEMBER.
--     No authored object may lose its source.
--     No member meaning may acquire a source it did not choose.
--
-- Hence TWO tables and deliberately NO third:
--
--   field_invitations           practitioner-authored. Attribution is PERMANENT
--                               and survives the relationship ending, because
--                               the practitioner wrote it. Rendering it without
--                               a source is not neutrality — it is absorption.
--
--   field_invitation_responses  the member's gesture, and ONLY the gesture.
--                               accepted | declined. No content, no reflection,
--                               no meaning.
--
-- ⛔ There is deliberately no `invitation_id` on member_field_note_threads, and
--    none may be added. An insight a member writes after receiving an invitation
--    is THEIRS. Stamping the practitioner's object onto the member's row would
--    convert facilitation into ownership — "Larry's Leadership Insight" — which
--    is the precise failure CF-D5c forbids. The practitioner may have created
--    the conditions; the member created the meaning.
--
--    Larry sees which invitations were accepted (his rows). He sees member
--    material only where the member set can_be_shown_to_practitioner. The two
--    are never joined.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Practitioner-authored: the invitation ──
CREATE TABLE IF NOT EXISTS field_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  field_slug VARCHAR(64) NOT NULL,              -- joins practice_fields.field_slug
  program_slug VARCHAR(64) NOT NULL DEFAULT 'general',

  -- WHO AUTHORED THIS. Persistent, never nulled, never anonymised. This column
  -- is the reason the invitation may be rendered at all.
  authored_by_practitioner_id UUID NOT NULL REFERENCES members(id),

  -- The practitioner's words, verbatim. Never paraphrased, never summarised,
  -- never regenerated. If it is shown, it is shown as written.
  body TEXT NOT NULL CHECK (length(trim(body)) > 0),

  -- Addressed to one member, or NULL for anyone standing in the program.
  -- An invitation to a specific member is still an OFFER, never an assignment.
  addressed_to_member_id UUID REFERENCES members(id),

  -- Withdrawal is the practitioner's own gesture over their own object.
  -- Soft, because withdrawing an offer must not erase that a member already
  -- responded to it — that response is the member's act, not the practitioner's.
  withdrawn_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE field_invitations IS
  'Practitioner-authored offers. Attribution is permanent and survives the relationship ending (CF-D5c): rendering an authored practice with no source is absorption, not neutrality. An invitation is never an assignment and carries no completion state.';
COMMENT ON COLUMN field_invitations.authored_by_practitioner_id IS
  'Who authored this. Persistent. The invitation may not be rendered without resolving it.';
COMMENT ON COLUMN field_invitations.body IS
  'The practitioner''s words, verbatim. Never paraphrased or regenerated by the system.';
COMMENT ON COLUMN field_invitations.withdrawn_at IS
  'Practitioner withdrew the offer. Soft — an existing member response is the member''s act and is not erased by it.';

CREATE INDEX IF NOT EXISTS idx_field_invitations_field_program
  ON field_invitations(field_slug, program_slug) WHERE withdrawn_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_field_invitations_addressed
  ON field_invitations(addressed_to_member_id) WHERE addressed_to_member_id IS NOT NULL;

-- ── Member-authored: the gesture, and nothing else ──
CREATE TABLE IF NOT EXISTS field_invitation_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invitation_id UUID NOT NULL REFERENCES field_invitations(id) ON DELETE CASCADE,
  member_id UUID NOT NULL REFERENCES members(id),

  -- The member's register. 'accepted' means "I want to work with this."
  -- ⛔ There is no 'completed'. There is no 'in_progress'. A completion state
  --    would recreate the LMS workflow the sovereignty model refuses (CF-D2a),
  --    and would make the practitioner the auditor of the member's living.
  response TEXT NOT NULL CHECK (response IN ('accepted', 'declined')),

  responded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One standing answer per member per invitation; a member may change it.
  UNIQUE (invitation_id, member_id)
);

COMMENT ON TABLE field_invitation_responses IS
  'The member''s gesture toward an invitation — accepted or declined, nothing more. Deliberately carries NO content: meaning the member makes afterward belongs to them and lives in member_field_note_threads with no link back to the invitation (CF-D5c).';
COMMENT ON COLUMN field_invitation_responses.response IS
  'accepted = "I want to work with this" · declined. There is deliberately no completion state — an invitation is not an assignment.';

CREATE INDEX IF NOT EXISTS idx_field_invitation_responses_member
  ON field_invitation_responses(member_id, responded_at DESC);
