-- System Directives: surface actionable recommendations to administrators
-- Generated by deterministic rule evaluation against the research ledger.
-- No autonomy — directives require human acknowledgment before resolution.
--
-- Identity: one open directive per (directive_key, observation_period_start).
-- condition_cleared_at records when the triggering condition stopped firing
-- independently of resolved_at (human acknowledgment). Both are meaningful.

CREATE TABLE IF NOT EXISTS system_directives (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  directive_key           TEXT NOT NULL,
  signal_type             TEXT NOT NULL,
  observation_period_start TIMESTAMPTZ NOT NULL,  -- which ledger period triggered this
  title                   TEXT NOT NULL,
  summary                 TEXT NOT NULL,
  evidence_payload        JSONB NOT NULL DEFAULT '{}',
  recommendation          TEXT NOT NULL,
  priority                TEXT NOT NULL CHECK (priority IN ('high','medium','low')),
  status                  TEXT NOT NULL DEFAULT 'open'
                          CHECK (status IN ('open','acknowledged','resolved','dismissed')),
  opened_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  condition_cleared_at    TIMESTAMPTZ,   -- condition stopped firing (may precede resolved_at)
  resolved_at             TIMESTAMPTZ,   -- human-acknowledged resolution
  acknowledged_by         TEXT,
  notes                   TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One open/acknowledged directive per rule per observation window
CREATE UNIQUE INDEX IF NOT EXISTS uq_directives_active_per_period
  ON system_directives (directive_key, observation_period_start)
  WHERE status IN ('open', 'acknowledged');

CREATE INDEX IF NOT EXISTS idx_directives_status
  ON system_directives (status, priority, opened_at DESC);

CREATE INDEX IF NOT EXISTS idx_directives_key
  ON system_directives (directive_key, opened_at DESC);

CREATE OR REPLACE FUNCTION update_system_directives_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_system_directives_updated_at
  BEFORE UPDATE ON system_directives
  FOR EACH ROW EXECUTE FUNCTION update_system_directives_updated_at();

INSERT INTO schema_migrations (filename, applied_at)
  VALUES ('20260316000002_system_directives.sql', NOW())
  ON CONFLICT (filename) DO NOTHING;
