-- Client Representation Governance — bring client-keyed memory to member-side parity.
-- Spec:   docs/specs/CLIENT_REPRESENTATION_GOVERNANCE_PATCH_2026-06-25.md
-- Ladder:  docs/architecture/PRACTITIONER_PORTAL_RESPONSIBILITY_LADDER_2026-06-25.md (§3a/4a)
--
-- STEWARD RULING (Kelly, 2026-06-25):
--   • crossing_allowed = FALSE is the ratified default for ALL MAIA-inferred client
--     representations.
--   • The existing prod case_memories rows are RETAINED UNDER GOVERNANCE — not because
--     they are valuable, but because they are EVIDENCE of the crossing: marked
--     maia_inferred / accepted / crossing_allowed=FALSE, withheld from all surfaces,
--     pending a later steward disposition (purge or keep). This avoids both mistakes:
--     normalizing them as usable client memory, and deleting the evidence before the
--     governance has proven it can hold them safely.
--
-- Remediation + prevention. The member side already has this discipline
-- (member_memory_atoms.crossing_allowed=FALSE + provenance); this gives the CLIENT side
-- parity. Governs REPRESENTATION, not action — does NOT authorize the triadic constitution.

-- ── 1. case_memories: first-class provenance, disposition, crossing gate, consent snapshot ──
ALTER TABLE case_memories
  ADD COLUMN IF NOT EXISTS authorship TEXT NOT NULL DEFAULT 'maia_inferred'
    CHECK (authorship IN ('practitioner_authored','maia_inferred','maia_suggested')),
  ADD COLUMN IF NOT EXISTS disposition TEXT NOT NULL DEFAULT 'accepted'
    CHECK (disposition IN ('provisional','accepted','rejected')),
  ADD COLUMN IF NOT EXISTS crossing_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consent_basis TEXT,          -- snapshot of practitioner_cases.privacy_mode at write
  ADD COLUMN IF NOT EXISTS consent_at_write TIMESTAMPTZ, -- snapshot of consent_captured_at at write
  ADD COLUMN IF NOT EXISTS source_route TEXT;

COMMENT ON COLUMN case_memories.authorship IS
  'First-class provenance (replaces reverse-inference from source_* FKs). practitioner_authored = a human note; maia_inferred = generated by the review pipeline; maia_suggested = offered, not asserted.';
COMMENT ON COLUMN case_memories.crossing_allowed IS
  'Member-side parity (member_memory_atoms.crossing_allowed). FALSE = held: a MAIA-inferred client representation may be counted but NOT surfaced/asserted. Ratified default FALSE for maia_inferred (Kelly 2026-06-25).';
COMMENT ON COLUMN case_memories.consent_basis IS
  'Snapshot of practitioner_cases.privacy_mode at write time (durable per-memory consent provenance, not a live lookup).';

-- ── 2. Backfill existing rows: classify provenance from source FKs, hold all, snapshot consent. ──
--   Idempotent: only touches rows not yet stamped (consent_basis IS NULL). Re-running never
--   resets a row that a later governed action set crossing_allowed=TRUE.
--   Ruling: existing rows → crossing_allowed=FALSE (held). All current prod rows are
--   maia_inferred (source_candidate_id set); the CASE keeps the classifier general.
UPDATE case_memories cm SET
  authorship = CASE
      WHEN cm.source_note_id IS NOT NULL
       AND cm.source_candidate_id IS NULL
       AND cm.review_lens_id IS NULL THEN 'practitioner_authored'
      ELSE 'maia_inferred' END,
  disposition = 'accepted',     -- rows already in case_memories were promoted = accepted
  crossing_allowed = FALSE,      -- ratified: hold all existing rows pending steward disposition
  source_route = COALESCE(cm.source_route, 'studio/review/save'),
  consent_basis = pc.privacy_mode,
  consent_at_write = pc.consent_captured_at
FROM practitioner_cases pc
WHERE cm.case_id = pc.id
  AND cm.consent_basis IS NULL;  -- only un-backfilled rows (idempotency guard)

-- ── 3. pending_review_candidates: rejection capture (was silent TTL expiry). ──
ALTER TABLE pending_review_candidates
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- ── 4. Retroactively mark already-expired, never-promoted candidates as rejected. ──
UPDATE pending_review_candidates
  SET rejected_at = expires_at, rejection_reason = 'expired_unreviewed'
  WHERE expires_at < now() AND promoted_at IS NULL AND rejected_at IS NULL;
