-- Clinical Supervision System
-- HIPAA-compliant local supervision with real-time transcription and analysis
-- All processing happens locally (Whisper, Ollama) - no PHI to external APIs

-- Supervision sessions (standalone - no foreign key constraints to allow independent use)
CREATE TABLE IF NOT EXISTS supervision_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  practitioner_id UUID,    -- Optional link to practitioners
  case_id UUID,            -- Optional link to cases
  session_type VARCHAR(30) CHECK (session_type IN (
    'individual', 'group', 'peer', 'consultation', 'team_meeting',
    'reading', 'scribe', 'live_scribe'
  )),
  title TEXT,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  recording_path TEXT,                    -- Local filesystem path
  transcript_path TEXT,                   -- Local filesystem path
  processing_status VARCHAR(20) DEFAULT 'recording' CHECK (processing_status IN (
    'recording', 'processing', 'transcribing', 'analyzing', 'complete', 'error'
  )),
  total_duration_ms INTEGER,
  speaker_count INTEGER,
  metadata JSONB DEFAULT '{}',            -- Platform, participants, etc.
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Timestamped transcript segments with speaker diarization
CREATE TABLE IF NOT EXISTS supervision_transcript_segments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES supervision_sessions(id) ON DELETE CASCADE,
  speaker VARCHAR(50) NOT NULL,           -- 'therapist', 'client', 'supervisor', 'speaker_1', etc.
  speaker_confidence REAL,                -- pyannote confidence 0.0-1.0
  start_ms INTEGER NOT NULL,
  end_ms INTEGER NOT NULL,
  text TEXT NOT NULL,
  transcription_confidence REAL,          -- Whisper confidence 0.0-1.0
  language VARCHAR(10) DEFAULT 'en',
  is_final BOOLEAN DEFAULT TRUE,          -- FALSE for real-time partials
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clinical insights (async generated by local LLM)
CREATE TABLE IF NOT EXISTS supervision_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES supervision_sessions(id) ON DELETE CASCADE,
  insight_type VARCHAR(30) NOT NULL CHECK (insight_type IN (
    'pattern',              -- Recurring themes, defense mechanisms
    'countertransference',  -- Therapist emotional reactions
    'intervention',         -- Intervention quality, timing, attunement
    'stuck_point',          -- Impasses, ruptures
    'rupture',              -- Relationship ruptures detected
    'attunement',           -- Moments of connection
    'transference',         -- Client transference patterns
    'documentation',        -- SOAP notes, session summaries
    'recommendation'        -- Suggested next steps
  )),
  content TEXT NOT NULL,
  segment_refs UUID[],                    -- References to transcript segments
  time_range_start_ms INTEGER,            -- When in session this applies
  time_range_end_ms INTEGER,
  significance NUMERIC(3,2),              -- 0.00-1.00 importance score
  model_used VARCHAR(100),                -- e.g., 'deepseek-r1:latest'
  processing_time_ms INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Async processing queue for supervision jobs
CREATE TABLE IF NOT EXISTS supervision_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES supervision_sessions(id) ON DELETE CASCADE,
  job_type VARCHAR(30) NOT NULL CHECK (job_type IN (
    'transcribe',                  -- Whisper transcription
    'diarize',                     -- Speaker diarization
    'analyze_patterns',            -- Pattern recognition
    'analyze_countertransference', -- Countertransference detection
    'analyze_interventions',       -- Intervention quality
    'detect_ruptures',             -- Rupture/stuck point detection
    'generate_documentation',      -- SOAP notes generation
    'generate_summary'             -- Session summary
  )),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN (
    'pending', 'processing', 'complete', 'error', 'cancelled'
  )),
  priority INTEGER DEFAULT 5,             -- 1=highest, 10=lowest
  input_data JSONB DEFAULT '{}',          -- Job-specific parameters
  output_data JSONB DEFAULT '{}',         -- Results/artifacts
  attempts INTEGER DEFAULT 0,
  max_attempts INTEGER DEFAULT 3,
  last_error TEXT,
  locked_at TIMESTAMPTZ,                  -- For concurrent worker safety
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

-- Real-time audio chunks (temporary, for streaming)
CREATE TABLE IF NOT EXISTS supervision_audio_chunks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES supervision_sessions(id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  start_ms INTEGER NOT NULL,
  end_ms INTEGER NOT NULL,
  audio_path TEXT,                        -- Local path to chunk file
  is_processed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance

-- Sessions by practitioner and status
CREATE INDEX IF NOT EXISTS idx_supervision_sessions_practitioner
  ON supervision_sessions(practitioner_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_supervision_sessions_case
  ON supervision_sessions(case_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_supervision_sessions_active
  ON supervision_sessions(practitioner_id)
  WHERE ended_at IS NULL;

-- Transcript segments by session and time
CREATE INDEX IF NOT EXISTS idx_supervision_segments_session_time
  ON supervision_transcript_segments(session_id, start_ms);

CREATE INDEX IF NOT EXISTS idx_supervision_segments_speaker
  ON supervision_transcript_segments(session_id, speaker);

-- Insights by session and type
CREATE INDEX IF NOT EXISTS idx_supervision_insights_session
  ON supervision_insights(session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_supervision_insights_type
  ON supervision_insights(session_id, insight_type);

-- Jobs queue (for worker polling)
CREATE INDEX IF NOT EXISTS idx_supervision_jobs_pending
  ON supervision_jobs(status, priority, created_at)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_supervision_jobs_session
  ON supervision_jobs(session_id, job_type);

-- Audio chunks for processing
CREATE INDEX IF NOT EXISTS idx_supervision_chunks_unprocessed
  ON supervision_audio_chunks(session_id, chunk_index)
  WHERE is_processed = FALSE;

-- Auto-update timestamp trigger
CREATE OR REPLACE FUNCTION update_supervision_session_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS supervision_sessions_updated_at ON supervision_sessions;
CREATE TRIGGER supervision_sessions_updated_at
  BEFORE UPDATE ON supervision_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_supervision_session_timestamp();

-- Comments for documentation
COMMENT ON TABLE supervision_sessions IS 'Clinical supervision sessions with audio recording and analysis';
COMMENT ON TABLE supervision_transcript_segments IS 'Timestamped transcript with speaker diarization';
COMMENT ON TABLE supervision_insights IS 'AI-generated clinical insights (local LLM only)';
COMMENT ON TABLE supervision_jobs IS 'Async processing queue for transcription and analysis';
COMMENT ON TABLE supervision_audio_chunks IS 'Temporary storage for real-time audio streaming';
