-- Pattern Inquiry Protocol — Phase 1 schema
-- Tracks multi-week behavioral pattern inquiry protocols with observation logging
--
-- Tables:
--   studio_pattern_protocols    — the protocol itself (practitioner-owned, client-linked)
--   protocol_observations       — turn-by-turn observations (maia/manual/practitioner)
--   protocol_council_outputs    — per-week guide council outputs (Phase 1 stub, Phase 2 populated)

-- ============================================================
-- TABLE 1: studio_pattern_protocols
-- ============================================================
CREATE TABLE IF NOT EXISTS studio_pattern_protocols (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  practitioner_id UUID NOT NULL REFERENCES practitioners(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES practitioner_clients(id) ON DELETE CASCADE,
  member_id UUID REFERENCES members(id) ON DELETE SET NULL,

  protocol_type VARCHAR(50) NOT NULL DEFAULT 'pattern_inquiry',
  pattern_name VARCHAR(200) NOT NULL,
  pattern_description TEXT,

  -- Habit loop anatomy
  trigger TEXT,
  behavior TEXT,
  immediate_reward TEXT,
  long_term_cost TEXT,

  status VARCHAR(50) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'paused', 'completed')),
  current_week INTEGER NOT NULL DEFAULT 1
    CHECK (current_week BETWEEN 1 AND 6),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  council_guides JSONB NOT NULL DEFAULT '["strategist","body_listener","pattern_seer","symbolist"]',
  micro_intervention JSONB,
  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One active protocol per connected member (partial unique index)
CREATE UNIQUE INDEX IF NOT EXISTS idx_protocols_one_active_per_member
  ON studio_pattern_protocols(member_id)
  WHERE member_id IS NOT NULL AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_protocols_practitioner ON studio_pattern_protocols(practitioner_id);
CREATE INDEX IF NOT EXISTS idx_protocols_client ON studio_pattern_protocols(client_id);
CREATE INDEX IF NOT EXISTS idx_protocols_member_status ON studio_pattern_protocols(member_id, status);

CREATE OR REPLACE FUNCTION update_studio_pattern_protocols_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_studio_pattern_protocols_updated_at ON studio_pattern_protocols;
CREATE TRIGGER trg_studio_pattern_protocols_updated_at
  BEFORE UPDATE ON studio_pattern_protocols
  FOR EACH ROW EXECUTE FUNCTION update_studio_pattern_protocols_updated_at();

-- ============================================================
-- TABLE 2: protocol_observations
-- ============================================================
-- RAW verbatim snippets (observation_text) are stored uninterpreted.
-- STRUCTURED EXTRACTION fields (somatic_signals, emotional_tone, etc.) are
-- interpreted signal — not raw content.
-- source: 'maia' = auto-logged from MAIA conversation turn
--         'manual' = member/practitioner generic note via UI
--         'practitioner' = explicit intentional practitioner observation

CREATE TABLE IF NOT EXISTS protocol_observations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_id UUID NOT NULL REFERENCES studio_pattern_protocols(id) ON DELETE CASCADE,
  member_id UUID REFERENCES members(id) ON DELETE SET NULL,
  week_number INTEGER NOT NULL
    CHECK (week_number BETWEEN 1 AND 6),

  -- RAW: verbatim snippet from conversation turn, uninterpreted
  observation_text TEXT,

  -- STRUCTURED EXTRACTION: interpreted signal, not raw
  somatic_signals TEXT,
  emotional_tone VARCHAR(100),
  context_description TEXT,
  behavior_occurred BOOLEAN,
  pause_attempted BOOLEAN,

  tags JSONB NOT NULL DEFAULT '[]',

  source VARCHAR(50) NOT NULL DEFAULT 'maia'
    CHECK (source IN ('maia', 'manual', 'practitioner')),
  session_id TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_observations_protocol_week
  ON protocol_observations(protocol_id, week_number);
CREATE INDEX IF NOT EXISTS idx_observations_member
  ON protocol_observations(member_id);
CREATE INDEX IF NOT EXISTS idx_observations_created
  ON protocol_observations(protocol_id, created_at DESC);

-- ============================================================
-- TABLE 3: protocol_council_outputs
-- ============================================================
-- At most one council output per protocol per week.
-- Phase 1: stored but not generated by AI.
-- Phase 2+: AI generates guide outputs; practitioner annotates.
--
-- Guide output JSONB shape (per guide column):
--   {
--     "generated": string,
--     "evidence": string[],
--     "provenance": "generated" | "practitioner" | "edited",
--     "practitioner_note": string,
--     "status": "pending" | "accepted" | "edited" | "discarded"
--   }

CREATE TABLE IF NOT EXISTS protocol_council_outputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_id UUID NOT NULL REFERENCES studio_pattern_protocols(id) ON DELETE CASCADE,
  week_number INTEGER,
  generated_at TIMESTAMPTZ,
  generated_from_observation_count INTEGER DEFAULT 0,

  strategist_output JSONB,
  body_listener_output JSONB,
  pattern_seer_output JSONB,
  symbolist_output JSONB,

  working_hypothesis TEXT,
  intervention_strategy TEXT,
  confidence_level VARCHAR(20) CHECK (confidence_level IN ('low', 'moderate', 'high')),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- At most one council output per protocol per week
CREATE UNIQUE INDEX IF NOT EXISTS idx_council_outputs_protocol_week
  ON protocol_council_outputs(protocol_id, week_number);

CREATE OR REPLACE FUNCTION update_protocol_council_outputs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_protocol_council_outputs_updated_at ON protocol_council_outputs;
CREATE TRIGGER trg_protocol_council_outputs_updated_at
  BEFORE UPDATE ON protocol_council_outputs
  FOR EACH ROW EXECUTE FUNCTION update_protocol_council_outputs_updated_at();
