-- GATHER-02 — the Materials Studio.
--
-- Everything a writer brings in: documents, notes, transcripts, recordings,
-- images, links, earlier drafts. Each stays visibly ITSELF. Nothing is
-- flattened into undifferentiated text, and nothing arrives already belonging
-- to a Work.
--
--     SOURCE      what actually arrived        ← this table
--        ↓
--     MATERIAL    what the writer gathered     ← this table
--        ↓
--     WORK        what the writer is making    ← living_works
--
-- BELONGING IS NOT HERE, ON PURPOSE. living_work_materials already carries the
-- declaration grammar — the member's act, the member's sentence, removable
-- without touching the thing. A material joins a Work as
-- (material_type='studio_material', material_id=<this id>), so gathering and
-- belonging stay two acts, as they already were for manuscripts.
--
-- THE PROVENANCE RULE, STRUCTURAL
--
-- WS-01 established for manuscripts that pasted text may never claim to be an
-- extracted file. Generalised here: a material that claims a file must HAVE
-- the file — ref, hash and size together — and one that was typed may not
-- claim one. An image row with no bytes is the same lie in a different
-- costume. The CHECK below makes the false row unwritable rather than
-- discouraged, so a route that forgets the check still cannot produce it.
--
-- WHAT MAIA MAY DO WITH THESE
--
-- Read them when the writer has declared they belong, and say what she
-- notices. Nothing here records a MAIA judgement about belonging: a material
-- belongs because the writer said so, in their own sentence, or it does not
-- belong. There is deliberately no confidence column and no suggested_work.
--
-- ROLLBACK: DROP TABLE IF EXISTS studio_materials;

CREATE TABLE IF NOT EXISTS studio_materials (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id          UUID NOT NULL REFERENCES members(id) ON DELETE CASCADE,

  kind               TEXT NOT NULL
                       CHECK (kind IN ('document', 'note', 'transcript',
                                       'audio', 'image', 'link')),

  -- The writer's name for it. Seeded from the filename, the link, or the
  -- text's own first line — never generated by MAIA — and editable always.
  title              TEXT NOT NULL CHECK (length(trim(title)) > 0),

  -- ── What arrived ────────────────────────────────────────────────────────
  -- Bytes live in the shared file vault; these three identify and verify them.
  artifact_ref       TEXT,
  artifact_hash      TEXT,
  artifact_size      INTEGER,
  original_filename  TEXT,
  mime_type          TEXT,
  -- A link keeps its address. The page is NOT fetched: fetching on the
  -- writer's behalf would make outbound requests they did not make, from a
  -- self-hosted system whose whole point is that nothing sits in between.
  source_url         TEXT,

  -- ── What was extracted ──────────────────────────────────────────────────
  -- NULL means not read, which is a legitimate state: a recording is kept as
  -- itself and not transcribed here, and an image is not described.
  extracted_text     TEXT,
  extraction_method  TEXT,
  extracted_chars    INTEGER,

  arrived_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- All three, or none. A partial claim is the dangerous one: it looks like
  -- custody in a listing and has nothing behind it.
  CONSTRAINT studio_materials_artifact_whole CHECK (
    (artifact_ref IS NULL AND artifact_hash IS NULL AND artifact_size IS NULL)
    OR
    (artifact_ref IS NOT NULL AND artifact_hash IS NOT NULL
     AND artifact_size IS NOT NULL AND original_filename IS NOT NULL)
  ),

  -- File-backed kinds must have the file; typed kinds may not claim one.
  CONSTRAINT studio_materials_kind_matches_arrival CHECK (
    (kind IN ('document', 'audio', 'image') AND artifact_ref IS NOT NULL)
    OR
    (kind IN ('note', 'transcript', 'link') AND artifact_ref IS NULL)
  ),

  -- Only a link carries an address, and a link must have one.
  CONSTRAINT studio_materials_link_has_address CHECK (
    (kind = 'link' AND source_url IS NOT NULL)
    OR
    (kind <> 'link' AND source_url IS NULL)
  ),

  -- Extraction is described whenever it happened, so "where did this text come
  -- from" is answerable for every material that has any.
  CONSTRAINT studio_materials_extraction_described CHECK (
    (extracted_text IS NULL AND extraction_method IS NULL)
    OR
    (extracted_text IS NOT NULL AND extraction_method IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS studio_materials_member_idx
  ON studio_materials (member_id, arrived_at DESC);

-- Finding a material again by its bytes, and noticing the same file brought
-- in twice. Not unique: a writer may deliberately keep two copies, and the
-- system does not get to decide that for them.
CREATE INDEX IF NOT EXISTS studio_materials_hash_idx
  ON studio_materials (member_id, artifact_hash)
  WHERE artifact_hash IS NOT NULL;
