-- Practice Insights: Generated supervision insights from session transcripts
-- These are world-specific insights generated by MAIA's mentor layer

CREATE TABLE IF NOT EXISTS practice_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES practice_sessions(id) ON DELETE CASCADE,
  world_id UUID NOT NULL REFERENCES practice_worlds(id) ON DELETE CASCADE,
  insight_type VARCHAR(50) NOT NULL,  -- e.g., 'somatic_cue', 'part_identified', 'archetype_active'
  content TEXT NOT NULL,               -- The generated insight text
  segment_refs UUID[] DEFAULT '{}',    -- References to transcript segments that informed this insight
  significance NUMERIC(3,2) DEFAULT 0.5,  -- 0.0-1.0 significance score
  model_used VARCHAR(100),             -- e.g., 'local-model:ollama', 'consciousness-engine:template'
  processing_time_ms INTEGER,          -- How long the generation took
  practitioner_rating INTEGER,         -- Optional: practitioner rates helpfulness (1-5)
  practitioner_notes TEXT,             -- Optional: practitioner adds notes
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_practice_insights_session ON practice_insights(session_id);
CREATE INDEX IF NOT EXISTS idx_practice_insights_world ON practice_insights(world_id);
CREATE INDEX IF NOT EXISTS idx_practice_insights_type ON practice_insights(insight_type);
CREATE INDEX IF NOT EXISTS idx_practice_insights_significance ON practice_insights(significance DESC);

-- Composite index for session + world queries
CREATE INDEX IF NOT EXISTS idx_practice_insights_session_world ON practice_insights(session_id, world_id);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_practice_insights_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS practice_insights_updated_at ON practice_insights;
CREATE TRIGGER practice_insights_updated_at
  BEFORE UPDATE ON practice_insights
  FOR EACH ROW
  EXECUTE FUNCTION update_practice_insights_timestamp();

-- Add helpful comments
COMMENT ON TABLE practice_insights IS 'MAIA-generated supervision insights from session transcripts, organized by world (interpretive lens)';
COMMENT ON COLUMN practice_insights.insight_type IS 'World-specific insight type (e.g., somatic_cue, part_identified, archetype_active)';
COMMENT ON COLUMN practice_insights.segment_refs IS 'UUIDs of transcript segments that informed this insight';
COMMENT ON COLUMN practice_insights.significance IS 'Calculated significance score 0.0-1.0 based on content analysis';
COMMENT ON COLUMN practice_insights.model_used IS 'Model that generated this insight (for sovereignty tracking)';
