import { EVIDENCE_GATE } from './contract.mjs';
import { world,stable,protectedRuntimeView } from './substrate.mjs';
const safe=(id,fn)=>{try{return fn()}catch(e){return [`${id}: threw ${e?.message||e}`]}};
export const FALSIFIERS=Object.freeze([
{id:'R5-F1',law:'runtime identity requires exact binding evidence',run:d=>safe('R5-F1',()=>{const w=world();w.bindings=w.bindings.filter(b=>b.planned_work_unit_id!=='p3');w.runtimes.p3={id:'p3',state:'ROUTED',guard:'valid'};const r=d.readiness(w).find(x=>x.planned_work_unit_id==='p3');return r?.status==='BLOCKED'&&r.gate===EVIDENCE_GATE?[]:['p3 matched without binding'];})},
{id:'R5-F2',law:'planned↔runtime binding is one-to-one',run:d=>safe('R5-F2',()=>{const w=world();w.runtimes.w9={id:'w9',state:'ROUTED',guard:'valid',authority:'A',route:'R9',scope:'S9'};w.bindings.push({...w.bindings[2],canonical_work_unit_id:'w9'});const anyReady=d.readiness(w).some(x=>x.status==='READY');return anyReady?['duplicate binding did not fail closed']:[];})},
{id:'R5-F3',law:'only CLOSED satisfies a dependency',run:d=>safe('R5-F3',()=>{const bad=['ADJUDICATED','RETURNED','STOPPED','SUPERSEDED','EXECUTING','EVIDENCE_READY','ROUTED'];const f=[];for(const s of bad){const w=world();w.runtimes.w1.state=s;const r=d.readiness(w).find(x=>x.planned_work_unit_id==='p3');if(r?.status==='READY')f.push(s+' satisfied dependency');}return f;})},
{id:'R5-F4',law:'all dependencies must be satisfied',run:d=>safe('R5-F4',()=>{const w=world();w.runtimes.w2.state='EXECUTING';const r=d.readiness(w).find(x=>x.planned_work_unit_id==='p3');return r?.status==='READY'?['partial dependency satisfaction admitted']:[];})},
{id:'R5-F5',law:'own runtime must be ROUTED',run:d=>safe('R5-F5',()=>{const f=[];for(const s of ['DRAFT','AUTHORIZED','EXECUTING','EVIDENCE_READY','ADJUDICATED','CLOSED','RETURNED','STOPPED','SUPERSEDED']){const w=world();w.runtimes.w3.state=s;const r=d.readiness(w).find(x=>x.planned_work_unit_id==='p3');if(r?.status==='READY')f.push(s+' selected');}return f;})},
{id:'R5-F6',law:'missing/invalid evidence blocks rather than schedules',run:d=>safe('R5-F6',()=>{const f=[];for(const mutate of [w=>delete w.runtimes.w1,w=>w.runtimes.w1.guard='invalid',w=>w.bindings.splice(0,1)]){const w=world();mutate(w);const r=d.readiness(w).find(x=>x.planned_work_unit_id==='p3');if(r?.status==='READY')f.push('missing evidence scheduled');}return f;})},
{id:'R5-F7',law:'selection never exceeds nonnegative observed capacity',run:d=>safe('R5-F7',()=>{const f=[];for(const [slots,max] of [[0,0],[1,1],[-1,0],[null,0]]){const w=world();w.runtimes.w1.state='ROUTED';w.runtimes.w2.state='ROUTED';w.capacity.available_slots=slots;const got=d.selectReady(w).length;if(got>max)f.push(`${slots} -> ${got}`);}return f;})},
{id:'R5-F8',law:'same inputs select same topological prefix',run:d=>safe('R5-F8',()=>{const w=world();w.runtimes.w1.state='ROUTED';w.runtimes.w2.state='ROUTED';const a=d.selectReady(structuredClone(w)),b=d.selectReady(structuredClone(w));return stable(a)===stable(b)&&stable(a)===stable(['p1','p2'])?[]:[`selection ${stable(a)} / ${stable(b)}`];})},
{id:'R5-F9',law:'readiness mutates no runtime/session authority surface',run:d=>safe('R5-F9',()=>{const w=world();const before=protectedRuntimeView(w);const r=d.decide(w);return before===protectedRuntimeView(w)&&r.protected_unchanged?[]:['protected surface mutated'];})},
{id:'R5-F10',law:'live session recheck can still refuse stale scheduler capacity',run:d=>safe('R5-F10',()=>d.sessionRecheckAllows({observed_slots:1,live_active:2,live_limit:2})?['scheduler bypassed live session limit']:[])},
]);
