import type { A212ExperienceDesign } from './model';
export type Mutator=(x:any)=>void;
export const mutant=(base:A212ExperienceDesign,mutate:Mutator):A212ExperienceDesign=>{const x=structuredClone(base) as any;mutate(x);return x;};
export const defeatCandidates: readonly [string,string,Mutator][]=[
['D1-global-relationship-card','L1',x=>{x.location='RELATIONSHIP_CARD';}],
['D2-no-selected-relationship','L2',x=>{x.requiresSelectedRelationship=false;}],
['D3-no-active-editorial','L3',x=>{x.requiresActiveEditorialThread=false;}],
['D4-review-sources','L8',x=>{x.eligibility.excludesReviewAndFocus=false;}],
['D5-same-thread-listed','L7',x=>{x.eligibility.excludesSameThread=false;}],
['D6-unavailable-disabled-card','L7',x=>{x.eligibility.excludesUnavailable=false;}],
['D7-wrong-scope-disabled-card','L7',x=>{x.eligibility.excludesScopeIneligible=false;}],
['D8-latest-preselected','L11',x=>{x.selection.preselected=true;x.selection.selectionBasis='LATEST';}],
['D9-first-preselected','L11',x=>{x.selection.preselected=true;x.selection.selectionBasis='FIRST';}],
['D10-relevance-preselected','L11',x=>{x.selection.preselected=true;x.selection.selectionBasis='RELEVANCE';}],
['D11-recommended-label','L14',x=>{x.cards.recommendationLabel=true;}],
['D12-generated-title','L12',x=>{x.cards.generatedTitle=true;}],
['D13-generated-summary','L12',x=>{x.cards.generatedSummary=true;}],
['D14-member-turn-shown','L13',x=>{x.cards.showsMemberTurn=true;}],
['D15-full-transcript','L13',x=>{x.cards.showsWholeTranscript=true;}],
['D16-relationship-timeline','L21',x=>{x.relationshipTimeline=true;}],
['D17-merge-into-textarea','L16',x=>{x.selection.mergedIntoTextarea=true;}],
['D18-hidden-selection','L16',x=>{x.selection.visibleChip=false;}],
['D19-multiple-selected','L15',x=>{x.selection.maxSelected=3;}],
['D20-persists-next-turn','L17',x=>{x.selection.persistsAcrossTurns=true;x.selection.consumedAfterSend=false;}],
['D21-persists-relationship-change','L18',x=>{x.selection.persistsAcrossRelationshipChange=true;}],
['D22-persists-thread-change','L18',x=>{x.selection.persistsAcrossThreadChange=true;}],
['D23-stored-in-place','L19',x=>{x.selection.storedInPlace=true;}],
['D24-stored-in-return','L19',x=>{x.selection.storedInRelationshipReturn=true;}],
['D25-episode-count-fallback','L9',x=>{x.eligibility.failureFallsBackToEpisodeMetadata=true;}],
['D26-reuse-contentful-relationship-api','L5',x=>{x.eligibility.separateNarrowReadSeam=false;x.eligibility.relationshipApiRemainsContentFree=false;}],
['D27-auto-replace-unavailable','L20',x=>{x.selection.unavailableAutoReplacement=true;}],
['D28-duplicate-same-thread-history','L7',x=>{x.eligibility.excludesSameThread=false;}],
['D29-hide-manuscript','L21',x=>{x.manuscriptRemainsPrimary=false;x.modalByDefault=true;}],
['D30-memory-language','L23',x=>{x.actionLabel='Recall relationship memory';}],
['D31-open-old-thread','L22',x=>{x.opensOldThreadOnSelect=true;}],
['D32-no-exact-source-read','L9',x=>{x.eligibility.sourceBodyExact=false;}],
['D33-chooser-in-sanctuary','L4',x=>{x.unavailableInSanctuary=false;}],
['D34-permanent-preference','L19',x=>{x.selection.storedInRelationshipReturn=true;x.selection.persistsAcrossTurns=true;}],
['D35-relevance-order-authority','L10',x=>{x.ordering='RELEVANCE';x.orderingHasAuthority=true;}],
['D36-persistent-side-rail','L21',x=>{x.persistentSideRail=true;}],
['D37-broaden-carry-classes','L25',x=>{x.broadensCarryClasses=true;}],
['D38-product-implementation','L26',x=>{x.productImplementation=true;}],
];
