import type { A212ExperienceDesign } from './model';
export type LawResult={id:string;pass:boolean;detail:string};
export function evaluate(d:A212ExperienceDesign):LawResult[]{return [
{id:'L1',pass:d.location==='EDITORIAL_COMPOSER',detail:'chooser is Editorial-composer local'},
{id:'L2',pass:d.requiresSelectedRelationship,detail:'selected A2 relationship required'},
{id:'L3',pass:d.requiresActiveEditorialThread,detail:'active Editorial receiver required'},
{id:'L4',pass:d.unavailableInSanctuary,detail:'no carry-source chooser in Sanctuary'},
{id:'L5',pass:d.eligibility.separateNarrowReadSeam&&d.eligibility.relationshipApiRemainsContentFree,detail:'eligibility read is separate and relationship API stays content-free'},
{id:'L6',pass:d.eligibility.provesSameRelationship&&d.eligibility.provesEditorialSourceKind,detail:'same relationship and Editorial-only source proof'},
{id:'L7',pass:d.eligibility.excludesSameThread&&d.eligibility.excludesUnavailable&&d.eligibility.excludesScopeIneligible,detail:'ineligible sources omitted'},
{id:'L8',pass:d.eligibility.excludesReviewAndFocus,detail:'Review and Focus never become source choices'},
{id:'L9',pass:d.eligibility.sourceBodyExact&&!d.eligibility.failureFallsBackToEpisodeMetadata,detail:'exact source excerpt, no metadata fallback'},
{id:'L10',pass:d.ordering==='CHRONOLOGICAL'&&!d.orderingHasAuthority,detail:'presentation order has zero selection authority'},
{id:'L11',pass:!d.selection.preselected&&d.selection.selectionBasis==='EXPLICIT',detail:'zero preselection and explicit choice only'},
{id:'L12',pass:d.cards.exactExcerpt&&!d.cards.generatedTitle&&!d.cards.generatedSummary,detail:'exact excerpt without generated framing'},
{id:'L13',pass:!d.cards.showsMemberTurn&&!d.cards.showsWholeTranscript,detail:'first class shows no member turn or transcript'},
{id:'L14',pass:d.cards.showsScopeLabel&&!d.cards.recommendationLabel,detail:'truthful scope, no recommendation label'},
{id:'L15',pass:d.selection.maxSelected===1,detail:'one source maximum'},
{id:'L16',pass:d.selection.visibleChip&&d.selection.removable&&!d.selection.mergedIntoTextarea,detail:'selection is visible removable context separate from member words'},
{id:'L17',pass:d.selection.consumedAfterSend&&!d.selection.persistsAcrossTurns,detail:'selection is one-shot'},
{id:'L18',pass:!d.selection.persistsAcrossRelationshipChange&&!d.selection.persistsAcrossThreadChange&&!d.selection.persistsAcrossPlaceChange,detail:'selection clears on context changes'},
{id:'L19',pass:!d.selection.storedInPlace&&!d.selection.storedInRelationshipReturn,detail:'selection is not durable place/relationship preference'},
{id:'L20',pass:!d.selection.unavailableAutoReplacement,detail:'unavailable source is never silently replaced'},
{id:'L21',pass:d.manuscriptRemainsPrimary&&!d.modalByDefault&&!d.persistentSideRail&&!d.relationshipTimeline,detail:'manuscript-first compact inline geometry'},
{id:'L22',pass:!d.opensOldThreadOnSelect,detail:'selecting source does not navigate away'},
{id:'L23',pass:d.actionLabel==='Bring an earlier MAIA response'&&d.chooserHeading==='Earlier in this relationship'&&d.selectedLabel==='Earlier MAIA response',detail:'member copy avoids memory language'},
{id:'L24',pass:d.helperText.includes('Nothing is added unless you choose it.'),detail:'helper makes explicit-choice law visible'},
{id:'L25',pass:!d.broadensCarryClasses,detail:'no carry-class widening'},
{id:'L26',pass:!d.productImplementation,detail:'A2-12 remains design-only'},
];}
