import type {A213Contract} from './model';
export type LawResult={id:string;pass:boolean;detail:string};
export function evaluate(c:A213Contract):LawResult[]{return [
{id:'L1',pass:c.endpoint.method==='GET'&&c.endpoint.path==='/api/writers-studio/relationships/:relationshipId/carry-sources',detail:'separate narrow GET endpoint'},
{id:'L2',pass:c.endpoint.relationshipIdInPathOnly&&c.endpoint.receiverThreadIdRequired,detail:'one relationship identity + required receiver thread'},
{id:'L3',pass:!c.endpoint.mutates&&!c.endpoint.providerCall&&!c.endpoint.expandsRelationshipGet,detail:'read seam is non-mutating and relationship GET stays content-free'},
{id:'L4',pass:c.endpoint.featureGated&&c.endpoint.verifiedIdentity&&!c.endpoint.returnsOmittedSourceReasons,detail:'gated verified non-disclosing read'},
{id:'L5',pass:c.response.relationshipId&&c.response.receiverThreadId&&c.response.kindLiteral&&c.response.episodeSequence&&c.response.sourceScope&&c.response.admittedAt&&c.response.excerpt&&c.response.excerptTruncated,detail:'minimal response identity fields complete'},
{id:'L6',pass:!c.response.sourceThreadId&&!c.response.sourceMaiaTurnIndex&&!c.response.fullLongBody,detail:'source internal identity/full body not leaked'},
{id:'L7',pass:!c.response.generatedTitle&&!c.response.generatedSummary&&!c.response.relevanceScore,detail:'no generated/ranked framing'},
{id:'L8',pass:c.eligibility.provesRelationshipOwner&&c.eligibility.provesCurrentDeclaration&&c.eligibility.provesReceiverThread,detail:'relationship and receiver authority proved'},
{id:'L9',pass:c.eligibility.editorialOnly&&c.eligibility.excludesSameThread&&c.eligibility.excludesUnavailable&&c.eligibility.excludesScopeIneligible,detail:'only eligible A2-11 source class returned'},
{id:'L10',pass:c.eligibility.exactSourceBody&&!c.eligibility.exposesForeignExistence,detail:'exact source read without foreign/source omission leakage'},
{id:'L11',pass:c.excerpt.maxCodePoints===320&&c.excerpt.exactPrefix&&!c.excerpt.normalizesWhitespace&&!c.excerpt.serverAddsEllipsis&&!c.excerpt.generated,detail:'bounded exact excerpt law'},
{id:'L12',pass:c.sort==='CHRONOLOGICAL'&&!c.sortHasAuthority,detail:'chronological order has zero authority'},
{id:'L13',pass:c.client.strictParsing&&!c.client.cachesAcrossRelationship&&!c.client.cachesAcrossThread,detail:'strict identity-bound client read'},
{id:'L14',pass:!c.client.fallbackRelationshipRead&&!c.client.fallbackEpisodeCount&&!c.client.persistentCache,detail:'no metadata fallback or persistent cache'},
{id:'L15',pass:c.state.host==='REBUILD'&&c.state.generationGuard&&c.state.relationshipIdentityGuard&&c.state.threadIdentityGuard,detail:'Rebuild host owns race-safe state'},
{id:'L16',pass:!c.state.preselects&&c.state.maxSelected===1&&c.state.selectionSeparateFromText,detail:'explicit one-source selection separate from member words'},
{id:'L17',pass:!c.state.persistsLocalStorage&&!c.state.persistsSessionStorage&&!c.state.persistsRelationshipReturn&&!c.state.persistsPlaceReturn,detail:'selection state is ephemeral only'},
{id:'L18',pass:c.state.clearsRelationshipChange&&c.state.clearsThreadChange&&c.state.clearsPlaceRelease&&c.state.clearsReload,detail:'identity/context changes clear selection'},
{id:'L19',pass:c.send.sendsKind&&c.send.sendsSequence&&!c.send.sendsExcerpt&&!c.send.sendsSourceThread&&!c.send.sendsSourceScope,detail:'send carries only kind + episode sequence'},
{id:'L20',pass:c.send.runtimeReresolves,detail:'A2-11 re-resolves full source server-side'},
{id:'L21',pass:c.send.clearBeforeTransport&&c.send.preserveOnLocalPostureBlock,detail:'one-shot clear timing distinguishes pre-transport refusal'},
{id:'L22',pass:!c.send.restoreOnNetworkFailure&&!c.send.restoreOnServerStaleSource&&!c.send.autoReplaceStale,detail:'no hidden retry/reselection'},
{id:'L23',pass:c.presentation.actionLabel==='Bring an earlier MAIA response'&&c.presentation.chooserHeading==='Earlier in this relationship'&&c.presentation.selectedLabel==='Earlier MAIA response',detail:'copy matches accepted A2-12 language'},
{id:'L24',pass:c.presentation.desktopInline&&!c.presentation.desktopFullScreen&&!c.presentation.persistentSideRail,detail:'desktop stays inline manuscript-first'},
{id:'L25',pass:c.presentation.mobileReturnsSameComposer&&!c.presentation.mobileChangesRoute&&!c.presentation.oldThreadNavigation,detail:'mobile remains same conversation/place'},
{id:'L26',pass:c.presentation.revisionDeskPresentationOnly&&!c.presentation.canvasParallelImplementation,detail:'single host authority; RevisionDesk presentation-only'},
{id:'L27',pass:c.presentation.accessibleButtons&&c.presentation.statusAnnouncements,detail:'accessible control/status contract'},
{id:'L28',pass:!c.productImplementation,detail:'A2-13 remains implementation-contract only'},
];}
