/**
 * Type Guards - Auto-generated Runtime Type Validators
 * Generated by Stage 4.2a Type-Guard Synthesis
 *
 * These guards provide runtime safety for property access patterns
 * that TypeScript's static analysis cannot verify.
 *
 * @generated 2025-12-20T19:16:58.920Z
 */

/**
 * Runtime guard for hasRows
 * Confidence: 100% | Usage: 40 locations
 */
function hasRows(obj: unknown): obj is { rows: unknown } {
  return typeof obj === 'object' && obj !== null && 'rows' in obj;
}
