import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

type Rel='ALIGNMENT'|'TENSION'|'INHIBITS'|'EVOKES'|'NO_RELATION';
type Basis='EXPLICIT_WHEN_THEN'|'EXPLICIT_CONTRAST'|'EXPLICIT_INHIBITION'|'EXPLICIT_LINK'|null;
type Fixture={id:string;raw:string;left:{id:string;layer:string;text:string};right:{id:string;layer:string;text:string};expected:Rel;basis:Basis};
type Proposal={relation?:Rel;sourceId?:string|null;targetId?:string|null};
const fixtures:Fixture[]=[
{id:'M1_ALIGNMENT',raw:'Leaving makes sense to me, and when I imagine actually leaving my body settles.',left:{id:'AIR_LEAVE',layer:'AIR',text:'Leaving makes sense.'},right:{id:'EARTH_SETTLE',layer:'EARTH',text:'My body settles when I imagine leaving.'},expected:'ALIGNMENT',basis:'EXPLICIT_WHEN_THEN'},
{id:'M2_TENSION',raw:'I still love him, and at the same time I want to leave.',left:{id:'WATER_LOVE',layer:'WATER',text:'I still love him.'},right:{id:'FIRE_LEAVE',layer:'FIRE',text:'I want to leave.'},expected:'TENSION',basis:'EXPLICIT_CONTRAST'},
{id:'M3_INHIBITS',raw:'I want to launch this week, but I am so physically exhausted that I cannot sustain the push.',left:{id:'FIRE_LAUNCH',layer:'FIRE',text:'I want to launch this week.'},right:{id:'EARTH_EXHAUST',layer:'EARTH',text:'Physical exhaustion prevents sustaining the push.'},expected:'INHIBITS',basis:'EXPLICIT_INHIBITION'},
{id:'M4_UNBOUND',raw:'I am uncertain about the plan. I also feel afraid today.',left:{id:'AIR_UNCERTAIN',layer:'AIR',text:'I am uncertain about the plan.'},right:{id:'WATER_AFRAID',layer:'WATER',text:'I feel afraid today.'},expected:'NO_RELATION',basis:null},
{id:'M5_COOCCUR',raw:'The financial risk is real. I have also been tired all week.',left:{id:'AIR_RISK',layer:'AIR',text:'The financial risk is real.'},right:{id:'EARTH_TIRED',layer:'EARTH',text:'I have been tired all week.'},expected:'NO_RELATION',basis:null},
{id:'M6_EXPLICIT_LINK',raw:'When I think about the new path, I feel hope rise immediately.',left:{id:'AIR_NEWPATH',layer:'AIR',text:'I think about the new path.'},right:{id:'WATER_HOPE',layer:'WATER',text:'I feel hope rise.'},expected:'EVOKES',basis:'EXPLICIT_LINK'},
];
const MODEL='claude-sonnet-4-6',TEMP=0.65,MAX=500,REPEATS=2;
const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const remoteCode=String.raw`const mod=require('/app/node_modules/@anthropic-ai/sdk'); const Anthropic=mod.default||mod; let b=''; process.stdin.setEncoding('utf8'); process.stdin.on('data',c=>b+=c); process.stdin.on('end',async()=>{const r=JSON.parse(b); const client=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY}); const m=await client.messages.create({model:r.model,max_tokens:r.maxTokens,temperature:r.temperature,system:r.system,messages:[{role:'user',content:r.user}]}); const text=m.content.filter(x=>x.type==='text').map(x=>x.text).join(''); process.stdout.write(JSON.stringify({text,model:m.model}));});`;
const REMOTE='/tmp/relational-geometry-h3b.js';
function ssh(command:string,input?:string){const p=spawnSync('ssh',['soullab@minisforum',command],{input,encoding:'utf8',timeout:90000,maxBuffer:8*1024*1024}); if(p.status!==0)throw new Error(`ssh:${p.status}:${(p.stderr||'').slice(0,200)}`); return p.stdout;}
function install(){ssh(`docker exec -i maia-sovereign sh -c 'cat > ${REMOTE}'`,remoteCode);} function remove(){try{ssh(`docker exec maia-sovereign rm -f ${REMOTE}`);}catch{}}
const system=`Offline research. Given two differentiated channel nodes and raw member language, propose at most one cross-layer relation. Allowed: ALIGNMENT, TENSION, INHIBITS, EVOKES, NO_RELATION. Return JSON only: {"relation":...,"sourceId":string|null,"targetId":string|null}. Do not infer a relation merely from co-occurrence or thematic plausibility.`;
function call(f:Fixture){const user=`RAW MEMBER LANGUAGE:\n${f.raw}\nNODE A ${f.left.id} [${f.left.layer}]: ${f.left.text}\nNODE B ${f.right.id} [${f.right.layer}]: ${f.right.text}`; const req=JSON.stringify({model:MODEL,maxTokens:MAX,temperature:TEMP,system,user}); const out=ssh(`docker exec -i maia-sovereign node ${REMOTE}`,req); return JSON.parse(out.trim()) as {text:string;model:string};}
function parse(s:string):Proposal{return JSON.parse(s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));}
function gate(f:Fixture,p:Proposal){if(p.relation==='NO_RELATION'||!p.relation)return {relation:'NO_RELATION' as Rel,admitted:false,basis:'MODEL_ABSTAIN'}; if(!f.basis)return {relation:'NO_RELATION' as Rel,admitted:false,basis:'REJECT_NO_BINDING_EVIDENCE'}; const ids=new Set([f.left.id,f.right.id]); if(!p.sourceId||!p.targetId||!ids.has(p.sourceId)||!ids.has(p.targetId)||p.sourceId===p.targetId)return {relation:'NO_RELATION' as Rel,admitted:false,basis:'REJECT_BAD_ENDPOINTS'}; return {relation:p.relation,admitted:true,basis:f.basis};}
async function main(){install(); const rows:any[]=[]; const raw:any[]=[]; try{for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const r=call(f); let p:Proposal={relation:'NO_RELATION',sourceId:null,targetId:null}; let parseError:string|null=null; try{p=parse(r.text);}catch(e){parseError=e instanceof Error?e.message:String(e);} const g=gate(f,p); rows.push({fixture:f.id,run,rawHash:sha(r.text),model:r.model,proposal:p,parseError,gated:g,expected:f.expected,proposalCorrect:p.relation===f.expected,finalCorrect:g.relation===f.expected}); raw.push({fixture:f.id,run,text:r.text});}}finally{remove();}
const trueRows=rows.filter(r=>fixtures.find(f=>f.id===r.fixture)!.expected!=='NO_RELATION'); const nullRows=rows.filter(r=>fixtures.find(f=>f.id===r.fixture)!.expected==='NO_RELATION');
const summary={runs:rows.length,proposalCorrect:rows.filter(r=>r.proposalCorrect).length,finalCorrect:rows.filter(r=>r.finalCorrect).length,trueRelationsPreserved: trueRows.filter(r=>r.gated.relation===fixtures.find(f=>f.id===r.fixture)!.expected).length,trueRelationTotal:trueRows.length,falseRelationsBeforeGate:nullRows.filter(r=>r.proposal.relation!=='NO_RELATION').length,falseRelationsAfterGate:nullRows.filter(r=>r.gated.relation!=='NO_RELATION').length,abstentionCorrect:nullRows.filter(r=>r.gated.relation==='NO_RELATION').length,abstentionTotal:nullRows.length};
const out={schema:'RELATIONAL_GEOMETRY_H3B_MEDIATED_INTEGRATION_V1',authority:'offline research only',productionEquivalent:{provider:'anthropic',model:MODEL,temperature:TEMP},assumption:'binding-evidence class is preclassified for this pilot; automatic classification is not tested',summary,rows}; fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H3B_MEDIATED_INTEGRATION_2026-09-16.json'),JSON.stringify(out,null,2)+'\n'); fs.writeFileSync('/private/tmp/h3b-raw.json',JSON.stringify(raw,null,2)+'\n'); console.log(JSON.stringify(summary,null,2));}
main().catch(e=>{remove();console.error(e);process.exit(1)});
