import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { spawnSync } from 'node:child_process';
type Pred='ALIGNMENT'|'TENSION'|'INHIBITS'|'EVOKES'|'NO_RELATION'; type F={id:string;raw:string;nodes:{id:string;text:string}[];pred:Pred;source:string|null;target:string|null;symmetric:boolean};
const fixtures:F[]=[
{id:'D1_INHIBIT',raw:'I want to launch this week, but my physical exhaustion means I cannot sustain the push.',nodes:[{id:'FIRE_LAUNCH',text:'I want to launch.'},{id:'EARTH_EXHAUST',text:'Physical exhaustion prevents sustaining the push.'}],pred:'INHIBITS',source:'EARTH_EXHAUST',target:'FIRE_LAUNCH',symmetric:false},
{id:'D2_TENSION',raw:'I still love him, and at the same time I want to leave.',nodes:[{id:'WATER_LOVE',text:'I still love him.'},{id:'FIRE_LEAVE',text:'I want to leave.'}],pred:'TENSION',source:'WATER_LOVE',target:'FIRE_LEAVE',symmetric:true},
{id:'D3_EVOKES',raw:'When I think about the new path, hope rises immediately.',nodes:[{id:'AIR_NEWPATH',text:'I think about the new path.'},{id:'WATER_HOPE',text:'Hope rises.'}],pred:'EVOKES',source:'AIR_NEWPATH',target:'WATER_HOPE',symmetric:false},
{id:'D4_ALIGNMENT',raw:'Leaving makes sense to me, and when I imagine leaving my body settles.',nodes:[{id:'AIR_LEAVE',text:'Leaving makes sense.'},{id:'EARTH_SETTLE',text:'My body settles when I imagine leaving.'}],pred:'ALIGNMENT',source:'AIR_LEAVE',target:'EARTH_SETTLE',symmetric:true},
{id:'D5_NONE',raw:'I am uncertain about the plan. I also feel afraid today.',nodes:[{id:'AIR_UNCERTAIN',text:'I am uncertain.'},{id:'WATER_AFRAID',text:'I feel afraid.'}],pred:'NO_RELATION',source:null,target:null,symmetric:false},
{id:'D6_EVOKES_BODY',raw:'When I think about the financial risk, my chest tightens.',nodes:[{id:'AIR_RISK',text:'I think about financial risk.'},{id:'EARTH_TIGHTEN',text:'My chest tightens.'}],pred:'EVOKES',source:'AIR_RISK',target:'EARTH_TIGHTEN',symmetric:false},
];
const MODEL='claude-sonnet-4-6',TEMP=.65,MAX=420,REPEATS=2; const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const remoteCode=String.raw`const mod=require('/app/node_modules/@anthropic-ai/sdk');const Anthropic=mod.default||mod;let b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>b+=c);process.stdin.on('end',async()=>{const r=JSON.parse(b);const client=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY});const m=await client.messages.create({model:r.model,max_tokens:r.maxTokens,temperature:r.temperature,system:r.system,messages:[{role:'user',content:r.user}]});const text=m.content.filter(x=>x.type==='text').map(x=>x.text).join('');process.stdout.write(JSON.stringify({text,model:m.model}));});`;
const REMOTE='/tmp/relational-geometry-h3f.js';function ssh(command:string,input?:string){const p=spawnSync('ssh',['soullab@minisforum',command],{input,encoding:'utf8',timeout:90000,maxBuffer:8*1024*1024});if(p.status!==0)throw new Error(`ssh:${p.status}:${(p.stderr||'').slice(0,200)}`);return p.stdout;}function install(){ssh(`docker exec -i maia-sovereign sh -c 'cat > ${REMOTE}'`,remoteCode);}function remove(){try{ssh(`docker exec maia-sovereign rm -f ${REMOTE}`);}catch{}}
const system=`Offline relational-geometry research. Relations have operator laws: TENSION is symmetric conflict without directional blocking. ALIGNMENT is symmetric/co-supportive. INHIBITS is directed: source prevents or constrains target. EVOKES is directed: source elicits target. NO_RELATION for mere co-occurrence. Return JSON only {"predicate":"ALIGNMENT"|"TENSION"|"INHIBITS"|"EVOKES"|"NO_RELATION","sourceId":string|null,"targetId":string|null}. For symmetric relations either endpoint order is acceptable.`;
function call(f:F){const user=`MEMBER LANGUAGE:\n${f.raw}\nNODES:\n${f.nodes.map(n=>`${n.id}: ${n.text}`).join('\n')}`;const req=JSON.stringify({model:MODEL,maxTokens:MAX,temperature:TEMP,system,user});return JSON.parse(ssh(`docker exec -i maia-sovereign node ${REMOTE}`,req).trim()) as {text:string;model:string};}
function parse(s:string){return JSON.parse(s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')) as {predicate:Pred;sourceId:string|null;targetId:string|null};}
function correct(f:F,x:any){if(x.predicate!==f.pred)return false;if(f.pred==='NO_RELATION')return x.sourceId==null&&x.targetId==null;if(f.symmetric){return new Set([x.sourceId,x.targetId]).size===2&&new Set([x.sourceId,x.targetId]).has(f.source!)&&new Set([x.sourceId,x.targetId]).has(f.target!);}return x.sourceId===f.source&&x.targetId===f.target;}
async function main(){install();const rows:any[]=[];try{for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const r=call(f);let x={predicate:'NO_RELATION' as Pred,sourceId:null as string|null,targetId:null as string|null};let parseError:string|null=null;try{x=parse(r.text)}catch(e){parseError=e instanceof Error?e.message:String(e)}rows.push({fixture:f.id,run,rawHash:sha(r.text),model:r.model,...x,expected:{predicate:f.pred,sourceId:f.source,targetId:f.target,symmetric:f.symmetric},parseError,correct:correct(f,x)});}}finally{remove();}const summary={runs:rows.length,correct:rows.filter(r=>r.correct).length,byFixture:Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{correct:rs.filter(r=>r.correct).length,runs:rs.length,predictions:rs.map(r=>({predicate:r.predicate,sourceId:r.sourceId,targetId:r.targetId}))}]}))};const out={schema:'RELATIONAL_GEOMETRY_H3F_OPERATOR_DIRECTIONALITY_V1',authority:'offline research only',productionEquivalent:{provider:'anthropic',model:MODEL,temperature:TEMP},summary,rows};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H3F_OPERATOR_DIRECTIONALITY_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(summary,null,2));}
main().catch(e=>{remove();console.error(e);process.exit(1)});
