import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

type DynPred='EVOKES'|'INHIBITS'|'NONE';
type DynBasis='EXPLICIT_ELICITATION'|'EXPLICIT_INHIBITION'|'NONE';
type ConfigPred='ALIGNMENT'|'TENSION'|'NONE';
type ConfigBasis='EXPLICIT_CONSONANCE'|'EXPLICIT_CONTRAST'|'NONE';
type Node={id:string;text:string};
type Dynamic={predicate:DynPred;directionality:'DIRECTED'|'NONE';sourceId:string|null;targetId:string|null;evidenceBasis:DynBasis};
type Configuration={predicate:ConfigPred;directionality:'SYMMETRIC'|'NONE';endpointIds:string[];evidenceBasis:ConfigBasis};
type Expected={dynamic:Dynamic;configuration:Configuration};
type Fixture={id:string;raw:string;nodes:Node[];expected:Expected};

const fixtures:Fixture[]=[
 {id:'H1_DYNAMIC_PLUS_ALIGNMENT',raw:'Thinking about leaving brings a settling in my body, and the thought and bodily response both point in the same direction.',nodes:[{id:'AIR_LEAVE',text:'Thinking about leaving.'},{id:'EARTH_SETTLE',text:'My body settles.'}],expected:{dynamic:{predicate:'EVOKES',directionality:'DIRECTED',sourceId:'AIR_LEAVE',targetId:'EARTH_SETTLE',evidenceBasis:'EXPLICIT_ELICITATION'},configuration:{predicate:'ALIGNMENT',directionality:'SYMMETRIC',endpointIds:['AIR_LEAVE','EARTH_SETTLE'],evidenceBasis:'EXPLICIT_CONSONANCE'}}},
 {id:'H2_TENSION_ONLY',raw:'I still love him, and I want to leave. Those two truths pull against each other, but neither one causes the other.',nodes:[{id:'WATER_LOVE',text:'I still love him.'},{id:'FIRE_LEAVE',text:'I want to leave.'}],expected:{dynamic:{predicate:'NONE',directionality:'NONE',sourceId:null,targetId:null,evidenceBasis:'NONE'},configuration:{predicate:'TENSION',directionality:'SYMMETRIC',endpointIds:['WATER_LOVE','FIRE_LEAVE'],evidenceBasis:'EXPLICIT_CONTRAST'}}},
 {id:'H3_INHIBITS_PLUS_TENSION',raw:'My physical exhaustion prevents me from sustaining the launch, and that bodily limit pulls directly against the push I want to make.',nodes:[{id:'EARTH_EXHAUST',text:'Physical exhaustion.'},{id:'FIRE_LAUNCH',text:'I want to sustain the launch push.'}],expected:{dynamic:{predicate:'INHIBITS',directionality:'DIRECTED',sourceId:'EARTH_EXHAUST',targetId:'FIRE_LAUNCH',evidenceBasis:'EXPLICIT_INHIBITION'},configuration:{predicate:'TENSION',directionality:'SYMMETRIC',endpointIds:['EARTH_EXHAUST','FIRE_LAUNCH'],evidenceBasis:'EXPLICIT_CONTRAST'}}},
 {id:'H4_DYNAMIC_ONLY',raw:'Thinking about the financial risk brings tightness into my chest. I do not yet know whether that bodily response supports or opposes the decision.',nodes:[{id:'AIR_RISK',text:'Thinking about financial risk.'},{id:'EARTH_TIGHTEN',text:'Chest tightness.'}],expected:{dynamic:{predicate:'EVOKES',directionality:'DIRECTED',sourceId:'AIR_RISK',targetId:'EARTH_TIGHTEN',evidenceBasis:'EXPLICIT_ELICITATION'},configuration:{predicate:'NONE',directionality:'NONE',endpointIds:[],evidenceBasis:'NONE'}}},
 {id:'H5_ALIGNMENT_ONLY',raw:'My reasoning says wait, and my desire also says wait. They point the same way, but neither one causes the other.',nodes:[{id:'AIR_WAIT',text:'My reasoning says wait.'},{id:'FIRE_WAIT',text:'My desire says wait.'}],expected:{dynamic:{predicate:'NONE',directionality:'NONE',sourceId:null,targetId:null,evidenceBasis:'NONE'},configuration:{predicate:'ALIGNMENT',directionality:'SYMMETRIC',endpointIds:['AIR_WAIT','FIRE_WAIT'],evidenceBasis:'EXPLICIT_CONSONANCE'}}},
 {id:'H6_NEITHER',raw:'I am uncertain about the plan. I also feel afraid today. I have not said that one causes, supports, blocks, or conflicts with the other.',nodes:[{id:'AIR_UNCERTAIN',text:'I am uncertain about the plan.'},{id:'WATER_AFRAID',text:'I feel afraid today.'}],expected:{dynamic:{predicate:'NONE',directionality:'NONE',sourceId:null,targetId:null,evidenceBasis:'NONE'},configuration:{predicate:'NONE',directionality:'NONE',endpointIds:[],evidenceBasis:'NONE'}}},
];

const MODEL='claude-sonnet-4-6',REPEATS=2; const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const system=`Offline relational-geometry research. Analyze TWO INDEPENDENT relation dimensions. Return JSON only: {"dynamic":{"predicate":"EVOKES"|"INHIBITS"|"NONE","directionality":"DIRECTED"|"NONE","sourceId":string|null,"targetId":string|null,"evidenceBasis":"EXPLICIT_ELICITATION"|"EXPLICIT_INHIBITION"|"NONE"},"configuration":{"predicate":"ALIGNMENT"|"TENSION"|"NONE","directionality":"SYMMETRIC"|"NONE","endpointIds":string[],"evidenceBasis":"EXPLICIT_CONSONANCE"|"EXPLICIT_CONTRAST"|"NONE"}}. Dynamic and configuration are independent: either, both, or neither may be present. EVOKES requires language of elicitation/bringing-on, not sequence alone. INHIBITS requires explicit blocking/constraint. ALIGNMENT requires explicit same-direction/support/consonance. TENSION requires explicit opposition/pull-against/contrast. Mere co-occurrence supports neither. Never infer one dimension merely because the other exists.`;
function call(f:Fixture){const user=`MEMBER LANGUAGE:\n${f.raw}\nNODES:\n${f.nodes.map(n=>`${n.id}: ${n.text}`).join('\n')}`;const p=spawnSync('claude',['-p','--model',MODEL,'--effort','low','--system-prompt',system,'--restricted','--tools','','--output-format','text',user],{encoding:'utf8',timeout:90000,maxBuffer:8*1024*1024,input:''});if(p.status!==0)throw new Error(`claude-cli:${p.status}:${(p.stderr||'').slice(0,300)}`);return {text:p.stdout.trim(),model:MODEL};}
function parse(s:string){return JSON.parse(s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')) as Expected;}
const setEq=(a:string[],b:string[])=>a.length===b.length&&a.every(x=>b.includes(x));
function score(f:Fixture,x:Expected){const d=f.expected.dynamic,c=f.expected.configuration;return {dynamicPredicate:x.dynamic?.predicate===d.predicate,dynamicDirection:x.dynamic?.directionality===d.directionality,dynamicEndpoints:x.dynamic?.sourceId===d.sourceId&&x.dynamic?.targetId===d.targetId,dynamicBasis:x.dynamic?.evidenceBasis===d.evidenceBasis,configPredicate:x.configuration?.predicate===c.predicate,configDirection:x.configuration?.directionality===c.directionality,configEndpoints:setEq(x.configuration?.endpointIds??[],c.endpointIds),configBasis:x.configuration?.evidenceBasis===c.evidenceBasis};}
async function main(){const rows:any[]=[];for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const r=call(f);let x:Expected={dynamic:{predicate:'NONE',directionality:'NONE',sourceId:null,targetId:null,evidenceBasis:'NONE'},configuration:{predicate:'NONE',directionality:'NONE',endpointIds:[],evidenceBasis:'NONE'}};let parseError:string|null=null;try{x=parse(r.text)}catch(e){parseError=e instanceof Error?e.message:String(e)}const axes=score(f,x);rows.push({fixture:f.id,run,rawHash:sha(r.text),prediction:x,expected:f.expected,axes,allCorrect:Object.values(axes).every(Boolean),parseError});}
const names=['dynamicPredicate','dynamicDirection','dynamicEndpoints','dynamicBasis','configPredicate','configDirection','configEndpoints','configBasis'] as const;const axisTotals=Object.fromEntries(names.map(k=>[k,{correct:rows.filter(r=>r.axes[k]).length,total:rows.length}]));const byFixture=Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{runs:rs.length,allCorrect:rs.filter(r=>r.allCorrect).length,predictions:rs.map(r=>r.prediction)}]}));const bothExpected=rows.filter(r=>r.expected.dynamic.predicate!=='NONE'&&r.expected.configuration.predicate!=='NONE');const dynamicOnly=rows.filter(r=>r.expected.dynamic.predicate!=='NONE'&&r.expected.configuration.predicate==='NONE');const configOnly=rows.filter(r=>r.expected.dynamic.predicate==='NONE'&&r.expected.configuration.predicate!=='NONE');const neither=rows.filter(r=>r.expected.dynamic.predicate==='NONE'&&r.expected.configuration.predicate==='NONE');const out={schema:'RELATIONAL_GEOMETRY_H3H_INDEPENDENT_RELATIONS_V1',authority:'offline research only',inference:{provider:'anthropic',model:MODEL,path:'local Claude CLI restricted/no-tools',effort:'low'},hypothesis:'Dynamic interaction and configuration are independently representable and require dimension-specific evidence.',summary:{runs:rows.length,allCorrect:rows.filter(r=>r.allCorrect).length,axisTotals,bothExpected:{runs:bothExpected.length,allCorrect:bothExpected.filter(r=>r.allCorrect).length},dynamicOnly:{runs:dynamicOnly.length,allCorrect:dynamicOnly.filter(r=>r.allCorrect).length},configOnly:{runs:configOnly.length,allCorrect:configOnly.filter(r=>r.allCorrect).length},neither:{runs:neither.length,allCorrect:neither.filter(r=>r.allCorrect).length}},byFixture,rows};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H3H_INDEPENDENT_RELATIONS_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({summary:out.summary,byFixture},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
