import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

type Basis='EXPLICIT_ELICITATION'|'EXPLICIT_INHIBITION'|'EXPLICIT_CONSONANCE'|'EXPLICIT_CONTRAST';
type EvidenceItem={basis:Basis;sourceId:string;targetId:string;quote:string};
type Node={id:string;text:string};
type Fixture={id:string;raw:string;nodes:Node[];expected:Omit<EvidenceItem,'quote'>[]};

const fixtures:Fixture[]=[
 {id:'I1_DYNAMIC_PLUS_ALIGNMENT',raw:'Thinking about leaving brings a settling in my body, and the thought and bodily response both point in the same direction.',nodes:[{id:'AIR_LEAVE',text:'Thinking about leaving.'},{id:'EARTH_SETTLE',text:'My body settles.'}],expected:[{basis:'EXPLICIT_ELICITATION',sourceId:'AIR_LEAVE',targetId:'EARTH_SETTLE'},{basis:'EXPLICIT_CONSONANCE',sourceId:'AIR_LEAVE',targetId:'EARTH_SETTLE'}]},
 {id:'I2_TENSION_ONLY',raw:'I still love him, and I want to leave. Those two truths pull against each other, but neither one causes the other.',nodes:[{id:'WATER_LOVE',text:'I still love him.'},{id:'FIRE_LEAVE',text:'I want to leave.'}],expected:[{basis:'EXPLICIT_CONTRAST',sourceId:'WATER_LOVE',targetId:'FIRE_LEAVE'}]},
 {id:'I3_INHIBITS_PLUS_TENSION',raw:'My physical exhaustion prevents me from sustaining the launch, and that bodily limit pulls directly against the push I want to make.',nodes:[{id:'EARTH_EXHAUST',text:'Physical exhaustion.'},{id:'FIRE_LAUNCH',text:'I want to sustain the launch push.'}],expected:[{basis:'EXPLICIT_INHIBITION',sourceId:'EARTH_EXHAUST',targetId:'FIRE_LAUNCH'},{basis:'EXPLICIT_CONTRAST',sourceId:'EARTH_EXHAUST',targetId:'FIRE_LAUNCH'}]},
 {id:'I4_DYNAMIC_ONLY',raw:'Thinking about the financial risk brings tightness into my chest. I do not yet know whether that bodily response supports or opposes the decision.',nodes:[{id:'AIR_RISK',text:'Thinking about financial risk.'},{id:'EARTH_TIGHTEN',text:'Chest tightness.'}],expected:[{basis:'EXPLICIT_ELICITATION',sourceId:'AIR_RISK',targetId:'EARTH_TIGHTEN'}]},
 {id:'I5_ALIGNMENT_ONLY',raw:'My reasoning says wait, and my desire also says wait. They point the same way, but neither one causes the other.',nodes:[{id:'AIR_WAIT',text:'My reasoning says wait.'},{id:'FIRE_WAIT',text:'My desire says wait.'}],expected:[{basis:'EXPLICIT_CONSONANCE',sourceId:'AIR_WAIT',targetId:'FIRE_WAIT'}]},
 {id:'I6_NEITHER',raw:'I am uncertain about the plan. I also feel afraid today. I have not said that one causes, supports, blocks, or conflicts with the other.',nodes:[{id:'AIR_UNCERTAIN',text:'I am uncertain about the plan.'},{id:'WATER_AFRAID',text:'I feel afraid today.'}],expected:[]},
];

const MODEL='claude-sonnet-4-6',REPEATS=2;const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const system=`Offline relational-geometry evidence extraction. Do NOT output relation predicates. Extract only explicit member-authored evidence spans that support one of these basis classes: EXPLICIT_ELICITATION = language that one node brings on/elicits the other; EXPLICIT_INHIBITION = one node explicitly blocks/prevents/constrains the other; EXPLICIT_CONSONANCE = the two nodes explicitly point/support/pull in the same direction; EXPLICIT_CONTRAST = the two nodes explicitly oppose/pull against/are in conflict. Return JSON only: {"evidence":[{"basis":"EXPLICIT_ELICITATION"|"EXPLICIT_INHIBITION"|"EXPLICIT_CONSONANCE"|"EXPLICIT_CONTRAST","sourceId":string,"targetId":string,"quote":string}]}. quote must be an exact contiguous span from MEMBER LANGUAGE. For symmetric consonance/contrast, either endpoint order is acceptable. Extract multiple items when independent evidence classes are explicitly present. Mere co-occurrence is not evidence. If no explicit evidence exists, return {"evidence":[]}.`;
function call(f:Fixture){const user=`MEMBER LANGUAGE:\n${f.raw}\nNODES:\n${f.nodes.map(n=>`${n.id}: ${n.text}`).join('\n')}`;const p=spawnSync('claude',['-p','--model',MODEL,'--effort','low','--system-prompt',system,'--restricted','--tools','','--output-format','text',user],{encoding:'utf8',timeout:90000,maxBuffer:8*1024*1024,input:''});if(p.status!==0)throw new Error(`claude-cli:${p.status}:${(p.stderr||'').slice(0,300)}`);return {text:p.stdout.trim(),model:MODEL};}
function parse(s:string){const x=JSON.parse(s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')) as {evidence?:EvidenceItem[]};return Array.isArray(x.evidence)?x.evidence:[];}
const norm=(s:string)=>s.replace(/[“”]/g,'"').replace(/[’]/g,"'").replace(/\s+/g,' ').trim().toLowerCase();
const symmetric=(b:Basis)=>b==='EXPLICIT_CONSONANCE'||b==='EXPLICIT_CONTRAST';
function sameItem(a:Omit<EvidenceItem,'quote'>,b:Omit<EvidenceItem,'quote'>){if(a.basis!==b.basis)return false;if(symmetric(a.basis))return new Set([a.sourceId,a.targetId]).size===2&&new Set([a.sourceId,a.targetId]).has(b.sourceId)&&new Set([a.sourceId,a.targetId]).has(b.targetId);return a.sourceId===b.sourceId&&a.targetId===b.targetId;}
function gate(f:Fixture,items:EvidenceItem[]){const validIds=new Set(f.nodes.map(n=>n.id));const admitted:Omit<EvidenceItem,'quote'>[]=[];const rejected:any[]=[];for(const item of items){const quoteOk=norm(f.raw).includes(norm(item.quote));const idsOk=validIds.has(item.sourceId)&&validIds.has(item.targetId)&&item.sourceId!==item.targetId;if(!quoteOk||!idsOk){rejected.push({item,reason:!quoteOk?'QUOTE_NOT_EXACT':'INVALID_ENDPOINT'});continue;}admitted.push({basis:item.basis,sourceId:item.sourceId,targetId:item.targetId});}return{admitted,rejected};}
function setScore(expected:Omit<EvidenceItem,'quote'>[],actual:Omit<EvidenceItem,'quote'>[]){const matchedExpected=new Set<number>(),matchedActual=new Set<number>();expected.forEach((e,i)=>actual.forEach((a,j)=>{if(!matchedExpected.has(i)&&!matchedActual.has(j)&&sameItem(e,a)){matchedExpected.add(i);matchedActual.add(j);}}));const tp=matchedExpected.size,fp=actual.length-tp,fn=expected.length-tp;return{tp,fp,fn,exact:fp===0&&fn===0};}
const canonical=(item:Omit<EvidenceItem,'quote'>)=>{switch(item.basis){case'EXPLICIT_ELICITATION':return{dimension:'DYNAMIC',predicate:'EVOKES',direction:'DIRECTED',sourceId:item.sourceId,targetId:item.targetId};case'EXPLICIT_INHIBITION':return{dimension:'DYNAMIC',predicate:'INHIBITS',direction:'DIRECTED',sourceId:item.sourceId,targetId:item.targetId};case'EXPLICIT_CONSONANCE':return{dimension:'CONFIGURATION',predicate:'ALIGNMENT',direction:'SYMMETRIC',endpointIds:[item.sourceId,item.targetId].sort()};case'EXPLICIT_CONTRAST':return{dimension:'CONFIGURATION',predicate:'TENSION',direction:'SYMMETRIC',endpointIds:[item.sourceId,item.targetId].sort()};}};
async function main(){const rows:any[]=[];for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const r=call(f);let items:EvidenceItem[]=[];let parseError:string|null=null;try{items=parse(r.text)}catch(e){parseError=e instanceof Error?e.message:String(e)}const gated=gate(f,items),score=setScore(f.expected,gated.admitted);rows.push({fixture:f.id,run,rawHash:sha(r.text),proposedCount:items.length,admitted:gated.admitted,rejected:gated.rejected,canonical:gated.admitted.map(canonical),expected:f.expected,score,parseError});}
const totals=rows.reduce((a,r)=>({tp:a.tp+r.score.tp,fp:a.fp+r.score.fp,fn:a.fn+r.score.fn}),{tp:0,fp:0,fn:0});const precision=totals.tp/(totals.tp+totals.fp||1),recall=totals.tp/(totals.tp+totals.fn||1);const byFixture=Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{runs:rs.length,exact:rs.filter(r=>r.score.exact).length,rows:rs.map(r=>({admitted:r.admitted,rejected:r.rejected,canonical:r.canonical,score:r.score}))}]}));const out={schema:'RELATIONAL_GEOMETRY_H3I_EVIDENCE_FIRST_V1',authority:'offline research only',inference:{provider:'anthropic',model:MODEL,path:'local Claude CLI restricted/no-tools',effort:'low'},law:'Model extracts exact evidence spans and basis classes; deterministic code admits and canonicalizes relation dimensions.',summary:{runs:rows.length,exact:rows.filter(r=>r.score.exact).length,tp:totals.tp,fp:totals.fp,fn:totals.fn,precision,recall,falsePositiveOnNeither:rows.filter(r=>r.fixture==='I6_NEITHER'&&r.score.fp>0).length},byFixture,rows};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H3I_EVIDENCE_FIRST_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({summary:out.summary,byFixture},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
