import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

type DynBasis='EXPLICIT_ELICITATION'|'EXPLICIT_INHIBITION'|'NONE';
type ConfigBasis='EXPLICIT_CONSONANCE'|'EXPLICIT_CONTRAST'|'NONE';
type Node={id:string;text:string};
type DynEvidence={basis:DynBasis;sourceId:string|null;targetId:string|null;quote:string|null};
type ConfigEvidence={basis:ConfigBasis;sourceId:string|null;targetId:string|null;quote:string|null};
type Fixture={id:string;raw:string;nodes:Node[];expectedDyn:Omit<DynEvidence,'quote'>;expectedConfig:Omit<ConfigEvidence,'quote'>};

const fixtures:Fixture[]=[
 {id:'J1_DYNAMIC_PLUS_ALIGNMENT',raw:'Thinking about leaving brings a settling in my body, and the thought and bodily response both point in the same direction.',nodes:[{id:'AIR_LEAVE',text:'Thinking about leaving.'},{id:'EARTH_SETTLE',text:'My body settles.'}],expectedDyn:{basis:'EXPLICIT_ELICITATION',sourceId:'AIR_LEAVE',targetId:'EARTH_SETTLE'},expectedConfig:{basis:'EXPLICIT_CONSONANCE',sourceId:'AIR_LEAVE',targetId:'EARTH_SETTLE'}},
 {id:'J2_TENSION_ONLY',raw:'I still love him, and I want to leave. Those two truths pull against each other, but neither one causes the other.',nodes:[{id:'WATER_LOVE',text:'I still love him.'},{id:'FIRE_LEAVE',text:'I want to leave.'}],expectedDyn:{basis:'NONE',sourceId:null,targetId:null},expectedConfig:{basis:'EXPLICIT_CONTRAST',sourceId:'WATER_LOVE',targetId:'FIRE_LEAVE'}},
 {id:'J3_INHIBITS_PLUS_TENSION',raw:'My physical exhaustion prevents me from sustaining the launch, and that bodily limit pulls directly against the push I want to make.',nodes:[{id:'EARTH_EXHAUST',text:'Physical exhaustion.'},{id:'FIRE_LAUNCH',text:'I want to sustain the launch push.'}],expectedDyn:{basis:'EXPLICIT_INHIBITION',sourceId:'EARTH_EXHAUST',targetId:'FIRE_LAUNCH'},expectedConfig:{basis:'EXPLICIT_CONTRAST',sourceId:'EARTH_EXHAUST',targetId:'FIRE_LAUNCH'}},
 {id:'J4_DYNAMIC_ONLY',raw:'Thinking about the financial risk brings tightness into my chest. I do not yet know whether that bodily response supports or opposes the decision.',nodes:[{id:'AIR_RISK',text:'Thinking about financial risk.'},{id:'EARTH_TIGHTEN',text:'Chest tightness.'}],expectedDyn:{basis:'EXPLICIT_ELICITATION',sourceId:'AIR_RISK',targetId:'EARTH_TIGHTEN'},expectedConfig:{basis:'NONE',sourceId:null,targetId:null}},
 {id:'J5_ALIGNMENT_ONLY',raw:'My reasoning says wait, and my desire also says wait. They point the same way, but neither one causes the other.',nodes:[{id:'AIR_WAIT',text:'My reasoning says wait.'},{id:'FIRE_WAIT',text:'My desire says wait.'}],expectedDyn:{basis:'NONE',sourceId:null,targetId:null},expectedConfig:{basis:'EXPLICIT_CONSONANCE',sourceId:'AIR_WAIT',targetId:'FIRE_WAIT'}},
 {id:'J6_NEITHER',raw:'I am uncertain about the plan. I also feel afraid today. I have not said that one causes, supports, blocks, or conflicts with the other.',nodes:[{id:'AIR_UNCERTAIN',text:'I am uncertain about the plan.'},{id:'WATER_AFRAID',text:'I feel afraid today.'}],expectedDyn:{basis:'NONE',sourceId:null,targetId:null},expectedConfig:{basis:'NONE',sourceId:null,targetId:null}},
];

const MODEL='claude-sonnet-4-6',REPEATS=2;const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const dynSystem=`Offline DYNAMIC relation evidence extractor. Judge ONLY directed dynamic interaction. Return JSON only {"basis":"EXPLICIT_ELICITATION"|"EXPLICIT_INHIBITION"|"NONE","sourceId":string|null,"targetId":string|null,"quote":string|null}. EXPLICIT_ELICITATION requires explicit language that one node brings on/elicits the other. EXPLICIT_INHIBITION requires explicit blocking/preventing/constraining. Ignore alignment, tension, same-direction, and contrast; those belong to another extractor. Mere co-occurrence or temporal sequence is NONE. quote must be an exact contiguous span from MEMBER LANGUAGE when basis is not NONE.`;
const configSystem=`Offline CONFIGURATION relation evidence extractor. Judge ONLY symmetric configuration. Return JSON only {"basis":"EXPLICIT_CONSONANCE"|"EXPLICIT_CONTRAST"|"NONE","sourceId":string|null,"targetId":string|null,"quote":string|null}. EXPLICIT_CONSONANCE requires explicit same-direction/support/consonance. EXPLICIT_CONTRAST requires explicit opposition/pull-against/conflict. Ignore causation, elicitation, blocking, and inhibition; those belong to another extractor. Mere co-occurrence is NONE. quote must be an exact contiguous span from MEMBER LANGUAGE when basis is not NONE.`;
function call(system:string,f:Fixture):Promise<string>{const user=`MEMBER LANGUAGE:\n${f.raw}\nNODES:\n${f.nodes.map(n=>`${n.id}: ${n.text}`).join('\n')}`;return new Promise((resolve,reject)=>{const p=spawn('claude',['-p','--model',MODEL,'--effort','low','--system-prompt',system,'--restricted','--tools','','--output-format','text',user],{stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{p.kill('SIGKILL');reject(new Error('claude-timeout'));},90000);p.stdout.setEncoding('utf8');p.stderr.setEncoding('utf8');p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{clearTimeout(timer);reject(e)});p.on('close',code=>{clearTimeout(timer);if(code!==0)reject(new Error(`claude-cli:${code}:${err.slice(0,300)}`));else resolve(out.trim());});p.stdin.end();});}
function clean(s:string){return s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');}
function parseDyn(s:string):DynEvidence{return JSON.parse(clean(s)) as DynEvidence;} function parseConfig(s:string):ConfigEvidence{return JSON.parse(clean(s)) as ConfigEvidence;}
const norm=(s:string)=>s.replace(/[“”]/g,'"').replace(/[’]/g,"'").replace(/\s+/g,' ').trim().toLowerCase();
function gate<T extends {basis:string;sourceId:string|null;targetId:string|null;quote:string|null}>(f:Fixture,x:T){if(x.basis==='NONE')return{admitted:{...x,quote:null},rejected:null};const ids=new Set(f.nodes.map(n=>n.id));const quoteOk=!!x.quote&&norm(f.raw).includes(norm(x.quote));const idsOk=!!x.sourceId&&!!x.targetId&&x.sourceId!==x.targetId&&ids.has(x.sourceId)&&ids.has(x.targetId);if(!quoteOk||!idsOk)return{admitted:null,rejected:{...x,reason:!quoteOk?'QUOTE_NOT_EXACT':'INVALID_ENDPOINT'}};return{admitted:{...x,quote:null},rejected:null};}
const sameDyn=(a:any,b:any)=>a?.basis===b.basis&&a?.sourceId===b.sourceId&&a?.targetId===b.targetId;
const sameConfig=(a:any,b:any)=>{if(a?.basis!==b.basis)return false;if(b.basis==='NONE')return a?.sourceId==null&&a?.targetId==null;return new Set([a?.sourceId,a?.targetId]).size===2&&new Set([a?.sourceId,a?.targetId]).has(b.sourceId)&&new Set([a?.sourceId,a?.targetId]).has(b.targetId);};
function canonicalDyn(x:any){if(!x||x.basis==='NONE')return null;return x.basis==='EXPLICIT_ELICITATION'?{dimension:'DYNAMIC',predicate:'EVOKES',direction:'DIRECTED',sourceId:x.sourceId,targetId:x.targetId}:{dimension:'DYNAMIC',predicate:'INHIBITS',direction:'DIRECTED',sourceId:x.sourceId,targetId:x.targetId};}
function canonicalConfig(x:any){if(!x||x.basis==='NONE')return null;return{dimension:'CONFIGURATION',predicate:x.basis==='EXPLICIT_CONSONANCE'?'ALIGNMENT':'TENSION',direction:'SYMMETRIC',endpointIds:[x.sourceId,x.targetId].sort()};}
async function main(){const rows:any[]=[];for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const [dRaw,cRaw]=await Promise.all([call(dynSystem,f),call(configSystem,f)]);let d:DynamicFallback={basis:'NONE',sourceId:null,targetId:null,quote:null};let c:ConfigFallback={basis:'NONE',sourceId:null,targetId:null,quote:null};let dErr:string|null=null,cErr:string|null=null;try{d=parseDyn(dRaw)}catch(e){dErr=e instanceof Error?e.message:String(e)}try{c=parseConfig(cRaw)}catch(e){cErr=e instanceof Error?e.message:String(e)}const dg=gate(f,d),cg=gate(f,c);const dynOk=dg.admitted?sameDyn(dg.admitted,f.expectedDyn):false;const cfgOk=cg.admitted?sameConfig(cg.admitted,f.expectedConfig):false;rows.push({fixture:f.id,run,dynamicHash:sha(dRaw),configHash:sha(cRaw),dynamic:{proposal:d,...dg,expected:f.expectedDyn,correct:dynOk,parseError:dErr,canonical:canonicalDyn(dg.admitted)},configuration:{proposal:c,...cg,expected:f.expectedConfig,correct:cfgOk,parseError:cErr,canonical:canonicalConfig(cg.admitted)},allCorrect:dynOk&&cfgOk});}
const byFixture=Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{runs:rs.length,allCorrect:rs.filter(r=>r.allCorrect).length,dynamicCorrect:rs.filter(r=>r.dynamic.correct).length,configurationCorrect:rs.filter(r=>r.configuration.correct).length}]}));const out={schema:'RELATIONAL_GEOMETRY_H3J_PARALLEL_EXTRACTORS_V1',authority:'offline research only',inference:{provider:'anthropic',model:MODEL,path:'parallel local Claude CLI restricted/no-tools',effort:'low'},hypothesis:'Dimension-specific parallel evidence extraction improves multidimensional recall without increasing false-positive relations.',summary:{runs:rows.length,allCorrect:rows.filter(r=>r.allCorrect).length,dynamicCorrect:rows.filter(r=>r.dynamic.correct).length,configurationCorrect:rows.filter(r=>r.configuration.correct).length,falsePositiveDynamic:rows.filter(r=>r.dynamic.expected.basis==='NONE'&&r.dynamic.admitted?.basis!=='NONE').length,falsePositiveConfiguration:rows.filter(r=>r.configuration.expected.basis==='NONE'&&r.configuration.admitted?.basis!=='NONE').length},byFixture,rows};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H3J_PARALLEL_EXTRACTORS_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({summary:out.summary,byFixture},null,2));}
type DynamicFallback=DynEvidence; type ConfigFallback=ConfigEvidence;
main().catch(e=>{console.error(e);process.exit(1)});
