import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

type PairPred='ALIGNMENT'|'TENSION'|'NONE';
type Higher='COLLECTIVE_CONSTRAINT'|'COLLECTIVE_SYNERGY'|'NONE';
type Node={id:string;text:string};
type PairEdge={a:string;b:string;predicate:PairPred};
type Fixture={id:string;raw:string;nodes:Node[];pairs:PairEdge[];higher:Higher;members:string[];evidenceQuote:string|null;collisionGroup?:string};
const allAlign=(ids:string[]):PairEdge[]=>[[0,1],[0,2],[1,2]].map(([i,j])=>({a:ids[i]!,b:ids[j]!,predicate:'ALIGNMENT'}));
const allTension=(ids:string[]):PairEdge[]=>[[0,1],[0,2],[1,2]].map(([i,j])=>({a:ids[i]!,b:ids[j]!,predicate:'TENSION'}));
const fixtures:Fixture[]=[
 {id:'K1_ALIGN_GROUP_CONSTRAINT',raw:'Speed, quality, and rest are pairwise compatible: any two can coexist. Trying to maximize all three at once makes the plan impossible to sustain.',nodes:[{id:'SPEED',text:'speed'},{id:'QUALITY',text:'quality'},{id:'REST',text:'rest'}],pairs:allAlign(['SPEED','QUALITY','REST']),higher:'COLLECTIVE_CONSTRAINT',members:['SPEED','QUALITY','REST'],evidenceQuote:'Trying to maximize all three at once makes the plan impossible to sustain.',collisionGroup:'A'},
 {id:'K2_ALIGN_GROUP_SYNERGY',raw:'Speed, quality, and rest are pairwise compatible: any two can coexist. When all three are held together, they reinforce one another and make the plan viable.',nodes:[{id:'SPEED',text:'speed'},{id:'QUALITY',text:'quality'},{id:'REST',text:'rest'}],pairs:allAlign(['SPEED','QUALITY','REST']),higher:'COLLECTIVE_SYNERGY',members:['SPEED','QUALITY','REST'],evidenceQuote:'When all three are held together, they reinforce one another and make the plan viable.',collisionGroup:'A'},
 {id:'K3_TENSION_GROUP_CONSTRAINT',raw:'Each pair among ambition, loyalty, and rest pulls against the other. When all three are active together, the system locks into a deadlock.',nodes:[{id:'AMBITION',text:'ambition'},{id:'LOYALTY',text:'loyalty'},{id:'REST',text:'rest'}],pairs:allTension(['AMBITION','LOYALTY','REST']),higher:'COLLECTIVE_CONSTRAINT',members:['AMBITION','LOYALTY','REST'],evidenceQuote:'When all three are active together, the system locks into a deadlock.',collisionGroup:'B'},
 {id:'K4_TENSION_GROUP_SYNERGY',raw:'Each pair among ambition, loyalty, and rest pulls against the other. Yet when all three are held together consciously, the three-way tension stabilizes the decision rather than deadlocking it.',nodes:[{id:'AMBITION',text:'ambition'},{id:'LOYALTY',text:'loyalty'},{id:'REST',text:'rest'}],pairs:allTension(['AMBITION','LOYALTY','REST']),higher:'COLLECTIVE_SYNERGY',members:['AMBITION','LOYALTY','REST'],evidenceQuote:'Yet when all three are held together consciously, the three-way tension stabilizes the decision rather than deadlocking it.',collisionGroup:'B'},
 {id:'K5_PAIRWISE_ONLY',raw:'Ambition and rest pull against each other. Loyalty is present too, but I have not described any three-way effect involving all of them.',nodes:[{id:'AMBITION',text:'ambition'},{id:'REST',text:'rest'},{id:'LOYALTY',text:'loyalty'}],pairs:[{a:'AMBITION',b:'REST',predicate:'TENSION'},{a:'AMBITION',b:'LOYALTY',predicate:'NONE'},{a:'REST',b:'LOYALTY',predicate:'NONE'}],higher:'NONE',members:[],evidenceQuote:null},
 {id:'K6_COOCCURRENCE_ONLY',raw:'I am thinking about money, belonging, and creative freedom today. I have not said that the three form a single configuration.',nodes:[{id:'MONEY',text:'money'},{id:'BELONGING',text:'belonging'},{id:'FREEDOM',text:'creative freedom'}],pairs:[{a:'MONEY',b:'BELONGING',predicate:'NONE'},{a:'MONEY',b:'FREEDOM',predicate:'NONE'},{a:'BELONGING',b:'FREEDOM',predicate:'NONE'}],higher:'NONE',members:[],evidenceQuote:null},
];
const MODEL='claude-sonnet-4-6',REPEATS=2;const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const pairSignature=(f:Fixture)=>f.pairs.map(e=>[...([e.a,e.b].sort()),e.predicate].join(':')).sort().join('|');
const collisionRows=['A','B'].map(g=>{const fsx=fixtures.filter(f=>f.collisionGroup===g);return{group:g,fixtureIds:fsx.map(f=>f.id),samePairwiseSignature:new Set(fsx.map(pairSignature)).size===1,higherKinds:fsx.map(f=>f.higher),pairwiseCanDiscriminate:new Set(fsx.map(pairSignature)).size>1};});
const system=`Offline higher-order relational research. Decide whether MEMBER LANGUAGE explicitly describes a non-pairwise effect that belongs to THREE OR MORE listed nodes as a group. Return JSON only {"kind":"COLLECTIVE_CONSTRAINT"|"COLLECTIVE_SYNERGY"|"NONE","memberIds":string[],"quote":string|null}. COLLECTIVE_CONSTRAINT means the group together creates a limitation/deadlock/overconstraint not attributable to one pair alone. COLLECTIVE_SYNERGY means the group together creates a stabilizing/enabling/emergent effect not attributable to one pair alone. Pairwise tension/alignment, topic co-occurrence, or three nodes merely being mentioned is not enough. quote must be an exact contiguous span from MEMBER LANGUAGE that explicitly supports the all-members group effect. For NONE use [] and null.`;
function call(f:Fixture):Promise<string>{const user=`MEMBER LANGUAGE:\n${f.raw}\nNODES:\n${f.nodes.map(n=>`${n.id}: ${n.text}`).join('\n')}\nPAIRWISE RELATIONS ALREADY KNOWN:\n${f.pairs.map(e=>`${e.a} ${e.predicate} ${e.b}`).join('\n')}`;return new Promise((resolve,reject)=>{const p=spawn('claude',['-p','--model',MODEL,'--effort','low','--system-prompt',system,'--restricted','--tools','','--output-format','text',user],{stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{p.kill('SIGKILL');reject(new Error('timeout'));},90000);p.stdout.setEncoding('utf8');p.stderr.setEncoding('utf8');p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{clearTimeout(timer);reject(e)});p.on('close',code=>{clearTimeout(timer);if(code!==0)reject(new Error(`claude:${code}:${err.slice(0,200)}`));else resolve(out.trim());});p.stdin.end();});}
const clean=(s:string)=>s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
const norm=(s:string)=>s.replace(/[“”]/g,'"').replace(/[’]/g,"'").replace(/\s+/g,' ').trim().toLowerCase();
function parse(s:string){return JSON.parse(clean(s)) as {kind:Higher;memberIds:string[];quote:string|null};}
function gate(f:Fixture,x:any){if(x.kind==='NONE')return{kind:'NONE' as Higher,memberIds:[] as string[],admitted:false,reason:'MODEL_NONE'};const valid=new Set(f.nodes.map(n=>n.id));const ids=[...(x.memberIds??[])];const idsOk=ids.length>=3&&new Set(ids).size===ids.length&&ids.every((id:string)=>valid.has(id));const quoteOk=typeof x.quote==='string'&&norm(f.raw).includes(norm(x.quote));if(!idsOk||!quoteOk)return{kind:'NONE' as Higher,memberIds:[] as string[],admitted:false,reason:!idsOk?'INVALID_MEMBERS':'QUOTE_NOT_EXACT'};return{kind:x.kind as Higher,memberIds:ids.sort(),admitted:true,reason:'EXACT_HIGHER_ORDER_EVIDENCE'};}
function correct(f:Fixture,g:any){if(f.higher==='NONE')return g.kind==='NONE'&&!g.admitted;if(g.kind!==f.higher||!g.admitted)return false;return f.members.length===g.memberIds.length&&f.members.every(id=>g.memberIds.includes(id));}
async function main(){const rows:any[]=[];for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const raw=await call(f);let x:any={kind:'NONE',memberIds:[],quote:null};let parseError:string|null=null;try{x=parse(raw)}catch(e){parseError=e instanceof Error?e.message:String(e)}const gated=gate(f,x);rows.push({fixture:f.id,run,rawHash:sha(raw),proposal:{kind:x.kind,memberIds:x.memberIds??[]},gated,expected:{kind:f.higher,members:f.members},correct:correct(f,gated),parseError});}
const byFixture=Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{runs:rs.length,correct:rs.filter(r=>r.correct).length,predictions:rs.map(r=>r.gated)}]}));const positives=rows.filter(r=>r.expected.kind!=='NONE'),negatives=rows.filter(r=>r.expected.kind==='NONE');const out={schema:'RELATIONAL_GEOMETRY_H4A_HIGHER_ORDER_V1',authority:'offline research only',inference:{provider:'anthropic',model:MODEL,path:'local Claude CLI restricted/no-tools',effort:'low'},hypothesis:'Some 3+ node configurations carry group-level information that collides under identical pairwise graph representations.',collisionTest:{groups:collisionRows,distinctHigherOrderCases:4,pairwiseDistinguishable:collisionRows.filter(r=>r.pairwiseCanDiscriminate).length,higherOrderDistinguishable:4},acquisition:{summary:{runs:rows.length,correct:rows.filter(r=>r.correct).length,truePositive:positives.filter(r=>r.correct).length,truePositiveTotal:positives.length,trueNegative:negatives.filter(r=>r.correct).length,trueNegativeTotal:negatives.length,falsePositive:negatives.filter(r=>!r.correct).length},byFixture,rows}};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H4A_HIGHER_ORDER_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({collisionTest:out.collisionTest,acquisition:out.acquisition.summary,byFixture},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
