import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

type State='NONE'|'ALIGNMENT'|'TENSION';
type Op='EMERGES'|'DISSOLVES'|'TRANSFORMS'|'RETURNS_TO'|'PERSISTS'|'AMBIGUOUS';
type Fixture={id:string;states:State[];expectedOrdered:{operator:Op;fromState:State|null;toState:State|null};expectedUnordered:Op};
const fixtures:Fixture[]=[
 {id:'T1_EMERGES',states:['NONE','TENSION'],expectedOrdered:{operator:'EMERGES',fromState:'NONE',toState:'TENSION'},expectedUnordered:'AMBIGUOUS'},
 {id:'T2_DISSOLVES',states:['TENSION','NONE'],expectedOrdered:{operator:'DISSOLVES',fromState:'TENSION',toState:'NONE'},expectedUnordered:'AMBIGUOUS'},
 {id:'T3_ALIGN_TO_TENSION',states:['ALIGNMENT','TENSION'],expectedOrdered:{operator:'TRANSFORMS',fromState:'ALIGNMENT',toState:'TENSION'},expectedUnordered:'AMBIGUOUS'},
 {id:'T4_TENSION_TO_ALIGN',states:['TENSION','ALIGNMENT'],expectedOrdered:{operator:'TRANSFORMS',fromState:'TENSION',toState:'ALIGNMENT'},expectedUnordered:'AMBIGUOUS'},
 {id:'T5_RETURN',states:['TENSION','NONE','TENSION'],expectedOrdered:{operator:'RETURNS_TO',fromState:'TENSION',toState:'TENSION'},expectedUnordered:'AMBIGUOUS'},
 {id:'T6_PERSISTS',states:['ALIGNMENT','ALIGNMENT','ALIGNMENT'],expectedOrdered:{operator:'PERSISTS',fromState:'ALIGNMENT',toState:'ALIGNMENT'},expectedUnordered:'PERSISTS'},
];
const MODEL='claude-sonnet-4-6',REPEATS=2;const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const system=`Offline temporal-geometry research over already-admitted relation states. Return JSON only {"operator":"EMERGES"|"DISSOLVES"|"TRANSFORMS"|"RETURNS_TO"|"PERSISTS"|"AMBIGUOUS","fromState":"NONE"|"ALIGNMENT"|"TENSION"|null,"toState":"NONE"|"ALIGNMENT"|"TENSION"|null}. Use EMERGES when NONE becomes a relation; DISSOLVES when a relation becomes NONE; TRANSFORMS when one non-NONE configuration becomes another; RETURNS_TO when a prior non-NONE state reappears after an intervening different state; PERSISTS when the same state remains throughout. If observations lack temporal order and more than one directional history fits, output AMBIGUOUS with null states. Do not invent temporal order.`;
function runClaude(user:string):Promise<string>{return new Promise((resolve,reject)=>{const p=spawn('claude',['-p','--model',MODEL,'--effort','low','--system-prompt',system,'--restricted','--tools','','--output-format','text',user],{stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{p.kill('SIGKILL');reject(new Error('timeout'));},90000);p.stdout.setEncoding('utf8');p.stderr.setEncoding('utf8');p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{clearTimeout(timer);reject(e)});p.on('close',code=>{clearTimeout(timer);if(code!==0)reject(new Error(`claude:${code}:${err.slice(0,200)}`));else resolve(out.trim());});p.stdin.end();});}
const clean=(s:string)=>s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
function parse(s:string){return JSON.parse(clean(s)) as {operator:Op;fromState:State|null;toState:State|null};}
function orderedPrompt(f:Fixture){return `ORDERED OBSERVATIONS:\n${f.states.map((s,i)=>`t${i+1}: ${s}`).join('\n')}`;}
function unorderedPrompt(f:Fixture,run:number){const states=[...f.states];if(run%2===0)states.reverse();return `UNORDERED OBSERVATIONS (no timestamps, sequence unknown):\n${states.map((s,i)=>`observation_${String.fromCharCode(65+i)}: ${s}`).join('\n')}`;}
function orderedCorrect(f:Fixture,x:any){const e=f.expectedOrdered;return x.operator===e.operator&&x.fromState===e.fromState&&x.toState===e.toState;}
function unorderedCorrect(f:Fixture,x:any){if(x.operator!==f.expectedUnordered)return false;if(f.expectedUnordered==='AMBIGUOUS')return x.fromState==null&&x.toState==null;return x.fromState==='ALIGNMENT'&&x.toState==='ALIGNMENT';}
async function main(){const rows:any[]=[];for(const f of fixtures)for(let run=1;run<=REPEATS;run++){const [oRaw,uRaw]=await Promise.all([runClaude(orderedPrompt(f)),runClaude(unorderedPrompt(f,run))]);let o:any={operator:'AMBIGUOUS',fromState:null,toState:null},u:any={operator:'AMBIGUOUS',fromState:null,toState:null};let oe=null,ue=null;try{o=parse(oRaw)}catch(e){oe=e instanceof Error?e.message:String(e)}try{u=parse(uRaw)}catch(e){ue=e instanceof Error?e.message:String(e)}rows.push({fixture:f.id,run,ordered:{hash:sha(oRaw),prediction:o,expected:f.expectedOrdered,correct:orderedCorrect(f,o),parseError:oe},unordered:{hash:sha(uRaw),prediction:u,expectedOperator:f.expectedUnordered,correct:unorderedCorrect(f,u),parseError:ue}});}
const byFixture=Object.fromEntries(fixtures.map(f=>{const rs=rows.filter(r=>r.fixture===f.id);return[f.id,{runs:rs.length,orderedCorrect:rs.filter(r=>r.ordered.correct).length,unorderedCorrect:rs.filter(r=>r.unordered.correct).length,orderedPredictions:rs.map(r=>r.ordered.prediction),unorderedPredictions:rs.map(r=>r.unordered.prediction)}]}));const directional=rows.filter(r=>r.fixture!=='T6_PERSISTS');const out={schema:'RELATIONAL_GEOMETRY_H5A_TEMPORAL_ORDER_V1',authority:'offline research only',inference:{provider:'anthropic',model:MODEL,path:'parallel local Claude CLI restricted/no-tools',effort:'low'},hypothesis:'Temporal order carries transition information unavailable in an unordered multiset of the same relation states.',summary:{runs:rows.length,orderedCorrect:rows.filter(r=>r.ordered.correct).length,unorderedCorrect:rows.filter(r=>r.unordered.correct).length,directionalOrderedCorrect:directional.filter(r=>r.ordered.correct).length,directionalTotal:directional.length,directionalUnorderedAbstainCorrect:directional.filter(r=>r.unordered.correct).length,persistenceOrdered:rows.filter(r=>r.fixture==='T6_PERSISTS'&&r.ordered.correct).length,persistenceUnordered:rows.filter(r=>r.fixture==='T6_PERSISTS'&&r.unordered.correct).length},byFixture,rows};fs.writeFileSync(path.join(process.cwd(),'docs/programme/evidence/relational-geometry-integration/H5A_TEMPORAL_ORDER_2026-09-16.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({summary:out.summary,byFixture},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
