/**
 * Sanitize MAIA speech input before it reaches a synthesis engine.
 *
 * This is intentionally a PRESENTATION sanitizer, not a meaning rewriter.
 * It removes artifacts that should never be spoken aloud (fenced code,
 * metadata, markdown formatting and URLs) while preserving ordinary prose,
 * including braces, brackets and parentheses.
 */

function isStandaloneJson(value: string): boolean {
  const trimmed = value.trim();
  if (!trimmed) return false;

  const looksLikeObject = trimmed.startsWith('{') && trimmed.endsWith('}');
  const looksLikeArray = trimmed.startsWith('[') && trimmed.endsWith(']');
  if (!looksLikeObject && !looksLikeArray) return false;

  try {
    const parsed = JSON.parse(trimmed);
    return parsed !== null && typeof parsed === 'object';
  } catch {
    return false;
  }
}

function stripStandaloneJsonLines(input: string): string {
  if (isStandaloneJson(input)) return '';

  return input
    .split('\n')
    .filter((line) => !isStandaloneJson(line))
    .join('\n');
}

/**
 * Remove non-speakable presentation syntax while preserving semantic prose.
 */
export function sanitizeForSpeech(input: string): string {
  if (!input) return '';

  let text = input;

  // Internal metadata must never become audible.
  text = text.replace(/---SOUL_METADATA---[\s\S]*?---END_METADATA---/gi, ' ');

  // Code blocks are implementation artifacts, not conversational speech.
  text = text.replace(/```[\s\S]*?```/g, ' ');
  text = text.replace(/~~~[\s\S]*?~~~/g, ' ');

  // Remove any orphan fence lines left by malformed/incomplete markdown.
  text = text.replace(/^\s*(?:```|~~~)[^\n]*$/gm, ' ');

  // Whole/standalone JSON artifacts only. Do NOT delete arbitrary {...} or [...]
  // because those forms can be legitimate human prose.
  text = stripStandaloneJsonLines(text);

  // Markdown images/links: retain the human-readable label, drop the target URL.
  text = text.replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1');
  text = text.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1');

  // Raw URLs are not useful spoken character-by-character.
  text = text.replace(/https?:\/\/\S+/gi, ' ');

  // Inline code: preserve the words, remove only the presentation delimiters.
  text = text.replace(/`([^`\n]+)`/g, '$1');

  // Common markdown block syntax.
  text = text.replace(/^\s{0,3}#{1,6}\s+/gm, '');
  text = text.replace(/^\s{0,3}>\s?/gm, '');
  text = text.replace(/^\s*(?:[-+*]\s+|\d+[.)]\s+)/gm, '');

  // Common emphasis markers. Preserve their content.
  text = text.replace(/\*\*([^*\n]+)\*\*/g, '$1');
  text = text.replace(/__([^_\n]+)__/g, '$1');
  text = text.replace(/~~([^~\n]+)~~/g, '$1');
  text = text.replace(/(^|[\s(])\*([^*\n]+)\*(?=$|[\s).,!?;:])/g, '$1$2');
  text = text.replace(/(^|[\s(])_([^_\n]+)_(?=$|[\s).,!?;:])/g, '$1$2');

  // Plain-text HTML/XML tags are presentation markup. SSML is handled by the
  // dedicated sanitizer below so allowed synthesis tags can survive there.
  text = text.replace(/<[^>]+>/g, ' ');

  // Normalize spacing after removing presentation artifacts.
  return text.replace(/\s+/g, ' ').trim();
}

const ALLOWED_SSML_TAG = /^<\/?(?:speak|prosody|emphasis)\b[^>]*>$|^<break\b[^>]*\/>$/i;

/**
 * Sanitize text nodes inside SSML while preserving only the small SSML subset
 * generated by MAIA's TTS adapter. This closes the route-level escape where
 * unsanitized source text was embedded in SSML and then preferred by Kokoro.
 */
export function sanitizeSsmlForSpeech(input: string): string {
  if (!input) return '';

  // Remove fenced code before tokenizing tags so a fence cannot survive merely
  // because its body contains escaped markup or line breaks.
  const withoutFences = input
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/~~~[\s\S]*?~~~/g, ' ');

  const parts = withoutFences.split(/(<[^>]+>)/g);
  const sanitized = parts
    .map((part) => {
      if (!part) return '';
      if (part.startsWith('<')) {
        return ALLOWED_SSML_TAG.test(part) ? part : '';
      }
      return sanitizeForSpeech(part);
    })
    .join('');

  return sanitized.trim();
}

/**
 * Provider-boundary helper: plain text and SSML must both be sanitized before
 * synthesis. Keeping this decision here prevents callers from bypassing the
 * invariant by choosing a different input representation.
 */
export function sanitizeSpeechInput(input: string): string {
  return /<speak\b/i.test(input)
    ? sanitizeSsmlForSpeech(input)
    : sanitizeForSpeech(input);
}
