#!/usr/bin/env bash
set -euo pipefail

# Capture the canonical schema baseline from the PRODUCTION database.
#
# This is the only sanctioned way to produce database/baseline/*. It reads; it
# never writes to the source. Run it where maia_consciousness lives (minisforum),
# with no client on the host:
#
#   DB_URL="$(docker exec maia-sovereign printenv DATABASE_URL)"
#   docker run --rm --network maia-sovereign_maia-internal \
#     --user "$(id -u):$(id -g)" -v "$PWD:/repo" -w /repo \
#     -e DATABASE_URL="$DB_URL" \
#     pgvector/pgvector:pg16 bash scripts/capture-baseline.sh
#
# WHY THE SOURCE MATTERS. A baseline taken from a development database looks
# right and is wrong: it carries tables belonging to unmerged work and omits
# tables production actually has. A disaster-recovery rebuild from it produces a
# schema that never existed, and the empty-database gate then passes because the
# snapshot pre-contains what the migration tree fails to create. Capture from
# production, or do not capture.
#
# THE CUT LINE IS A LEDGER FACT. It is read from the source database's own
# schema_migrations, never from the filesystem. A migration is subsumed because
# production recorded it as applied — not because a file of that name exists.

: "${DATABASE_URL:?DATABASE_URL must be set to the production database}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/database/baseline"
STEM="${BASELINE_STEM:-0001_baseline_$(date -u +%Y-%m-%d)}"
SCHEMA_OUT="$OUT_DIR/$STEM.sql"
MANIFEST_OUT="$OUT_DIR/$STEM.manifest"
mkdir -p "$OUT_DIR"

echo "🔎 Source database:"
psql "$DATABASE_URL" -c \
  "SELECT current_database() AS db, inet_server_addr() AS host, current_user AS user;"

db="$(psql "$DATABASE_URL" -tAc 'SELECT current_database();' | tr -d '[:space:]')"
if [ "$db" != "maia_consciousness" ]; then
  echo "❌ Refusing: source database is '$db', not 'maia_consciousness'."
  echo "   A baseline captured from anything else is not canonical."
  echo "   Override deliberately with BASELINE_ALLOW_ANY_SOURCE=1 if you mean it."
  [ "${BASELINE_ALLOW_ANY_SOURCE:-0}" = "1" ] || exit 1
fi

echo "📝 Recording the cut line from schema_migrations (ledger, not filesystem)..."
{
  echo "# Migration ledger subsumed by $STEM.sql."
  echo "#"
  echo "# Generated by scripts/capture-baseline.sh from the SOURCE DATABASE'S OWN"
  echo "# schema_migrations table. Nothing here is inferred from the filesystem: a"
  echo "# migration appears only because production recorded it as applied."
  echo "#"
  echo "# FILENAMES ONLY, BY DESIGN. Checksums are computed from disk at stamp time, so"
  echo "# a migration edited after capture still trips the runner's tamper check. A"
  echo "# filename with no file on disk is stamped with a NULL checksum — production"
  echo "# records that it ran, and its source is no longer in the repository. That is"
  echo "# preserved as a ledger fact, never reconstructed and never invented."
  echo "#"
  echo "# Captured: $(date -u +%Y-%m-%dT%H:%M:%SZ) from $db"
  echo "# Do not hand-edit."
  psql "$DATABASE_URL" -tAc \
    "SELECT filename FROM schema_migrations ORDER BY filename;" | sed '/^[[:space:]]*$/d'
} > "$MANIFEST_OUT"

echo "📦 Dumping schema (no data, no owners, no privileges)..."
{
  echo "-- MAIA canonical schema baseline"
  echo "--"
  echo "-- SOURCE OF TRUTH: $db on minisforum (the production database),"
  echo "-- captured $(date -u +%Y-%m-%d) by scripts/capture-baseline.sh via"
  echo "--   pg_dump --schema-only --no-owner --no-privileges --no-comments --quote-all-identifiers"
  echo "--"
  echo "-- This is a PRESENT-DAY SNAPSHOT OF THE PRODUCTION SCHEMA. It is not recovered"
  echo "-- historical DDL, it is not a migration, and it makes no claim about how the"
  echo "-- schema came to be. See docs/ops/DB_EMPTY_BOOTSTRAP_01_DIAGNOSIS_2026-09-01.md."
  echo "--"
  echo "-- It therefore contains exactly what production contains — no more. Tables"
  echo "-- belonging to unmerged work are ABSENT by construction, and a migration that"
  echo "-- depends on one will fail the empty-database gate until its genesis migration"
  echo "-- lands on trunk. That failure is the gate working."
  echo "--"
  echo "-- Contains no member data. Enforced by scripts/verify-bootstrap.sh."
  # Recent pg_dump wraps the dump in \restrict / \unrestrict psql meta-commands.
  # They are not SQL: any loader that is not psql chokes on them, and
  # scripts/verify-bootstrap.sh rejects a baseline that carries them. Stripping
  # them removes no schema.
  pg_dump "$DATABASE_URL" --schema-only --no-owner --no-privileges \
    --no-comments --quote-all-identifiers \
    | sed -E '/^\\(restrict|unrestrict) /d'
} > "$SCHEMA_OUT"

echo
echo "✅ Baseline captured"
echo "   schema:   $SCHEMA_OUT ($(grep -c '^CREATE TABLE' "$SCHEMA_OUT") tables)"
echo "   manifest: $MANIFEST_OUT ($(grep -cv '^#' "$MANIFEST_OUT") ledger entries)"
echo
echo "Next: commit both, then verify with  npm run db:verify-bootstrap"
