#!/usr/bin/env bash
set -euo pipefail

# Capture the canonical schema baseline.
#
# Run this where the known-good database lives (production: minisforum,
# maia-postgres / maia_consciousness). It reads only; it never writes to the
# source database.
#
# It produces two artifacts, both committed to the repository:
#
#   database/baseline/schema.sql   schema-only dump of the known-good database
#   database/baseline/CUT_LINE     the migration filenames that dump subsumes
#
# The baseline is a PRESENT-DAY RECONSTRUCTION of the schema. It is not a
# historical migration and it does not claim historical provenance. Everything
# recorded in CUT_LINE is subsumed by schema.sql; everything after it runs
# forward through database/migrations/ as normal.
#
# Usage:
#   DATABASE_URL=postgres://... scripts/capture-baseline.sh
#
#   # on minisforum:
#   docker exec maia-postgres sh -c \
#     'pg_dump --schema-only --no-owner --no-privileges -U soullab maia_consciousness'

: "${DATABASE_URL:?DATABASE_URL must be set to the known-good database}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/database/baseline"
SCHEMA_OUT="$OUT_DIR/schema.sql"
CUT_LINE_OUT="$OUT_DIR/CUT_LINE"

mkdir -p "$OUT_DIR"

echo "🔎 Source database:"
psql "$DATABASE_URL" -c \
  "SELECT current_database() AS db, inet_server_addr() AS host, current_user AS user;"

# The cut line is exactly what the source database says it has applied.
# Nothing is inferred from the filesystem: if a migration is not recorded as
# applied in the source, the baseline does not claim to subsume it.
echo "📝 Recording cut line from schema_migrations..."
{
  echo "# Migrations subsumed by database/baseline/schema.sql."
  echo "# Generated by scripts/capture-baseline.sh — do not hand-edit."
  echo "# Captured: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "#"
  echo "# These filenames are stamped into schema_migrations during bootstrap so"
  echo "# the runner does not re-apply them and the schema gate is satisfied."
  psql "$DATABASE_URL" -tAc \
    "SELECT filename FROM schema_migrations ORDER BY filename;"
} > "$CUT_LINE_OUT"

subsumed="$(grep -cv '^#' "$CUT_LINE_OUT" || true)"

echo "📦 Dumping schema (no data, no owners, no privileges)..."
pg_dump "$DATABASE_URL" \
  --schema-only \
  --no-owner \
  --no-privileges \
  --no-comments \
  --quote-all-identifiers \
  > "$SCHEMA_OUT"

# schema_migrations is recreated and stamped by the bootstrap phase; keeping the
# dump's own copy is harmless (CREATE TABLE only, no rows in a schema-only dump).

echo
echo "✅ Baseline captured"
echo "   schema:   $SCHEMA_OUT ($(wc -l < "$SCHEMA_OUT") lines)"
echo "   cut line: $CUT_LINE_OUT ($subsumed migrations subsumed)"
echo
echo "Next: commit both files, then verify with"
echo "   scripts/test-empty-db-reconstruction.sh"
