#!/usr/bin/env bash
# Scaffold an Environmental Field Study sitting.
#
#   bash scripts/field-study-scaffold.sh now-what
#   bash scripts/field-study-scaffold.sh now-what --verify
#
# Method: docs/specs/developmental-environment/FIELD_STUDY_METHOD_CANDIDATE_2026-07-29.md
#
# The Observation Declaration is immutable for the sitting. --verify re-fingerprints the
# build and reports whether it changed underneath the study. Written for bash 3.2 (macOS).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

FIELD="${1:-}"
MODE="${2:-scaffold}"

if [ -z "$FIELD" ]; then
  echo "usage: bash scripts/field-study-scaffold.sh <field-slug> [--verify]" >&2
  echo "  e.g. bash scripts/field-study-scaffold.sh now-what" >&2
  exit 2
fi

DATE="$(date +%F)"
STUDY_DIR="docs/field-studies/${FIELD}/${DATE}"
DECL="${STUDY_DIR}/OBSERVATION_DECLARATION.md"

# ---------------------------------------------------------------------------
# Two independent integrity declarations
#
#   1. OBSERVED BUILD  — did the product under study change during the sitting?
#   2. STUDY INSTRUMENT — did the method or harness change during the sitting?
#
# These are separate problems. The product can hold still while the method moves
# underneath it. Excluding study output prevents self-contamination; it does not
# detect someone editing SKILL.md or this script halfway through a sitting.
# ---------------------------------------------------------------------------

# NARROW BY RULING. Only the designated study-output directory is excluded, because it is
# generated by the observation process itself. Do NOT generalize this to documentation,
# reports, temp files, or "known harmless" paths — a curated exclusion list turns the
# fingerprint from a detector of drift into an opinion about drift.
EXCLUDE_RULE='docs/field-studies/'
EXCLUDE_WHY='generated by the observation process itself; scaffolding a sitting must not register as drift in the build the sitting observes'

# The method and its harness. Editing any of these mid-sitting invalidates the instrument.
INSTRUMENT_FILES="scripts/field-study-scaffold.sh
.claude/skills/field-study/SKILL.md
docs/specs/developmental-environment/FIELD_STUDY_METHOD_CANDIDATE_2026-07-29.md"

build_fingerprint() {
  local sha branch dirty tree status
  sha="$(git rev-parse --short HEAD)"
  branch="$(git rev-parse --abbrev-ref HEAD)"
  status="$(git status --porcelain | grep -v "$EXCLUDE_RULE" || true)"
  dirty="$(printf '%s\n' "$status" | grep -c . || true)"
  tree="$(printf '%s\n' "$status" | shasum | cut -c1-12)"
  echo "${sha}|${branch}|${dirty}|${tree}"
}

# Content hash, not git state — an uncommitted instrument is still a fixed instrument
# for the duration of a sitting, and must be detectable if it moves.
instrument_fingerprint() {
  printf '%s\n' "$INSTRUMENT_FILES" | while IFS= read -r f; do
    [ -n "$f" ] && shasum "$f" 2>/dev/null || echo "MISSING $f"
  done | shasum | cut -c1-12
}

instrument_rev() {
  local rev
  rev="$(printf '%s\n' "$INSTRUMENT_FILES" | tr '\n' ' ' | xargs git log -1 --format=%h -- 2>/dev/null || true)"
  [ -n "$rev" ] || rev="none"
  if printf '%s\n' "$INSTRUMENT_FILES" | while IFS= read -r f; do
       [ -n "$f" ] && git status --porcelain -- "$f"; done | grep -q .; then
    echo "${rev} (UNCOMMITTED — instrument is not yet fixed by a commit)"
  else
    echo "${rev}"
  fi
}

FP="$(build_fingerprint)"
FP_SHA="$(echo "$FP" | cut -d'|' -f1)"
FP_BRANCH="$(echo "$FP" | cut -d'|' -f2)"
FP_DIRTY="$(echo "$FP" | cut -d'|' -f3)"
FP_TREE="$(echo "$FP" | cut -d'|' -f4)"
IFP="$(instrument_fingerprint)"
IREV="$(instrument_rev)"

# ---------------------------------------------------------------------------
# --verify : did the build change underneath the sitting?
# ---------------------------------------------------------------------------
if [ "$MODE" = "--verify" ]; then
  if [ ! -f "$DECL" ]; then
    echo "no declaration at ${DECL} — nothing to verify" >&2
    exit 1
  fi
  DECLARED_SHA="$(grep '^- \*\*Commit:\*\*' "$DECL" | sed 's/.*`\(.*\)`.*/\1/' || true)"
  DECLARED_TREE="$(grep '^- \*\*Working-tree fingerprint:\*\*' "$DECL" | sed 's/.*`\(.*\)`.*/\1/' || true)"
  DECLARED_INST="$(grep '^- \*\*Instrument fingerprint:\*\*' "$DECL" | sed 's/.*`\(.*\)`.*/\1/' || true)"

  BUILD_OK=1; INST_OK=1
  [ "$DECLARED_SHA" = "$FP_SHA" ] && [ "$DECLARED_TREE" = "$FP_TREE" ] || BUILD_OK=0
  [ "$DECLARED_INST" = "$IFP" ] || INST_OK=0

  echo "=== Close report — ${FIELD} ${DATE} ==============================="
  echo
  echo "1. OBSERVED BUILD   (the product under study)"
  echo "   declared : ${DECLARED_SHA} / tree ${DECLARED_TREE}"
  echo "   current  : ${FP_SHA} / tree ${FP_TREE}"
  if [ "$BUILD_OK" = "1" ]; then
    echo "   INTACT — every observation belongs to the declared build."
  else
    echo "   DIVERGED — the product changed during the sitting."
  fi
  echo
  echo "2. STUDY INSTRUMENT (the method and harness)"
  echo "   declared : ${DECLARED_INST}"
  echo "   current  : ${IFP}"
  if [ "$INST_OK" = "1" ]; then
    echo "   INTACT — the method did not move under the sitting."
  else
    echo "   DIVERGED — the method or harness was edited mid-sitting."
  fi
  echo
  echo "Exclusion rule in force: '${EXCLUDE_RULE}'"
  echo "=================================================================="

  if [ "$BUILD_OK" = "1" ] && [ "$INST_OK" = "1" ]; then
    exit 0
  fi

  echo
  echo "Divergence is a REPORTABLE CONDITION, not a failure. Record both lines above in"
  echo "the Method Integrity page. Observations from before and after a divergence belong"
  echo "to different builds — or to different methods — and may not be compared."
  echo "Prefer re-walking to silently mixing evidence."

  if [ "$BUILD_OK" = "0" ] && [ "$INST_OK" = "0" ]; then exit 5; fi
  if [ "$BUILD_OK" = "0" ]; then exit 3; fi
  exit 4
fi

# ---------------------------------------------------------------------------
# scaffold
# ---------------------------------------------------------------------------
if [ -d "$STUDY_DIR" ]; then
  echo "study already scaffolded: ${STUDY_DIR}" >&2
  echo "(a sitting is scoped to one build; use --verify to check it is still intact)" >&2
  exit 1
fi

mkdir -p "$STUDY_DIR"

cat > "$DECL" <<EOF
# Observation Declaration — ${FIELD} — ${DATE}

**Immutable for this sitting.** Every observation in this study belongs to the build below.
No mixed evidence. No switching halfway through. Verify with:

\`\`\`bash
bash scripts/field-study-scaffold.sh ${FIELD} --verify
\`\`\`

## Implementation under study

- **Field:** ${FIELD}
- **Commit:** \`${FP_SHA}\`
- **Branch:** \`${FP_BRANCH}\`
- **Working-tree fingerprint:** \`${FP_TREE}\` (${FP_DIRTY} uncommitted paths)
- **Environment:** <!-- local trunk worktree | local dirty tree | production soullab.life -->
- **Date:** ${DATE}

## Study instrument (declared separately from the observed build)

The product under study can hold still while the method moves underneath it. Both are
declared; both are verified at close.

- **Instrument fingerprint:** \`${IFP}\`
- **Instrument last commit:** ${IREV}
- **Instrument files:**
$(printf '%s\n' "$INSTRUMENT_FILES" | sed 's|^|  - `|; s|$|`|')

## Fingerprint algorithm and exclusions

Recorded so that a later reader can reproduce or challenge it.

- **Observed build:** \`git rev-parse --short HEAD\` + \`git rev-parse --abbrev-ref HEAD\` +
  \`git status --porcelain\` filtered through the exclusion rule below, hashed with
  \`shasum\`, truncated to 12 chars.
- **Study instrument:** \`shasum\` of each instrument file, hashed again, truncated to 12 chars.
  Content-based, not git-based — an uncommitted instrument is still fixed for the sitting.
- **Exclusion rule (the ONLY one):** \`${EXCLUDE_RULE}\`
- **Why excluded:** ${EXCLUDE_WHY}

**Narrowness is load-bearing.** No other path may be excluded — not documentation, not
reports, not temporary files, not "known harmless" changes. A curated exclusion list turns
the fingerprint from a detector of drift into an opinion about drift.

## Evidence boundary

- **Walked** (observed directly in a running application):
  - <!-- route — viewport(s) — member state -->
- **Read** (implementation only):
  - <!-- route — why it could not be walked -->
- **Unavailable** (cannot currently be verified):
  - <!-- e.g. states requiring an invitation this observer may not mint -->
- **Needs production verification:**
  - <!-- -->

## Known divergence from production

<!-- If the studied build is not what members meet, say exactly how it differs.
     "Fixed on trunk" is not "live in production." -->

## Study ethics declaration

- Member content read: **none** / <!-- named consent basis -->
- Sanctuary content: **categorically excluded**
- Evidence deliberately foregone (and the conclusions left provisional as a result):
  - <!-- -->
EOF

cat > "${STUDY_DIR}/00-method-integrity.md" <<'EOF'
# Method Integrity

*Readers meet the limits of the evidence before they meet the findings.*

Specific and falsifiable — names and counts, not categories. Not "some surfaces were
inferred" but "`/now-what/room` walked at 390px and 1280px; `/now-what/next` read-only —
it requires a participant record created by an invitation this observer may not mint."

## What was directly observed

## What was inferred (and from what)

## What could not be observed

## What assumptions were required

## What founder rulings constrained the study

## Did the build change during the sitting?

<!-- Output of: bash scripts/field-study-scaffold.sh <field> --verify -->
EOF

cat > "${STUDY_DIR}/01-gravity-map.md" <<'EOF'
# Gravity Map

**Produced first, before any narrative.** It asks what the environment is *actually*
organizing around — not what it claims to organize around.

Four gravities measured independently, then compared. **The finding is the disagreement.**

| Surface | Visual | Interaction | Temporal | Relational | Reading |
|---|---|---|---|---|---|
| | | | | | |

- **Visual** — where attention goes (Class A: layout, computed style, screenshot)
- **Interaction** — where actions go (Class A: routes, affordances, what is one gesture away)
- **Temporal** — where the person returns (Class A/B: what persists, what the return path
  resolves to, aggregate route telemetry — **never member content**)
- **Relational** — who becomes central (Class A: whose name appears, whose voice speaks,
  who is addressed)

## Alignments (coherent places)

## Disagreements (structural findings)

<!-- Visual→MAIA while relational should sit with Larry is not a hierarchy problem.
     It is a relational inconsistency, and it is structural. -->
EOF

cat > "${STUDY_DIR}/02-orientation-and-complexity.md" <<'EOF'
# Orientation · Complexity ⟂ Confusion

## Orientation (per state)

Where am I · why am I here · who holds this space · what is the primary relationship offered ·
clearest next action · what competes with it · what must I infer · what persists · who can see
what I do · how do I leave and return.

## Complexity ⟂ Confusion

Two **independent** scores. Target is inhabitable richness, not simplicity.

- **Complexity** — concepts, choices, comparisons, facts to hold
- **Confusion** — meaning, consequence, relationship, direction left to inference

| | Low confusion | High confusion |
|---|---|---|
| **Low complexity** | Clear simplicity | Empty ambiguity |
| **High complexity** | Inhabitable richness | Overwhelm |
EOF

cat > "${STUDY_DIR}/03-transitions.md" <<'EOF'
# Transition Study

The seams, not the destinations.

Invitation → threshold → room → reflection → leaving → returning.

Per seam: what changed · what remained · what *should* have changed · what should *not* have.
EOF

cat > "${STUDY_DIR}/04-learning-ecology.md" <<'EOF'
# Learning Ecology

How learning accumulates through repeated return. Products teach by repetition, not onboarding.

After the 1st, 2nd, 5th, 20th visit: what has become easier · what has become automatic ·
what assumptions has the environment encouraged?

**Honest limit:** the 20th visit cannot be observed — it may not have happened for any
participant. Grounded substitute (Class B): read what the return path *rewards* — what the
system remembers, surfaces on return, and makes easy the second time.

**Ethics limit:** real return behavior is the best evidence and is the instrument most tempted
by member data. Aggregate structural telemetry only. Where member content would answer the
question, say so and stop — log it as *Needs consent*.
EOF

cat > "${STUDY_DIR}/05-inter-field-coupling.md" <<'EOF'
# Inter-field Coupling · What Disappears

## Coupling

Does each place strengthen the others, or are they islands?

## What disappears

Which concerns does the environment successfully dissolve?

What refuses to disappear that should — navigation, software terminology, implementation
seams, unnecessary choices, system state, AI mechanics?
EOF

cat > "${STUDY_DIR}/06-constitutional-consistency.md" <<'EOF'
# Constitutional Consistency (Class E)

Implementation vs. ratified principle. Governance, not experience.

- [ ] MAIA is not the destination
- [ ] Suggestions remain external until adopted
- [ ] Consent is unmistakable
- [ ] The member understands who can see what
- [ ] Authority moves only upward through authored experience
- [ ] Sanctuary boundaries hold
- [ ] No claim in the interface outruns verified state

Each finding cites the canon it tests.
EOF

cat > "${STUDY_DIR}/07-environmental-analogy.md" <<'EOF'
# Environmental Analogy

Two steps, in order. **Never step two alone.** Metaphor after measurement.

## 1. Measurable characteristics

Central gathering point · narrow circulation · hidden rooms · long corridors · repeated
thresholds · isolated workspaces · one dominant focal point · multiple competing focal points.

## 2. Only then

If those characteristics were instantiated physically, what kinds of environments exhibit them?

Name the place, then name the three concrete features that produced the naming.

Is that the place we intended to build?
EOF

cat > "${STUDY_DIR}/08-correction-queue.md" <<'EOF'
# Correction Queue

Objective defects. Class A. **No judgment required — these need repair, not philosophy.**

A broken return path is not a tension. It is a defect.

| # | Finding | File:line | Type | Evidence |
|---|---|---|---|---|
| | | | | |

Types: presentation · language · interaction · information architecture · domain model ·
relational architecture · constitutional conflict
EOF

cat > "${STUDY_DIR}/09-founder-questions.md" <<'EOF'
# Founder Questions

Authentic tradeoffs. Neither side is correct. **Both stated with equal force, then stop.**

No recommendation smuggled in as "obviously we should…". A study that recommends is
quietly legislating.

## Question 1

**Tension:** <!-- X ⟷ Y -->

**The case for X:**

**The case for Y:**

**What evidence would settle it:**

**What cannot be settled by evidence (this is why it is a founder ruling):**
EOF

cat > "${STUDY_DIR}/10-architectural-opportunities.md" <<'EOF'
# Architectural Opportunities

Discoveries that arise from nothing being broken. Not defects. Not tensions.
Convergences.

> The same continuity primitive appears independently in three studios.
> Three teams independently created "return" mechanisms.

These are often the birthplace of a platform's deepest abstractions — which is exactly why
they are dangerous.

**Standing constraint: an architectural opportunity is Category 1 by default** — preserved
direction, held, *not authorized*. It records that something could become a shared
environmental primitive. It does not authorize building one. Collapsing an opportunity into
a build is the inflation drift this project already refuses.

| # | Convergence | Observed in | Instrument that surfaced it | Category |
|---|---|---|---|---|
| | | | | Cat 1 (held) |
EOF

cat > "${STUDY_DIR}/11-emerging-patterns.md" <<'EOF'
# Emerging Patterns

Recurring structures independently observed **across** studies. The bridge between individual
field studies and future constitutional rulings — so that each study does not begin from zero.

```text
Pattern candidate 001
Continuity is strongest when the environment returns people to unfinished work
rather than to a chronological feed.

Observed in:      Now What? · Journal · Author Studio
Surfaced by:      temporal gravity · transition study · learning ecology
Observer:         single / independent
Status:           Candidate
```

## Two epistemic guards

**1. Same instrument ≠ convergent evidence.** A pattern surfaced in three fields by the *same*
instrument may be the shape of the instrument, not of the environments. Record which instrument
surfaced each occurrence. Cross-instrument convergence is strong; single-instrument recurrence
is weak.

**2. Priming contaminates accumulation.** A study run with knowledge of prior pattern candidates
will find them. This is a real tension in the method itself: *accumulation* (don't start from
zero) works against *independence* (don't confirm yourself). Provisional rule — instruments run
blind to the pattern register; only synthesis consults it, and says that it did.
EOF

cat > "${STUDY_DIR}/12-synthesis.md" <<'EOF'
# Synthesis

Written **last**, after every instrument has reported independently.

## Implemented participant journey (not the intended one)

## Implemented practitioner journey

## Ten highest-leverage friction points

## Hidden complexity the system should carry on the person's behalf

## Currently hidden that must be revealed

## Existing strengths not to redesign away

## Three competing grammars

Held **separate**. No premature synthesis — a beautiful but conceptually muddy interface is
the cost of blending them too early.

### A. Calm clarity

### B. Living field

### C. House geography
EOF

echo "Field study scaffolded: ${STUDY_DIR}"
echo
echo "  Observed build    : ${FP_SHA} on ${FP_BRANCH} (${FP_DIRTY} uncommitted paths, excl. ${EXCLUDE_RULE})"
echo "  Study instrument  : ${IFP} — ${IREV}"
echo "  Declaration       : ${DECL}"
echo
echo "Next:"
echo "  1. Complete the Observation Declaration BEFORE walking anything."
echo "  2. Produce 01-gravity-map.md first — before any narrative."
echo "  3. Instruments report independently; write 12-synthesis.md last."
echo "  4. At close: bash scripts/field-study-scaffold.sh ${FIELD} --verify"
