/**
 * DESKTOP-HOUSE-01 — derive Desktop's platform-view path authority from the
 * canonical House registry.
 *
 * ⛔ WHY GENERATED AND NOT HAND-WRITTEN. Desktop's shell is CommonJS and cannot
 * import `lib/navigation/houseDestinations.ts`, so the allow-list has to exist
 * on the Desktop side in some form. The repo has met this exact problem before
 * — the House registry, the native runtime allow-list and the Capacitor
 * keep-list drifted apart until `houseNavDrift.test.ts` pinned them together.
 * This file goes one step further than a checked duplicate: the Desktop
 * manifest is GENERATED from the registry, and the drift test regenerates and
 * compares, so the only way to change what Desktop may open is to change the
 * House.
 *
 * ⛔ WHY DESKTOP DOES NOT FETCH THIS FROM THE SERVER. The perimeter around
 * remote content must not be defined by the remote content. A view that could
 * serve its own allow-list could widen it.
 *
 * Run:  npx tsx scripts/generate-desktop-house-allowlist.ts
 * Test: lib/navigation/__tests__/desktopHouseAllowlistDrift.test.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { HOUSE_DESTINATIONS } from '../lib/navigation/houseDestinations';

/** The Desktop threshold itself. Not a House destination — it IS the House. */
export const DESKTOP_HOUSE_ROUTE = '/house';

/**
 * The member's conversation, which Desktop must never load remotely.
 *
 * ⛔ Matched EXACTLY, never as a prefix. `/maia/anchor`, `/maia/ideas`,
 * `/maia/living-field`, `/maia/keep-capture` and `/maia/vision-studio` are
 * Rooms that happen to live under this path; treating `/maia` as a prefix would
 * bounce a member out of Anchor and back to the local conversation, which is
 * both wrong and baffling.
 */
export const RETURN_TO_MAIA_ROUTES = ['/maia'];

/**
 * Paths every House page needs that are not themselves destinations.
 *
 * Kept deliberately short. This is the "plus only the infrastructure routes
 * necessary for those pages" clause, and every entry should be arguable.
 */
export const INFRASTRUCTURE_ROOTS = [
  '/open-web',      // the House's own web-bridge route (WEB_BRIDGE_ROUTE)
  '/signin',        // a session that expires mid-session must be able to land
];

export function buildManifest() {
  const routed = HOUSE_DESTINATIONS.filter((d) => d.kind === 'route' && d.route);

  // `external` destinations deliberately excluded: those are handed to the OS
  // browser by navigationDecision, never loaded in the platform view.
  const destinations = routed.map((d) => ({
    id: d.id,
    route: d.route as string,
    group: d.group,
    audience: d.audience,
  }));

  const allowedRoots = Array.from(
    new Set(
      destinations
        .map((d) => d.route)
        .filter((r) => !RETURN_TO_MAIA_ROUTES.includes(r))
        .concat(DESKTOP_HOUSE_ROUTE)
        .concat(INFRASTRUCTURE_ROOTS),
    ),
  ).sort();

  return {
    _comment:
      'GENERATED by scripts/generate-desktop-house-allowlist.ts from lib/navigation/houseDestinations.ts. Do not edit by hand — edit the House.',
    houseRoute: DESKTOP_HOUSE_ROUTE,
    returnToMaiaRoutes: RETURN_TO_MAIA_ROUTES,
    allowedRoots,
    destinations: destinations.sort((a, b) => a.id.localeCompare(b.id)),
  };
}

const OUT = path.join(__dirname, '..', 'maia-desktop', 'src', 'house-allowlist.json');

if (require.main === module) {
  const json = JSON.stringify(buildManifest(), null, 2) + '\n';
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${OUT}`);
}
