/**
 * DESKTOP-HOUSE-01 — derive Desktop's platform-view path authority from the
 * canonical House registry.
 *
 * ⛔ WHY GENERATED AND NOT HAND-WRITTEN. Desktop's shell is CommonJS and cannot
 * import `lib/navigation/houseDestinations.ts`, so the allow-list has to exist
 * on the Desktop side in some form. The repo has met this exact problem before
 * — the House registry, the native runtime allow-list and the Capacitor
 * keep-list drifted apart until `houseNavDrift.test.ts` pinned them together.
 * This file goes one step further than a checked duplicate: the Desktop
 * manifest is GENERATED from the registry, and the drift test regenerates and
 * compares, so the only way to change what Desktop may open is to change the
 * House.
 *
 * ⛔ WHY DESKTOP DOES NOT FETCH THIS FROM THE SERVER. The perimeter around
 * remote content must not be defined by the remote content. A view that could
 * serve its own allow-list could widen it.
 *
 * Run:  npx tsx scripts/generate-desktop-house-allowlist.ts
 * Test: lib/navigation/__tests__/desktopHouseAllowlistDrift.test.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { HOUSE_DESTINATIONS } from '../lib/navigation/houseDestinations';

/** The Desktop threshold itself. Not a House destination — it IS the House. */
export const DESKTOP_HOUSE_ROUTE = '/house';

/**
 * DESKTOP-MAIA-UNIFICATION-01 — `/maia` is a DESTINATION, not an instruction.
 *
 * ⛔ WHAT THIS REVERSES. DESKTOP-HOUSE-01 treated the canonical conversation as
 * `return-to-maia`: the platform view refused to load it and Desktop revealed
 * the local Electron renderer instead. Founder ruling after the device walk:
 * that made the witness scaffolding the centre of the product. Everything that
 * makes MAIA herself — arrival, the holoflower, modes, Keep, integrity, the
 * state field — lives on the canonical surface, and the local renderer
 * reimplemented a plain transcript beside it. One MAIA, and it is the canonical
 * one.
 *
 * The local renderer survives as native infrastructure below the surface
 * (credential custody, capture, thread watching). It is not a destination.
 */
export const DESKTOP_MAIA_ROUTE = '/maia';

/**
 * Paths every House page needs that are not themselves destinations.
 *
 * Kept deliberately short. This is the "plus only the infrastructure routes
 * necessary for those pages" clause, and every entry should be arguable.
 */
export const INFRASTRUCTURE_ROOTS = [
  '/open-web',      // the House's own web-bridge route (WEB_BRIDGE_ROUTE)
  '/signin',        // a session that expires mid-session must be able to land
];

export function buildManifest() {
  const routed = HOUSE_DESTINATIONS.filter((d) => d.kind === 'route' && d.route);

  // `external` destinations deliberately excluded: those are handed to the OS
  // browser by navigationDecision, never loaded in the platform view.
  const destinations = routed.map((d) => ({
    id: d.id,
    route: d.route as string,
    group: d.group,
    audience: d.audience,
  }));

  const allowedRoots = Array.from(
    new Set(
      destinations
        .map((d) => d.route)
        .concat(DESKTOP_HOUSE_ROUTE)
        .concat(DESKTOP_MAIA_ROUTE)
        .concat(INFRASTRUCTURE_ROOTS),
    ),
  ).sort();

  return {
    _comment:
      'GENERATED by scripts/generate-desktop-house-allowlist.ts from lib/navigation/houseDestinations.ts. Do not edit by hand — edit the House.',
    houseRoute: DESKTOP_HOUSE_ROUTE,
    maiaRoute: DESKTOP_MAIA_ROUTE,
    allowedRoots,
    destinations: destinations.sort((a, b) => a.id.localeCompare(b.id)),
  };
}

const OUT = path.join(__dirname, '..', 'maia-desktop', 'src', 'house-allowlist.json');

if (require.main === module) {
  const json = JSON.stringify(buildManifest(), null, 2) + '\n';
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${OUT}`);
}
