import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
// Fresh temporary browser contexts only. No account cookies or database inspection.
const base='http://localhost:3797', output='.becoming-preview';
await mkdir(output+'/screenshots',{recursive:true});
const results=[], errors=[], requests=[];
const pass=(id,detail)=>{results.push({id,status:'PASS',detail});console.log('PASS',id);};
const browser=await chromium.launch({headless:true});let failure;
function observe(p){p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push(r.url()));}
const move=(p,name)=>p.getByRole('navigation',{name:'Encounter movements'}).getByRole('button',{name,exact:true}).click();
const save=async(p,rev)=>{await p.getByRole('button',{name:'Keep',exact:true}).click();await p.getByRole('status').filter({hasText:`revision ${rev}`}).waitFor();};
const openCard=(p,name)=>p.getByRole('button').filter({has:p.getByRole('heading',{name,exact:true})}).click();
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/New_York'});
 const page=await context.newPage();observe(page);await page.goto(base+'/becoming');await page.getByRole('heading',{level:1,name:'Becoming'}).waitFor();
 await page.locator('h1').focus();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:output+'/screenshots/arrival-desktop.png',fullPage:true});
 await page.getByText('No reflections kept here yet.',{exact:true}).waitFor();pass('B01','Fresh local browser begins without seeded reflections.');
 await page.getByRole('button',{name:'Begin where you are'}).click();await page.getByLabel('Reflection name').fill('Witness — A quieter life');
 await page.getByLabel('What is here now?').fill('Synthetic witness: making time to listen before agreeing.');
 await move(page,'Open');await page.getByLabel('A name for this possibility').fill('Spaciousness');await page.getByRole('button',{name:'Desired',exact:true}).click();
 await move(page,'Encounter');await page.getByLabel('What appears, in your own words').fill('Synthetic scene: time for a morning walk before work.');
 await page.locator('h1').focus();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:output+'/screenshots/encounter-desktop.png',fullPage:true});
 await move(page,'Open');await page.getByRole('button',{name:'+ Another possibility',exact:true}).click();await page.getByLabel('A name for this possibility').fill('Service with boundaries');
 await move(page,'Encounter');await page.getByLabel('What appears, in your own words').fill('Synthetic scene: contributing without being constantly available.');
 await move(page,'Dialogue');await page.getByRole('button',{name:'+ Me, now',exact:true}).click();await page.getByLabel('Me, now',{exact:true}).fill('What matters most?');
 await page.getByRole('button',{name:'+ Imagined perspective',exact:true}).click();await page.getByLabel('An imagined future perspective',{exact:true}).fill('When I imagine an answer, I notice a wish to be present.');
 await page.locator('h1').focus();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:output+'/screenshots/dialogue-desktop.png',fullPage:true});
 await save(page,1);await page.getByRole('status').filter({hasText:'No return has been recorded.'}).waitFor();pass('B02','Keep succeeds without mandatory Return or action.');
 await page.reload();await openCard(page,'Witness — A quieter life');await page.getByText('Synthetic witness: making time to listen before agreeing.',{exact:true}).waitFor();
 await page.getByRole('heading',{name:'Spaciousness',exact:true}).waitFor();await page.getByRole('heading',{name:'Service with boundaries',exact:true}).waitFor();
 await page.getByText('When I imagine an answer, I notice a wish to be present.',{exact:true}).waitFor();pass('B03','Both possibilities and member-entered dialogue survive reload.');
 const sourceId=new URL(page.url()).searchParams.get('reflection');assert.ok(sourceId);const exact=rev=>`${base}/becoming?reflection=${sourceId}&revision=${rev}`;
 await page.getByRole('button',{name:'Continue reflecting',exact:true}).click();await page.getByLabel('What is here now?').fill('Synthetic revision two.');await save(page,2);
 const other=await context.newPage();observe(other);await other.goto(exact(2));await other.getByRole('button',{name:'Continue reflecting',exact:true}).click();
 await page.getByLabel('What is here now?').fill('Synthetic winning revision three.');await save(page,3);
 await other.getByLabel('What is here now?').fill('Synthetic stale edit retained in this tab.');await other.getByRole('button',{name:'Keep',exact:true}).click();
 await other.getByRole('alert').filter({hasText:'Another tab changed or deleted this reflection.'}).waitFor();assert.equal(await other.getByLabel('What is here now?').inputValue(),'Synthetic stale edit retained in this tab.');
 pass('B04','A stale-tab save is refused and the unsaved words remain visible.');await other.close();
 const history=await context.newPage();observe(history);await history.goto(exact(1));await history.getByText('Synthetic witness: making time to listen before agreeing.',{exact:true}).waitFor();
 assert.equal(await history.getByText('Synthetic winning revision three.',{exact:true}).count(),0);pass('B05','Exact historical revision is not silently replaced by latest.');
 await history.goto(exact(999));await history.getByRole('heading',{name:'Source unavailable',exact:true}).waitFor();pass('B06','An unavailable revision does not fall back to another.');await history.close();
 await page.getByRole('button',{name:'Temporal field',exact:true}).click();await page.locator('.source-check input').first().check();
 await page.getByLabel('What is true for you now?').fill('Synthetic present: a new invitation has arrived.');
 await page.getByLabel('A connection I notice',{exact:true}).fill('I want to distinguish generosity from automatic agreement.');
 await page.getByLabel('What is different—or does not fit?').fill('Sometimes an invitation feels joyful, not burdensome.');
 await page.getByRole('button',{name:'Your reflections',exact:true}).click();await page.getByRole('dialog',{name:'Leave these temporal notes?'}).waitFor();await page.getByRole('button',{name:'Stay with these notes',exact:true}).click();
 assert.equal(await page.getByLabel('A connection I notice',{exact:true}).inputValue(),'I want to distinguish generosity from automatic agreement.');pass('B07','Temporal notes have an explicit departure warning and remain on cancel.');
 await page.locator('h1').focus();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:output+'/screenshots/temporal-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Begin from these reflections'}).click();assert.equal(await page.getByLabel('What is here now?').inputValue(),'Synthetic present: a new invitation has arrived.');
 await page.getByLabel('Reflection name').fill('Witness — A present connection');await save(page,1);await page.getByRole('button',{name:'Your reflections',exact:true}).click();await openCard(page,'Witness — A present connection');
 await page.getByText('Sometimes an invitation feels joyful, not burdensome.',{exact:true}).waitFor();pass('B08','A member-selected connection and its counterexample are retained.');
 await page.getByRole('button',{name:'Return to Witness — A quieter life · revision 3',exact:true}).click();await page.getByText('Synthetic winning revision three.',{exact:true}).waitFor();
 assert.equal(new URL(page.url()).searchParams.get('revision'),'3');pass('B09','The relationship returns to the exact source version.');
 await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete reflection and revisions',exact:true}).click();await openCard(page,'Witness — A present connection');
 await page.getByText('Original source no longer available. Its words have not been reconstructed.',{exact:true}).waitFor();pass('B10','Deleting a source leaves a truthful unavailable relation.');
 await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete reflection and revisions',exact:true}).click();await page.getByRole('heading',{name:'Nothing has been kept here yet.'}).waitFor();
 pass('B11','Deleting both synthetic reflections returns the visible library to empty.');
 await page.getByRole('button',{name:'Begin a reflection',exact:true}).click();await page.getByLabel('Reflection name').fill('Witness — Not yet known');await move(page,'Return');
 await page.getByRole('button',{name:'Return to now',exact:true}).click();await page.getByRole('button',{name:'Pause and leave',exact:true}).click();await page.getByRole('button',{name:'Keep and leave',exact:true}).click();
 await openCard(page,'Witness — Not yet known');await page.getByText('No image recorded.',{exact:true}).waitFor();await page.getByText('No action or practice was recorded.',{exact:true}).waitFor();
 await page.locator('.reading-paper').getByText(/^Return recorded /).waitFor();pass('B12','No-image/no-action session can return; Keep and leave preserves the explicit return.');
 await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete reflection and revisions',exact:true}).click();
 await page.getByRole('button',{name:'Begin a reflection',exact:true}).click();await page.getByLabel('What is here now?').fill('Synthetic unkept draft.');await move(page,'Open');await page.getByRole('button',{name:'Feared',exact:true}).click();
 await page.getByText('You can name this from a distance. You do not need to enter it or make it speak.',{exact:true}).waitFor();pass('B13','Feared possibility offers distance without compulsory dialogue.');
 await page.getByRole('button',{name:'Pause and leave',exact:true}).click();await page.getByRole('dialog',{name:'Leave this reflection?'}).waitFor();await page.keyboard.press('Escape');await move(page,'Arrive');
 assert.equal(await page.getByLabel('What is here now?').inputValue(),'Synthetic unkept draft.');pass('B14','Keyboard cancellation preserves the unfinished encounter.');
 await page.getByRole('button',{name:'Pause and leave',exact:true}).click();await page.getByRole('button',{name:'Leave without keeping',exact:true}).click();await page.getByText('No reflections kept here yet.',{exact:true}).waitFor();pass('B15','Explicit discard does not leave a visible saved reflection.');
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,reducedMotion:'reduce'});const mp=await mobile.newPage();observe(mp);await mp.goto(base+'/becoming');await mp.locator('h1').focus();await mp.evaluate(()=>window.scrollTo(0,0));await mp.screenshot({path:output+'/screenshots/arrival-mobile.png',fullPage:true});
 assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mp.getByRole('button',{name:'Begin where you are'}).click();await mp.locator('h1').focus();await mp.evaluate(()=>window.scrollTo(0,0));await mp.screenshot({path:output+'/screenshots/encounter-mobile.png',fullPage:true});
 assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('B16','Arrival and encounter fit a 390px viewport without horizontal scrolling.');
 const actions=await mp.getByRole('button').evaluateAll(xs=>xs.filter(x=>x.getBoundingClientRect().height>0).map(x=>({label:x.textContent,size:parseFloat(getComputedStyle(x).fontSize),height:x.getBoundingClientRect().height})));
 assert.ok(actions.every(x=>x.size>=16&&x.height>=44),JSON.stringify(actions));pass('B17','Visible mobile buttons meet the 16px type and 44px height floors.');
 await move(mp,'Return');await mp.getByRole('button',{name:'Return to now',exact:true}).waitFor();await mp.locator('h1').focus();await mp.evaluate(()=>window.scrollTo(0,0));await mp.screenshot({path:output+'/screenshots/return-mobile.png',fullPage:true});pass('B18','Return remains directly reachable on mobile without filling earlier movements.');
 assert.equal(errors.length,0,errors.join('\n'));assert.ok(requests.every(u=>new URL(u).origin===base));pass('B19','No JavaScript page errors or off-origin browser requests occurred during this walk.');
 const response=await fetch(base+'/health');const health=await response.json();assert.equal(health.scope,'isolated-local-preview');assert.ok(response.headers.get('content-security-policy').includes("connect-src 'none'"));
 await writeFile(output+'/witness-health.json',JSON.stringify(health,null,2));pass('B20','Loopback preview identifies its bundle and emits the no-connect content policy.');
} catch(e) {failure=e;console.error('WITNESS_FAILED',e.message);}
finally {
 await browser.close();
 await writeFile(output+'/browser-witness.json',JSON.stringify({scope:'Fresh synthetic contexts; visible UI only, no direct database audit, no account or production testing',recordedAt:new Date().toISOString(),results,errors,requests:[...new Set(requests)],failure:failure?String(failure.message):null},null,2));
}
if(failure)process.exitCode=1;
