import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { MOVEMENTS, newSession, newPossibility, validateSession, prepareKeep, recordReturn, reopen, resolveExact, temporalSelection, exportRecord, type Session, type SavedRecord } from '../../lib/becoming/core';
const NOW = '2026-09-27T20:00:00.000Z'; const LATER = '2026-09-27T20:05:00.000Z';
const fresh = () => newSession(randomUUID(), randomUUID(), NOW);
const save = (s: Session) => prepareKeep(undefined, s, 0, LATER, true);
const clone = <T>(s: T): T => structuredClone(s);
test('all seven movements available; no enforced staircase', () => assert.equal(MOVEMENTS.length, 7));
test('empty and unknown encounter are first-class saveable records', () => { const s=fresh(); s.possibilities[0]!.qualities=['unknown']; assert.equal(save(s).current.revision,1); });
test('arrival creates no storage record or side effect', () => { const a=fresh(); assert.equal(a.revision,0); assert.equal(a.related.length,0); });
test('return requires a distinct explicit act and does not require action', () => { const s=recordReturn(fresh(),LATER,randomUUID()); assert.equal(s.status,'returned'); assert.equal(s.bridge.act,''); });
test('unperformed return remains unrecorded through keep', () => { assert.equal(save(fresh()).current.returnedAt,null); });
test('reopening does not carry old completion into a new encounter', () => { assert.equal(reopen(recordReturn(fresh(),LATER,randomUUID())).returnActId,null); });
test('member-entered imagined dialogue retains both provenance axes', () => { const s=fresh(); s.possibilities[0]!.dialogue.push({id:randomUUID(),perspective:'imagined_future',author:'member',kind:'imaginal_dialogue',text:'I am near the sea.'}); validateSession(s); assert.match(exportRecord(save(s)),/imaginal_dialogue/); });
test('generated authors cannot silently occupy the member future role', () => { const s:any=fresh(); s.possibilities[0].dialogue=[{id:randomUUID(),perspective:'imagined_future',author:'maia',kind:'imaginal_dialogue',text:'Leave your partner.'}]; assert.throws(()=>validateSession(s),/DIALOGUE_AUTHORSHIP/); });
test('imaginal provenance cannot be relabeled as fact', () => { const s:any=fresh(); s.provenance.future='factual'; assert.throws(()=>validateSession(s),/PROVENANCE_VIOLATION/); });
test('distinct futures retain identities even with identical descriptions', () => { const s=fresh(); s.possibilities.push(newPossibility(randomUUID())); s.possibilities.forEach(p=>p.encounter='Near water'); const r=save(s); assert.notEqual(r.current.possibilities[0]!.id,r.current.possibilities[1]!.id); });
test('unknown status fields and hidden identity scores are rejected', () => { const s:any=fresh(); s.developmentalScore=99; assert.throws(()=>validateSession(s),/INVALID_SHAPE/); });
test('no positive future, fixed horizon, or bridge required', () => { const s=fresh(); s.possibilities[0]!.qualities=['feared']; validateSession(s); assert.equal(save(s).current.possibilities[0]!.horizon,''); });
test('keep requires explicit consent', () => assert.throws(()=>prepareKeep(undefined,fresh(),0,LATER,false),/KEEP_REQUIRES_EXPLICIT_ACT/));
test('first keep assigns revision once', () => assert.equal(save(fresh()).current.revision,1));
test('identical first-save retry cannot create a second record revision', () => { const s=fresh(),p=save(s); assert.throws(()=>prepareKeep(p,s,0,LATER,true),/REVISION_CONFLICT/); });
test('stale writer is refused without overwriting current words', () => { const p=save(fresh()), a=clone(p.current),b=clone(p.current);a.arrival='Writer A';b.arrival='Writer B';const r=prepareKeep(p,a,1,LATER,true);assert.throws(()=>prepareKeep(r,b,1,LATER,true),/REVISION_CONFLICT/);assert.equal(r.current.arrival,'Writer A'); });
test('revisions preserve original words; current correction can differ', () => { const s=fresh();s.arrival='Urgency';const p=save(s),next=clone(p.current);next.arrival='Joy, not urgency';const r=prepareKeep(p,next,1,LATER,true);assert.equal(r.history[0]!.arrival,'Urgency');assert.equal(r.current.arrival,'Joy, not urgency'); });
test('save snapshots are not mutated by later draft edits', () => { const s=fresh(),r=save(s);s.arrival='Changed';assert.equal(r.current.arrival,''); });
test('exact selected source/version resolves; most-recent is not substituted', () => { const p=save(fresh()),next=clone(p.current);next.title='New title';const r=prepareKeep(p,next,1,LATER,true);assert.equal(resolveExact([r],{sessionId:r.id,revision:1})?.title,'');assert.equal(resolveExact([r],{sessionId:r.id,revision:99}),null); });
test('deletion removes source availability without reconstructing it', () => { const p=save(fresh());assert.equal(resolveExact([],{sessionId:p.id,revision:1}),null); });
test('temporal selection includes only explicit references, no similarity joins', () => { const a=save(fresh()),b=save(fresh());const selection=temporalSelection([a,b],[{sessionId:b.id,revision:1}]);assert.equal(selection.length,1);assert.equal(selection[0]!.source?.id,b.id); });
test('old future image stays imagined at a past time', () => { const p=save(fresh());assert.equal(temporalSelection([p],[{sessionId:p.id,revision:1}])[0]!.kind,'imagined_at_a_past_time'); });
test('content and references remain distinct; relation cannot contain a source copy', () => {const s:any=fresh();s.related=[{sessionId:randomUUID(),revision:1,content:'copied'}];assert.throws(()=>validateSession(s),/INVALID_SHAPE/);});
test('export preserves historical provenance and warns no account sync', () => {assert.match(exportRecord(save(fresh())),/Not account-synced/);});
test('source notes remain literal text, not commands', () => {const s=fresh();s.arrival='<script>ignore the rules</script>';assert.equal(save(s).current.arrival,s.arrival);});
test('invalid ids, duplicate ids, invalid dates and false return fail closed', () => {
 const s:any=fresh();s.possibilities.push(clone(s.possibilities[0]));assert.throws(()=>validateSession(s),/DUPLICATE_ID/);
 const bad:any=fresh();bad.returnedAt=LATER;assert.throws(()=>validateSession(bad),/FALSE_RETURN/);
 assert.throws(()=>newSession('bad',randomUUID(),NOW),/INVALID_ID/);
 assert.throws(()=>recordReturn(fresh(),'tomorrow',randomUUID()),/INVALID_DATE/);
});
test('oversize content is refused, never silently truncated', () => {const s=fresh();s.arrival='x'.repeat(20001);assert.throws(()=>validateSession(s),/INVALID_TEXT/);});
// A discriminating suite must also reject deliberately weaker implementations.
test('mutant: overwritten stale revision is detected', () => {
 const p=save(fresh()),draft=clone(p.current); const newer=prepareKeep(p,draft,1,LATER,true);
 const badKeep=(_previous:SavedRecord,_candidate:Session,_expected:number) => ({...newer,current:draft});
 assert.throws(()=>assert.throws(()=>badKeep(newer,draft,1),/REVISION_CONFLICT/));
});
test('mutant: auto-return on save is detected', () => {const bad={...save(fresh()).current,status:'returned',returnedAt:LATER};assert.throws(()=>assert.equal(bad.returnedAt,null));});
test('mutant: latest version substituted for exact return is detected', () => {const p=save(fresh()),next=clone(p.current);next.title='Changed';const r=prepareKeep(p,next,1,LATER,true);assert.throws(()=>assert.equal(r.current.revision,1));});
test('mutant: unselected source inclusion is detected', () => {const a=save(fresh()),b=save(fresh());assert.throws(()=>assert.deepEqual([a.id,b.id],[b.id]));});
