"""
PGN tree builder.

Constructs a chess.pgn.Game tree with variations, comments, and annotations
suitable for import into ChessBase, Lichess studies, or any PGN reader.
"""

import chess
import chess.pgn


class PGNBuilder:
    """Builds annotated PGN game trees."""

    def __init__(self, side, event="Opening Repertoire"):
        """
        Initialize the PGN builder.

        Args:
            side: "white" or "black" — the repertoire side
            event: Event header for the PGN
        """
        self.game = chess.pgn.Game()
        self.game.headers["Event"] = event
        self.game.headers["Site"] = "Generated by Chess Repertoire Generator"
        self.game.headers["White"] = "Repertoire" if side == "white" else "Opponent"
        self.game.headers["Black"] = "Opponent" if side == "white" else "Repertoire"
        self.game.headers["Result"] = "*"
        self.side = side

    def set_starting_position(self, board):
        """Set a custom starting position if not from the initial position."""
        if board.fen() != chess.STARTING_FEN:
            self.game.setup(board)

    def add_opponent_move(self, parent_node, move_san, board, frequency, total_games):
        """
        Add an opponent's move to the tree.

        Args:
            parent_node: The parent node in the game tree
            move_san: Move in SAN notation
            board: Board state BEFORE the move
            frequency: How often this move is played (%)
            total_games: Total games in the database for this position

        Returns:
            The new child node
        """
        move = board.parse_san(move_san)
        child = parent_node.add_variation(move)
        child.comment = f"{frequency}% of {total_games:,} games"
        return child

    def add_repertoire_move(self, parent_node, move_san, board,
                            score=None, games=None, source="masters"):
        """
        Add a repertoire move (our recommended response).

        Args:
            parent_node: The parent node in the game tree
            move_san: Move in SAN notation
            board: Board state BEFORE the move
            score: Win percentage for our side
            games: Number of games this move was played
            source: "masters", "lichess", or "book"

        Returns:
            The new child node
        """
        move = board.parse_san(move_san)
        child = parent_node.add_variation(move)

        parts = []
        if source == "masters":
            parts.append("Masters DB")
        elif source == "book":
            parts.append("Book")
            child.nags.add(chess.pgn.NAG_GOOD_MOVE)  # !
        else:
            parts.append("Lichess DB")

        if score is not None:
            parts.append(f"Score: {score:.1f}%")
        if games is not None:
            parts.append(f"({games:,} games)")

        child.comment = " | ".join(parts)
        return child

    def add_book_alternative(self, parent_node, move_san, board, weight=None):
        """
        Add a book alternative move.

        Args:
            parent_node: The parent node in the game tree
            move_san: Move in SAN notation
            board: Board state BEFORE the move
            weight: Book weight

        Returns:
            The new child node
        """
        move = board.parse_san(move_san)
        child = parent_node.add_variation(move)
        child.nags.add(chess.pgn.NAG_GOOD_MOVE)  # !

        comment = "Book recommendation"
        if weight is not None:
            comment += f" (weight: {weight})"
        child.comment = comment
        return child

    def add_evaluation(self, node, eval_str, classification=None, best_move=None):
        """
        Add Stockfish evaluation as a comment to a node.

        Args:
            node: The game tree node
            eval_str: Evaluation string (e.g., "+0.45", "#3")
            classification: Human-readable assessment (e.g., "equal")
            best_move: Best move suggestion in SAN
        """
        parts = [node.comment] if node.comment else []
        parts.append(f"Eval: {eval_str}")
        if classification:
            parts.append(f"({classification})")
        if best_move:
            parts.append(f"Best: {best_move}")
        node.comment = " | ".join(parts)

    def add_termination_comment(self, node, reason):
        """Add a comment explaining why the tree stopped here."""
        parts = [node.comment] if node.comment else []
        parts.append(f"[{reason}]")
        node.comment = " | ".join(parts)

    def to_pgn_string(self):
        """Export the game tree as a PGN string."""
        exporter = chess.pgn.StringExporter(
            headers=True,
            variations=True,
            comments=True,
        )
        return self.game.accept(exporter)

    def save(self, filepath):
        """Save the PGN to a file."""
        pgn_str = self.to_pgn_string()
        with open(filepath, "w") as f:
            f.write(pgn_str)
            f.write("\n")
        return filepath
