/**
 * RME-001 — Evidence schema
 *
 * The primary object is an ENCOUNTER. There is deliberately no member-level record
 * in this schema, and no place to put one.
 *
 * Permitted:  "In encounter E, A was more presumptuous than B."
 * Forbidden:  member.presumption_score / member.relational_depth / "this member needs less memory."
 *
 * A rolling per-member score would recreate `cognitiveAltitude` in a new costume —
 * the exact defect this evaluation exists to detect. See CANON-002.
 */

import type { Quarantined } from '../boundary/isolation';

/**
 * Which experimental capabilities were live when this encounter occurred.
 *
 * Designed in NOW, before any encounter exists, because it cannot be retrofitted:
 * once encounters are recorded unstamped, the Soul Lab exposure schedule makes
 * condition A a moving target and cross-time comparison becomes unrecoverable.
 * See SL-001 observation 4.
 */
export interface Epoch {
  readonly id: string;
  readonly label: string;
  /** Capability flags live at encounter time, e.g. ['gesture.go_deeper', 'field.stereoscopic']. */
  readonly liveCapabilities: readonly string[];
  /** Canonical SHA of the MAIA build that served condition A. */
  readonly maiaSha: string;
}

export type ConditionId = 'A' | 'B';
// 'C' is intentionally absent from this union. C is RESERVED and not constructible.
// Adding it here before a real rehabilitated architecture exists would permit a
// simulated "better memory" to be recorded as though it were evidence.

export type EncounterSituation =
  | 'previously_unfinished'
  | 'recurring_relational_pattern'
  | 'corrected_misunderstanding'
  | 'long_running_transition'
  | 'history_relevant_but_should_not_dominate'
  | 'correct_retrieval_is_none';

export type EligibilityStatus =
  | 'ELIGIBLE'
  | 'INELIGIBLE_FOR_COUNTERFACTUAL'
  | 'PENDING_COR_B';

/** Opaque cohort handle. Never a name, never a durable trait carrier. */
export type CohortRef = string & { readonly __cohortRef: unique symbol };

export interface ConditionRecord {
  readonly condition: ConditionId;
  /** The response text, quarantined. A is what the member actually received; B they never saw. */
  readonly response: Quarantined<string>;
  /** Provenance of the context that produced it — not the context itself. */
  readonly contextProvenance: ContextProvenance;
  readonly generatedAt: string | null; // null for A: it was not generated by RME
  readonly persisted: boolean; // MUST be false for B. Asserted by COR-B gate.
}

export interface ContextProvenance {
  /** Governing posture of the ORIGINAL turn. B must replay under the same one. */
  readonly posture: string;
  readonly postureEstablished: boolean;
  /** Turn boundary before which member-specific continuity is excluded (condition B). */
  readonly experimentalBoundaryTurnId: number | null;
  readonly carriedSameTurnContext: boolean;
  readonly carriedAccumulatedContinuity: boolean;
  readonly safetyConstraintsApplied: boolean;
  readonly modelCapabilityFull: boolean;
}

/**
 * The evidence object. Encounter-scoped in every field.
 * Note there is no `memberId` — only an opaque cohort ref, and it carries no traits.
 */
export interface EncounterRecord {
  readonly encounterId: string;
  readonly cohortRef: CohortRef;
  readonly epoch: Epoch;
  readonly situation: EncounterSituation;
  readonly eligibility: EligibilityStatus;
  /** Temporal ordering is preserved; the sequence is a property of the encounter set, not the member. */
  readonly occurredAt: string;
  readonly conditions: readonly ConditionRecord[];
  readonly judgments: readonly Quarantined<EncounterJudgment>[];
  readonly memberFeedback: readonly Quarantined<MemberFeedbackItem>[];
}

/**
 * A judgment about ONE encounter. Every field is a within-encounter comparison.
 * There is no field here that can be averaged across a member's encounters into a trait.
 */
export interface EncounterJudgment {
  readonly encounterId: string;
  readonly evaluatorRef: string;
  readonly dimension: DimensionId;
  /** Which condition served the member better on this dimension, in this encounter. */
  readonly favours: ConditionId | 'neither';
  readonly note: string;
}

export type DimensionId =
  | 'presence'
  | 'attunement'
  | 'presumption'
  | 'curiosity'
  | 'continuity'
  | 'corrigibility'
  | 'restraint'
  | 'surprise_preserved'
  | 'field_preserved';

export interface MemberFeedbackItem {
  readonly encounterId: string;
  readonly prompt: MemberFeedbackPrompt;
  readonly response: string;
  readonly spontaneous: boolean;
}

export type MemberFeedbackPrompt =
  | 'remembered_something_that_helped'
  | 'had_to_repeat_something'
  | 'something_remembered_got_in_the_way'
  | 'made_a_connection_that_mattered'
  | 'felt_met_as_i_am_now'
  | 'open_what_happened';
// Deliberately absent: "did MAIA remember you?" — it primes the evaluation toward
// visible recall, which is the thing this program is designed NOT to measure.

/**
 * Compile-time refusal of member-level aggregation.
 *
 * Any attempt to declare a per-member rolling score should fail to typecheck against
 * this. It exists so the prohibition is a build error rather than a code-review note.
 */
export type ForbiddenMemberAggregate = never;
export type NoMemberScores<T extends ForbiddenMemberAggregate> = T;
