'use client';

/**
 * Member Landing Page Template
 *
 * Generated by MAIA site factory.
 * All copy driven from CONTENT.json — edit there, not here.
 *
 * Design tokens: Soullab sacred palette (navy/spice/sage)
 * Fonts: Crimson Pro (headings), Source Sans Pro (body)
 */

import content from './CONTENT.json';

const elementIcons: Record<string, string> = {
  fire: '\u{1F525}',
  water: '\u{1F30A}',
  earth: '\u{1F331}',
  air: '\u{1F32C}\u{FE0F}',
  aether: '\u{2728}',
};

export default function MemberLanding() {
  const { member, hero, features, testimonial, theme } = content;

  return (
    <main
      className="min-h-screen"
      style={{
        backgroundColor: theme.primary,
        fontFamily: `'${theme.bodyFont}', sans-serif`,
      }}
    >
      {/* Hero */}
      <section className="flex flex-col items-center justify-center min-h-[80vh] px-6 text-center">
        <h1
          className="text-5xl md:text-7xl font-light tracking-wide text-white mb-4"
          style={{ fontFamily: `'${theme.headingFont}', serif` }}
        >
          {hero.heading}
        </h1>
        <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-2xl">
          {hero.subheading}
        </p>
        <a
          href={hero.ctaLink}
          className="px-8 py-3 rounded-full text-lg font-medium transition-all duration-300 hover:scale-105"
          style={{
            backgroundColor: theme.accent,
            color: theme.primary,
          }}
        >
          {hero.ctaText}
        </a>
      </section>

      {/* About */}
      <section className="max-w-3xl mx-auto px-6 py-20">
        <h2
          className="text-3xl font-light text-white mb-6"
          style={{ fontFamily: `'${theme.headingFont}', serif` }}
        >
          {member.name}
        </h2>
        <p className="text-lg text-gray-300 leading-relaxed">
          {member.bio}
        </p>
      </section>

      {/* Features */}
      <section className="max-w-5xl mx-auto px-6 py-20">
        <div className="grid md:grid-cols-3 gap-8">
          {features.map((feature, i) => (
            <div
              key={i}
              className="p-8 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-sm"
            >
              <div className="text-3xl mb-4">
                {elementIcons[feature.icon] || '\u{2728}'}
              </div>
              <h3
                className="text-xl text-white mb-3"
                style={{ fontFamily: `'${theme.headingFont}', serif` }}
              >
                {feature.title}
              </h3>
              <p className="text-gray-400 leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Testimonial */}
      {testimonial && (
        <section className="max-w-3xl mx-auto px-6 py-20 text-center">
          <blockquote
            className="text-2xl text-gray-300 italic mb-4"
            style={{ fontFamily: `'${theme.headingFont}', serif` }}
          >
            &ldquo;{testimonial.quote}&rdquo;
          </blockquote>
          <p className="text-gray-500">
            {testimonial.author}
            {testimonial.role && ` — ${testimonial.role}`}
          </p>
        </section>
      )}

      {/* Contact */}
      <section id="contact" className="max-w-3xl mx-auto px-6 py-20 text-center">
        <h2
          className="text-3xl font-light text-white mb-6"
          style={{ fontFamily: `'${theme.headingFont}', serif` }}
        >
          Get in Touch
        </h2>
        <a
          href={
            member.contactMethod === 'email'
              ? `mailto:${member.contactValue}`
              : member.contactValue
          }
          className="inline-block px-8 py-3 rounded-full text-lg font-medium transition-all duration-300 hover:scale-105"
          style={{
            backgroundColor: theme.accent,
            color: theme.primary,
          }}
        >
          {member.contactMethod === 'email' ? 'Send Email' : 'Connect'}
        </a>
      </section>

      {/* Footer */}
      <footer className="text-center py-8 text-gray-600 text-sm">
        Built with Soullab
      </footer>
    </main>
  );
}
