"use client";

/**
 * Reality Hygiene Display - Shows Reality Check Results
 *
 * Displays consciousness-expanding questions generated by RealityCheckAgent.
 * Mapped to Spiralogic elements for MAIA-native integration.
 */

import { useMemo } from "react";

type RealityHygieneResult = {
  total: number;
  max: number;
  band: "low" | "moderate" | "strong" | "overwhelming";
  topSignals: Array<{
    indicator: string;
    score: number;
    element: string;
  }>;
  elementalBreakdown: Record<string, number>;
  questions: {
    lowering_score: string;
    emotional_recruitment: string;
    freedom_questions: string[];
    primary_element: string;
    developmental_note?: string;
  };
};

export function RealityHygieneDisplay({
  result,
}: {
  result: RealityHygieneResult;
}) {
  // Band styling
  const bandColors: Record<string, { bg: string; text: string; border: string }> = {
    low: {
      bg: "bg-green-50 dark:bg-green-900/20",
      text: "text-green-700 dark:text-green-300",
      border: "border-green-200 dark:border-green-800",
    },
    moderate: {
      bg: "bg-yellow-50 dark:bg-yellow-900/20",
      text: "text-yellow-700 dark:text-yellow-300",
      border: "border-yellow-200 dark:border-yellow-800",
    },
    strong: {
      bg: "bg-orange-50 dark:bg-orange-900/20",
      text: "text-orange-700 dark:text-orange-300",
      border: "border-orange-200 dark:border-orange-800",
    },
    overwhelming: {
      bg: "bg-red-50 dark:bg-red-900/20",
      text: "text-red-700 dark:text-red-300",
      border: "border-red-200 dark:border-red-800",
    },
  };

  const colors = bandColors[result.band];

  // Element colors for visualization
  const elementColors: Record<string, string> = {
    Water: "bg-blue-500",
    Fire: "bg-red-500",
    Earth: "bg-amber-600",
    Air: "bg-sky-400",
    Aether: "bg-purple-500",
  };

  return (
    <div
      className={`rounded-2xl border ${colors.border} ${colors.bg} p-6 space-y-5`}
    >
      {/* Header */}
      <div className="flex items-baseline justify-between">
        <div>
          <div className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            🔍 Reality Hygiene Analysis
          </div>
          <div className="text-sm text-gray-600 dark:text-gray-400 mt-1">
            Manipulation pattern detection
          </div>
        </div>
        <div className="text-right">
          <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">
            {result.total}/{result.max}
          </div>
          <div className={`text-sm uppercase tracking-wide font-semibold ${colors.text}`}>
            {result.band}
          </div>
        </div>
      </div>

      {/* Elemental Breakdown */}
      <div>
        <div className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Elemental Breakdown (Primary: {result.questions.primary_element})
        </div>
        <div className="grid grid-cols-5 gap-2">
          {Object.entries(result.elementalBreakdown).map(([element, score]) => (
            <div key={element} className="text-center">
              <div
                className={`h-2 rounded-full ${elementColors[element]}`}
                style={{ width: `${(score / 25) * 100}%`, minWidth: "10%" }}
              />
              <div className="text-xs font-medium text-gray-600 dark:text-gray-400 mt-1">
                {element}
              </div>
              <div className="text-sm font-semibold text-gray-900 dark:text-gray-100">
                {score}/25
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Top Signals */}
      <div>
        <div className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Top Manipulation Patterns
        </div>
        <div className="space-y-1">
          {result.topSignals.slice(0, 5).map((signal, i) => (
            <div
              key={i}
              className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300"
            >
              <span className="font-semibold text-gray-900 dark:text-gray-100">
                {signal.score}
              </span>
              <span className="flex-1">
                {signal.indicator.replace(/_/g, " ")}
              </span>
              <span className="text-xs text-gray-500 dark:text-gray-500">
                {signal.element}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Consciousness-Expanding Questions */}
      <div className="space-y-4 pt-4 border-t border-gray-200 dark:border-gray-700">
        <div className="text-sm font-semibold text-gray-900 dark:text-gray-100">
          Consciousness-Expanding Questions
        </div>

        {/* EARTH/AIR: Lowering Score */}
        <div className="space-y-2">
          <div className="text-xs uppercase tracking-wide font-medium text-amber-600 dark:text-amber-400">
            Earth/Air - Grounding
          </div>
          <div className="text-sm text-gray-700 dark:text-gray-300 italic">
            {result.questions.lowering_score}
          </div>
        </div>

        {/* WATER/FIRE: Emotional Recruitment */}
        <div className="space-y-2">
          <div className="text-xs uppercase tracking-wide font-medium text-blue-600 dark:text-blue-400">
            Water/Fire - Awareness
          </div>
          <div className="text-sm text-gray-700 dark:text-gray-300 italic">
            {result.questions.emotional_recruitment}
          </div>
        </div>

        {/* AETHER: Freedom Questions */}
        <div className="space-y-2">
          <div className="text-xs uppercase tracking-wide font-medium text-purple-600 dark:text-purple-400">
            Aether - Sovereignty
          </div>
          <ul className="space-y-1 list-disc list-inside">
            {result.questions.freedom_questions.map((q, i) => (
              <li key={i} className="text-sm text-gray-700 dark:text-gray-300 italic">
                {q}
              </li>
            ))}
          </ul>
        </div>

        {/* Developmental Note */}
        {result.questions.developmental_note && (
          <div className="mt-4 p-3 bg-white/50 dark:bg-gray-800/50 rounded-lg">
            <div className="text-xs uppercase tracking-wide font-medium text-gray-600 dark:text-gray-400 mb-1">
              Developmental Note
            </div>
            <div className="text-sm text-gray-700 dark:text-gray-300">
              {result.questions.developmental_note}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
