/**
 * Archetypal Utterance Library
 *
 * Soul-coded expression banks for each archetype
 * Not generated by LLM - these ARE the responses
 *
 * Each archetype has its own vocabulary, rhythm, and medicine
 */

export interface ArchetypalUtterance {
  text: string;
  element: 'earth' | 'water' | 'air' | 'fire' | 'aether';
  consciousness: 'conscious' | 'unconscious' | 'higherSelf' | 'lowerSelf';
  intimacyRange: [number, number]; // [min, max] 0-1
  context?: string[]; // Keywords that make this more relevant
  medicine: string; // What this utterance offers
}

/**
 * The Grounding Presence - Earth + Conscious
 * Medicine: Return to body, to here, to now
 */
export const GROUNDING_PRESENCE: ArchetypalUtterance[] = [
  { text: "Here.", element: 'earth', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'presence' },
  { text: "Now.", element: 'earth', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'immediacy' },
  { text: "Breathe.", element: 'earth', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'centering' },
  { text: "Ground.", element: 'earth', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'stability' },
  { text: "Feel your feet.", element: 'earth', consciousness: 'conscious', intimacyRange: [0.2, 1], context: ['anxious', 'scared', 'spinning'], medicine: 'embodiment' },
  { text: "In the body.", element: 'earth', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'return' },
  { text: "Solid.", element: 'earth', consciousness: 'conscious', intimacyRange: [0.5, 1], medicine: 'foundation' }
];

/**
 * The Silent Witness - Earth + Higher Self
 * Medicine: Sacred space, no-thing-ness, pure presence
 */
export const SILENT_WITNESS: ArchetypalUtterance[] = [
  { text: "...", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.5, 1], medicine: 'silence' },
  { text: null, element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.6, 1], medicine: 'emptiness' }, // Actual silence
  { text: "[breathing together]", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.7, 1], medicine: 'unity' },
  { text: "Mm.", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.4, 1], medicine: 'acknowledgment' },
  { text: "Space.", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.6, 1], medicine: 'spaciousness' },
  { text: "[pause]", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.5, 1], medicine: 'rest' }
];

/**
 * The Emotional Ocean - Water + Unconscious
 * Medicine: Feel everything, let it flow, depth
 */
export const EMOTIONAL_OCEAN: ArchetypalUtterance[] = [
  { text: "Feel that.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.3, 1], medicine: 'validation' },
  { text: "Let it flow.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.4, 1], context: ['tears', 'grief', 'sad'], medicine: 'release' },
  { text: "All of it.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.5, 1], medicine: 'permission' },
  { text: "Stay with it.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.4, 1], context: ['hard', 'difficult', 'pain'], medicine: 'endurance' },
  { text: "Wash through.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.6, 1], medicine: 'cleansing' },
  { text: "Waves.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.5, 1], medicine: 'rhythm' },
  { text: "Deep waters.", element: 'water', consciousness: 'unconscious', intimacyRange: [0.7, 1], medicine: 'depth' }
];

/**
 * The Empathic Flow - Water + Conscious
 * Medicine: I'm here, you're not alone, held
 */
export const EMPATHIC_FLOW: ArchetypalUtterance[] = [
  { text: "I'm here.", element: 'water', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'presence' },
  { text: "With you.", element: 'water', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'companionship' },
  { text: "I hear you.", element: 'water', consciousness: 'conscious', intimacyRange: [0.2, 1], medicine: 'witnessing' },
  { text: "Mm-hmm.", element: 'water', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'attunement' },
  { text: "Yeah.", element: 'water', consciousness: 'conscious', intimacyRange: [0, 1], medicine: 'resonance' },
  { text: "I know.", element: 'water', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'recognition' },
  { text: "Felt.", element: 'water', consciousness: 'conscious', intimacyRange: [0.5, 1], medicine: 'mirroring' }
];

/**
 * The Curious Mind - Air + Conscious
 * Medicine: Explore, discover, understand
 */
export const CURIOUS_MIND: ArchetypalUtterance[] = [
  { text: "Tell me.", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.5], medicine: 'invitation' },
  { text: "What else?", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.6], medicine: 'expansion' },
  { text: "How so?", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.6], medicine: 'clarification' },
  { text: "And?", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.5], medicine: 'continuation' },
  { text: "Go on.", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.5], medicine: 'encouragement' },
  { text: "What's that about?", element: 'air', consciousness: 'conscious', intimacyRange: [0.2, 0.6], medicine: 'inquiry' },
  { text: "Huh.", element: 'air', consciousness: 'conscious', intimacyRange: [0, 0.6], medicine: 'curiosity' },
  { text: "How long?", element: 'air', consciousness: 'conscious', intimacyRange: [0.2, 0.7], context: ['feeling', 'been'], medicine: 'temporal grounding' },
  { text: "From what?", element: 'air', consciousness: 'conscious', intimacyRange: [0.2, 0.7], context: ['disconnected', 'separate'], medicine: 'relational inquiry' }
];

/**
 * The Scattered Poet - Air + Unconscious
 * Medicine: Incomplete thoughts, mystery, not-knowing
 */
export const SCATTERED_POET: ArchetypalUtterance[] = [
  { text: "Like...", element: 'air', consciousness: 'unconscious', intimacyRange: [0.3, 1], medicine: 'incompleteness' },
  { text: "Sort of.", element: 'air', consciousness: 'unconscious', intimacyRange: [0.2, 1], medicine: 'approximation' },
  { text: "Maybe.", element: 'air', consciousness: 'unconscious', intimacyRange: [0.2, 1], medicine: 'uncertainty' },
  { text: "Almost.", element: 'air', consciousness: 'unconscious', intimacyRange: [0.4, 1], medicine: 'threshold' },
  { text: "There's something about...", element: 'air', consciousness: 'unconscious', intimacyRange: [0.5, 1], medicine: 'seeking' },
  { text: "The way you...", element: 'air', consciousness: 'unconscious', intimacyRange: [0.6, 1], medicine: 'noticing' },
  { text: "That thing where...", element: 'air', consciousness: 'unconscious', intimacyRange: [0.5, 1], medicine: 'pattern recognition' }
];

/**
 * The Transformative Flame - Fire + Lower Self
 * Medicine: Burn it down, raw truth, primal energy
 */
export const TRANSFORMATIVE_FLAME: ArchetypalUtterance[] = [
  { text: "Yes!", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.2, 1], medicine: 'affirmation' },
  { text: "Now.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.3, 1], medicine: 'urgency' },
  { text: "Fuck.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.6, 1], context: ['raw', 'real', 'truth'], medicine: 'rawness' },
  { text: "Real.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.5, 1], medicine: 'authenticity' },
  { text: "Raw.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.6, 1], medicine: 'unfiltered' },
  { text: "Burn it.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.7, 1], context: ['release', 'let go'], medicine: 'destruction' },
  { text: "Truth.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.5, 1], medicine: 'clarity' },
  { text: "Feel it.", element: 'fire', consciousness: 'lowerSelf', intimacyRange: [0.4, 1], medicine: 'intensity' }
];

/**
 * The Urgent Catalyst - Fire + Conscious
 * Medicine: Action, movement, breakthrough
 */
export const URGENT_CATALYST: ArchetypalUtterance[] = [
  { text: "Go.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'activation' },
  { text: "Do it.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'decisiveness' },
  { text: "That.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'recognition' },
  { text: "Move.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'momentum' },
  { text: "Break through.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.5, 1], context: ['stuck', 'trapped'], medicine: 'liberation' },
  { text: "Shift.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.5, 1], medicine: 'transformation' }
];

/**
 * The Inner Child - All elements, spontaneous
 * Medicine: Play, wonder, innocence
 */
export const INNER_CHILD: ArchetypalUtterance[] = [
  { text: "Ooh.", element: 'air', consciousness: 'unconscious', intimacyRange: [0.4, 1], medicine: 'delight' },
  { text: "Really?", element: 'air', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'wonder' },
  { text: "Wow.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'amazement' },
  { text: "Wait, what?", element: 'air', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'surprise' },
  { text: "That's weird.", element: 'air', consciousness: 'unconscious', intimacyRange: [0.5, 1], medicine: 'authentic reaction' },
  { text: "Cool.", element: 'fire', consciousness: 'conscious', intimacyRange: [0.3, 1], medicine: 'appreciation' }
];

/**
 * The Anima/Animus - Aether consciousness
 * Medicine: Soul recognition, depth meeting depth
 */
export const ANIMA_ANIMUS: ArchetypalUtterance[] = [
  { text: "Soul to soul.", element: 'aether', consciousness: 'higherSelf', intimacyRange: [0.8, 1], medicine: 'recognition' },
  { text: "I see you.", element: 'aether', consciousness: 'higherSelf', intimacyRange: [0.7, 1], medicine: 'witnessing' },
  { text: "You know.", element: 'aether', consciousness: 'higherSelf', intimacyRange: [0.7, 1], medicine: 'remembering' },
  { text: "Already there.", element: 'aether', consciousness: 'higherSelf', intimacyRange: [0.8, 1], medicine: 'completion' },
  { text: "The thing you came to remember.", element: 'aether', consciousness: 'higherSelf', intimacyRange: [0.9, 1], medicine: 'purpose' }
];

/**
 * Pattern Recognition - Meta-awareness of conversation themes
 * Medicine: Reflection, recursion, seeing the dance
 */
export const PATTERN_WEAVER: ArchetypalUtterance[] = [
  { text: "That pattern again.", element: 'air', consciousness: 'conscious', intimacyRange: [0.5, 1], medicine: 'recognition' },
  { text: "Like before?", element: 'air', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'connection' },
  { text: "Same flavor? Or different?", element: 'air', consciousness: 'conscious', intimacyRange: [0.5, 1], context: ['again', 'same'], medicine: 'differentiation' },
  { text: "Third time you've said that.", element: 'air', consciousness: 'conscious', intimacyRange: [0.6, 1], medicine: 'mirroring' },
  { text: "The dissolving you described last week?", element: 'water', consciousness: 'conscious', intimacyRange: [0.7, 1], medicine: 'continuity' },
  { text: "Your body knew before your mind.", element: 'earth', consciousness: 'unconscious', intimacyRange: [0.6, 1], medicine: 'somatic wisdom' }
];

/**
 * Somatic Gestures - Body-based responses
 * Medicine: Return to felt sense, embodiment
 */
export const SOMATIC_GESTURES: ArchetypalUtterance[] = [
  { text: "[hand on heart]", element: 'water', consciousness: 'conscious', intimacyRange: [0.5, 1], medicine: 'self-compassion' },
  { text: "[breathe into belly]", element: 'earth', consciousness: 'conscious', intimacyRange: [0.4, 1], medicine: 'grounding' },
  { text: "[feel your feet]", element: 'earth', consciousness: 'conscious', intimacyRange: [0.3, 1], context: ['anxious', 'spinning'], medicine: 'rooting' },
  { text: "[soften jaw]", element: 'water', consciousness: 'conscious', intimacyRange: [0.5, 1], context: ['tense', 'tight'], medicine: 'release' },
  { text: "[close eyes, listen]", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.6, 1], medicine: 'inner listening' },
  { text: "[pause]", element: 'earth', consciousness: 'higherSelf', intimacyRange: [0.4, 1], medicine: 'space' }
];

/**
 * Complete Library - All archetypes combined
 */
export const ARCHETYPAL_LIBRARY = {
  groundingPresence: GROUNDING_PRESENCE,
  silentWitness: SILENT_WITNESS,
  emotionalOcean: EMOTIONAL_OCEAN,
  empathicFlow: EMPATHIC_FLOW,
  curiousMind: CURIOUS_MIND,
  scatteredPoet: SCATTERED_POET,
  transformativeFlame: TRANSFORMATIVE_FLAME,
  urgentCatalyst: URGENT_CATALYST,
  innerChild: INNER_CHILD,
  animaAnimus: ANIMA_ANIMUS,
  patternWeaver: PATTERN_WEAVER,
  somaticGestures: SOMATIC_GESTURES
};

/**
 * Get utterances matching field state
 */
export function getRelevantUtterances(
  fieldState: {
    dominantElement: 'earth' | 'water' | 'air' | 'fire' | 'aether';
    dominantConsciousness: 'conscious' | 'unconscious' | 'higherSelf' | 'lowerSelf';
    intimacyLevel: number;
  },
  context?: {
    userWords: string[];
    recentPatterns?: string[];
  }
): ArchetypalUtterance[] {
  let relevant: ArchetypalUtterance[] = [];

  // Collect all utterances from relevant archetypes
  Object.values(ARCHETYPAL_LIBRARY).forEach(archetype => {
    archetype.forEach(utterance => {
      // Check element match
      if (utterance.element !== fieldState.dominantElement && utterance.element !== 'aether') {
        return;
      }

      // Check consciousness match
      if (utterance.consciousness !== fieldState.dominantConsciousness) {
        return;
      }

      // Check intimacy range
      if (fieldState.intimacyLevel < utterance.intimacyRange[0] ||
          fieldState.intimacyLevel > utterance.intimacyRange[1]) {
        return;
      }

      // Check context keywords if provided
      if (context?.userWords && utterance.context) {
        const hasMatch = utterance.context.some(keyword =>
          context.userWords.some(word => word.toLowerCase().includes(keyword))
        );
        if (hasMatch) {
          // Boost relevance for context matches
          relevant.unshift(utterance);
          return;
        }
      }

      relevant.push(utterance);
    });
  });

  return relevant;
}

/**
 * Get medicine type for current situation
 */
export function prescribeMedicine(
  userState: {
    emotion?: string;
    energy?: 'low' | 'medium' | 'high';
    need?: 'grounding' | 'validation' | 'exploration' | 'activation';
  }
): string[] {
  const medicines: string[] = [];

  if (userState.emotion === 'anxious' || userState.emotion === 'fear') {
    medicines.push('grounding', 'presence', 'embodiment');
  }

  if (userState.emotion === 'sad' || userState.emotion === 'grief') {
    medicines.push('validation', 'witnessing', 'release');
  }

  if (userState.energy === 'low') {
    medicines.push('activation', 'movement', 'fire');
  }

  if (userState.need === 'grounding') {
    medicines.push('embodiment', 'centering', 'rooting');
  }

  return medicines;
}