'use client';

import Link from 'next/link';
import { SectionReveal } from './SectionReveal';

export function NarrativeSection() {
  return (
    <section
      id="narrative"
      className="relative py-24 sm:py-32 px-4"
      style={{
        background: 'linear-gradient(180deg, #0b0f1c 0%, #0d1020 50%, #0b0f1c 100%)',
      }}
    >
      <div className="max-w-2xl mx-auto">
        <SectionReveal>
          <p className="text-[11px] tracking-[0.35em] uppercase text-white/30 text-center mb-12">
            What it is like
          </p>

          <div className="space-y-6 text-lg sm:text-xl font-extralight leading-relaxed text-white/70" style={{ fontFamily: "'Crimson Pro', serif" }}>
            <p>You arrive with something that has been weighing on you.</p>

            <p>MAIA doesn&apos;t diagnose you.</p>

            <p>She doesn&apos;t rush to solve you.</p>

            <p className="text-white/55">
              She remembers what you&apos;ve chosen to remember, notices threads across
              conversations, and asks questions that help you see your own life more clearly.
            </p>

            <p className="text-white/55">
              Sometimes the conversation lasts ten minutes.
              Sometimes it unfolds over months.
            </p>

            <p className="text-white/55">
              The pace is yours.
            </p>

            <p className="text-white/45 text-base sm:text-lg">
              Many people are surprised that the most valuable moments aren&apos;t generated by MAIA —
              they are recognized within themselves.
            </p>

            <p className="text-white/80 italic">
              The conversation begins wherever your life is today.
            </p>
          </div>

          <div className="mt-14 text-center">
            <Link
              href="/enter"
              className="inline-flex items-center justify-center rounded-xl px-8 py-3.5 bg-maia-spice-500 hover:bg-maia-spice-400 text-black font-semibold text-base transition-colors shadow-lg shadow-maia-spice-500/20"
            >
              Begin a conversation
            </Link>
          </div>
        </SectionReveal>
      </div>
    </section>
  );
}
