#!/usr/bin/env bash
# install.sh — set up Route 53 DDNS on this host.
#
# Run on the minisForum:   sudo ./install.sh
#
# Before running:
#   1. Create AWS IAM user with iam-policy.json (replace REPLACE_WITH_HOSTED_ZONE_ID
#      with your zone ID first; find it via:
#        aws route53 list-hosted-zones-by-name --dns-name soullab.life \
#          --query 'HostedZones[0].Id' --output text
#      The ID looks like /hostedzone/Z01234567ABCDEFGH — strip the prefix.).
#   2. Generate access key for that user.
#   3. Have the access key + zone ID ready when prompted.
#
# Rollback:
#   sudo systemctl disable --now route53-ddns.timer
#   sudo systemctl stop route53-ddns.service 2>/dev/null || true
#   sudo rm /etc/systemd/system/route53-ddns.{service,timer}
#   sudo rm /usr/local/bin/route53-ddns.sh
#   sudo rm -rf /etc/route53-ddns /var/lib/route53-ddns
#   sudo userdel route53-ddns 2>/dev/null || true
#   sudo systemctl daemon-reload
#
# DNS records are NOT modified by uninstall — they remain at whatever IP they
# were last set to. The IAM user in AWS must be deleted separately.

set -euo pipefail

if [ "$EUID" -ne 0 ]; then
  echo "must run as root (try: sudo $0)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for f in route53-ddns.sh route53-ddns.service route53-ddns.timer; do
  if [ ! -f "$SCRIPT_DIR/$f" ]; then
    echo "missing $f next to install.sh" >&2
    exit 1
  fi
done

for cmd in aws jq curl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "missing dependency: $cmd — install before re-running" >&2
    echo "  apt-get install -y awscli jq curl" >&2
    exit 1
  fi
done

read -rp "Hosted zone ID (e.g. Z01234567ABCDEFGH): " ZONE_ID
read -rp "DNS name [soullab.life]: " DNS_NAME
DNS_NAME="${DNS_NAME:-soullab.life}"
read -rp "AWS access key ID: " AWS_KEY
read -rsp "AWS secret access key: " AWS_SECRET
echo
read -rp "AWS region [us-east-1]: " AWS_REGION
AWS_REGION="${AWS_REGION:-us-east-1}"
read -rp "Webhook URL on IP change (optional, leave blank for silent): " WEBHOOK_URL

if ! id route53-ddns >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin route53-ddns
fi

install -d -m 0755 /etc/route53-ddns
install -d -m 0750 -o route53-ddns -g route53-ddns /var/lib/route53-ddns

cat > /etc/route53-ddns/config <<EOF
# Generated by install.sh on $(date -u +%FT%TZ)
HOSTED_ZONE_ID=$ZONE_ID
DNS_NAME=$DNS_NAME
STATE_DIR=/var/lib/route53-ddns
EOF
chmod 0644 /etc/route53-ddns/config

{
  echo "AWS_ACCESS_KEY_ID=$AWS_KEY"
  echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET"
  echo "AWS_DEFAULT_REGION=$AWS_REGION"
  if [ -n "$WEBHOOK_URL" ]; then
    echo "WEBHOOK_URL=$WEBHOOK_URL"
  fi
} > /etc/route53-ddns/credentials
chmod 0600 /etc/route53-ddns/credentials
chown route53-ddns:route53-ddns /etc/route53-ddns/credentials

install -m 0755 "$SCRIPT_DIR/route53-ddns.sh" /usr/local/bin/route53-ddns.sh
install -m 0644 "$SCRIPT_DIR/route53-ddns.service" /etc/systemd/system/route53-ddns.service
install -m 0644 "$SCRIPT_DIR/route53-ddns.timer" /etc/systemd/system/route53-ddns.timer

systemctl daemon-reload

echo
echo "=== Dry-run test (no DNS changes) ==="
sudo -u route53-ddns DRY_RUN=1 bash -c '
  set -a
  . /etc/route53-ddns/credentials
  set +a
  /usr/local/bin/route53-ddns.sh
' || {
  echo "dry-run failed — check output above. NOT enabling timer." >&2
  exit 1
}

echo
echo "Dry-run succeeded. Enable the timer with:"
echo "  sudo systemctl enable --now route53-ddns.timer"
echo
echo "Then watch logs with:"
echo "  journalctl -u route53-ddns.service -f --output=cat"
echo
echo "Force a manual run:"
echo "  sudo systemctl start route53-ddns.service"
echo
echo "Check timer status:"
echo "  systemctl status route53-ddns.timer"
