// JARVIS-FOUNDER-WORKSPACE-01 / F1 — founder vocabulary map v1.
// internal term → ordinary-language sentence → technical source.
// confidence: 'verified' = the sentence was checked against the named source during F0/F1;
//             'candidate' = a reasonable gloss not yet checked line-by-line (render with a marker, never silently).
window.JFW_VOCAB = [
  { term: 'Builder OS / builder_os', plain: 'The JARVIS work engine inside this checkout.', source: 'jarvis-desktop/src/main.js status probe → scripts/builder/session.mjs', confidence: 'verified' },
  { term: 'Route A / route_a', plain: 'The no-model path: JARVIS does the work itself with fixed, deterministic tools.', source: 'docs/ops/JARVIS_ROUTE_A_LIVE_ZERO_LLM_PROOF_2026-08-11.md · scripts/builder/deterministic.mjs', confidence: 'candidate' },
  { term: 'C0', plain: 'A fixed capability JARVIS can run itself, with no model involved.', source: 'scripts/builder/router.mjs · jarvis-desktop/src/capability-form.js', confidence: 'verified' },
  { term: 'C1', plain: 'A model running on this machine does the work.', source: 'scripts/builder/router.mjs · main.js submit-task (Ollama)', confidence: 'verified' },
  { term: 'C3', plain: 'An outside (frontier) model would be asked. Never automatic; you say so each time.', source: 'router.mjs · main.js:520 · frontier-worker.js (external_ok)', confidence: 'verified' },
  { term: 'local-native', plain: "JARVIS's own coding lane on a local model, inside a bounded temporary copy of the repository.", source: 'scripts/builder/jarvis-runtime-pipeline.mjs (requires repo.read + bounded repo.write:worktree)', confidence: 'verified' },
  { term: 'Work Unit (W0.v2)', plain: 'One governed piece of work: what it is, where it runs, with what permission, by which route, and with what evidence.', source: 'docs/programme/JARVIS-WORK-UNIT-01_W0_CANONICAL_CONTRACT_2026-09-18.md', confidence: 'verified' },
  { term: 'packet (legacy work unit)', plain: 'The older shape of a piece of work; kept for compatibility, not the canonical one.', source: 'jarvis-desktop/src/operator-work-unit.js · I4 §2/§17', confidence: 'verified' },
  { term: 'W2 (lifecycle)', plain: 'The stages a piece of work moves through. Only the lifecycle law may move it.', source: 'docs/programme/JARVIS-WORK-UNIT-01_W2_LIFECYCLE_2026-09-18.md', confidence: 'verified' },
  { term: 'W3 / W3T (routing binding / transport)', plain: 'Deciding how a piece of work would be run, and by what channel, without running it.', source: 'docs/programme/JARVIS-WORK-UNIT-01_W3_ROUTING_BINDING_2026-09-18.md', confidence: 'verified' },
  { term: 'W4 (ledger)', plain: 'The append-only history of everything that happened to a piece of work. Nothing is ever edited out.', source: 'docs/programme/JARVIS-WORK-UNIT-01_W4_APPEND_ONLY_LEDGER_2026-09-18.md', confidence: 'verified' },
  { term: 'E1 (execution bridge)', plain: 'The one-shot bridge that runs an already-authorized piece of work through a provider, once.', source: 'docs/programme/JARVIS-CANONICAL-PROVIDER-EXECUTION-01_E1_WITNESS_2026-09-18.md', confidence: 'verified' },
  { term: 'Authorize once ≠ Confirm execute', plain: 'Saying "you may" and saying "go" are two separate acts, always.', source: 'E1 witness · R5B record', confidence: 'verified' },
  { term: 'E0–E4 (evidence class)', plain: 'How strongly a claim has to be grounded before it counts.', source: 'W0.v2 form (renderer.js Work view)', confidence: 'candidate' },
  { term: 'J5 / J6', plain: 'The ratified routing law (J5) and its implementation (J6).', source: 'docs/programme/JARVIS-ROUTING-INTELLIGENCE-01_J5_FOUNDER_RULING_2026-09-18.md · scripts/builder/routing-intelligence-j6.mjs', confidence: 'verified' },
  { term: 'R4 (execution admission)', plain: 'Whether a piece of work may be admitted for running at all.', source: 'docs/programme/JARVIS-ROUTING-INTELLIGENCE-01_R4_EXECUTION_ADMISSION_CONTRACT_2026-09-18.md', confidence: 'verified' },
  { term: 'R5A (immutable route binding)', plain: 'Once a route is bound, it is frozen; the screen cannot supply it.', source: 'docs/programme/JARVIS-ROUTING-INTELLIGENCE-01_R5A_IMMUTABLE_ROUTE_BINDING_2026-09-18.md', confidence: 'verified' },
  { term: 'R5B (human provider execution authorization)', plain: 'You authorize a single outside-model run, once. Authorizing is not running.', source: 'docs/programme/JARVIS-ROUTING-INTELLIGENCE-01_R5B_HUMAN_PROVIDER_EXECUTION_AUTHORIZATION_2026-09-18.md', confidence: 'verified' },
  { term: 'O0 … O4', plain: 'The operator organs: rules (O0), what you meant (O1), a plan of steps (O2), what permission each step needs (O3), which capability fits (O4). None is wired into the console today.', source: 'docs/programme/JARVIS-ORCHESTRATION-OPERATOR-01_O0…O4 · F0 §2.2', confidence: 'verified' },
  { term: 'O7 / O10', plain: 'Two future acts: a decision surface for you (O7) and a witnessed desktop walk (O10). Neither is open.', source: 'O3 doc :250,:253 · O4 doc :329', confidence: 'verified' },
  { term: 'READY', plain: 'This works and was checked.', source: 'jarvis-desktop/src/legibility.js', confidence: 'verified' },
  { term: 'WORKING', plain: 'Something is running right now.', source: 'legibility.js', confidence: 'verified' },
  { term: 'NEEDS_SETUP', plain: 'Something on this machine is missing or not configured.', source: 'legibility.js', confidence: 'verified' },
  { term: 'NEEDS_AUTHORITY', plain: 'Waiting for you to grant permission.', source: 'legibility.js', confidence: 'verified' },
  { term: 'DEGRADED', plain: 'It works, but not fully or not reliably.', source: 'legibility.js', confidence: 'verified' },
  { term: 'BLOCKED', plain: 'Something else must be resolved first.', source: 'legibility.js', confidence: 'verified' },
  { term: 'FAILED', plain: 'It was tried and it did not work.', source: 'legibility.js', confidence: 'verified' },
  { term: 'UNVERIFIED', plain: 'JARVIS cannot say either way from the evidence it has.', source: 'legibility.js · manual §4', confidence: 'verified' },
  { term: 'UNOBSERVED', plain: 'Nobody looked. That is not the same as broken, and not the same as fine.', source: 'manual §4 · Living Spiral projection law', confidence: 'verified' },
  { term: 'NOT PROBED / UNCONFIGURED', plain: 'Deliberately not checked from here (production, database).', source: 'main.js:518-519', confidence: 'verified' },
  { term: 'HELD_FOR_AUTHORITY', plain: 'Ready to route, but held until you grant what it needs.', source: 'O4 contract · R4', confidence: 'verified' },
  { term: 'SECOND_REVIEW_OWED', plain: 'One review happened; an independent second one is required before it counts.', source: 'jarvis-desktop/src/work-unit-control.js · FLOW-02', confidence: 'verified' },
  { term: 'REPAIR_BEFORE_WITNESS', plain: 'Something must be fixed before it is worth witnessing.', source: 'work-unit-control.js', confidence: 'verified' },
  { term: 'NEEDS_KELLY', plain: 'Needs your judgment. (The console hard-codes your name; this map says "you".)', source: 'renderer.js:591,1322', confidence: 'verified' },
  { term: 'REVIEW_DISAGREEMENT', plain: 'Two reviewers disagree. JARVIS will not pick a winner; you decide.', source: 'work-unit-control.js · R1 route contract', confidence: 'verified' },
  { term: 'EVIDENCE_PRESENTED', plain: 'The evidence is on the table. Nothing has been decided.', source: 'work-unit-control.js', confidence: 'verified' },
  { term: 'PASS / STOP / RETURN / HOLD / PARK', plain: 'Accepted · stop and ask · send back for rework · wait on a named condition · set aside deliberately.', source: 'docs/programme/JARVIS_INSTRUCTIONAL_MANUAL_v1.md §12', confidence: 'verified' },
  { term: 'LIVE / STALE / AMBIGUOUS_OWNERSHIP / CAPACITY', plain: 'A session is current · out of date · nobody clearly owns it · no room to run it.', source: 'scripts/builder/session.mjs via governance.js', confidence: 'candidate' },
  { term: 'Governor (session.mjs)', plain: 'The bookkeeper of who is working on what. You can recover, reconcile or close a session through it.', source: 'jarvis-desktop/src/governance.js', confidence: 'verified' },
  { term: 'Living Spiral', plain: 'The operator field picture: rings mean standing, spokes are only grouping. It never scores health and never shows a member.', source: 'docs/governance/JARVIS_LIVING_SPIRAL_JURISDICTION_2026-08-16.md · spiral.js', confidence: 'verified' },
  { term: 'Provenance / "Which JARVIS is this?"', plain: 'Which build is running versus which checkout it is bound to.', source: 'jarvis-desktop/src/provenance.js', confidence: 'verified' },
  { term: 'Canonical / clean-main-no-secrets', plain: 'The trunk that production is built from.', source: 'CLAUDE.md deployment section', confidence: 'verified' },
  { term: 'Candidate', plain: 'A change proposed and evidenced, but not yet accepted.', source: 'manual §4', confidence: 'verified' },
  { term: 'Witness', plain: 'Direct, recorded evidence that something actually happened — as opposed to a claim that it did.', source: 'manual §17, §29', confidence: 'verified' },
  { term: 'Observed against (freshness)', plain: 'Which exact trunk version the evidence was taken against.', source: 'charter §Freshness discipline', confidence: 'verified' },
  { term: 'SHA', plain: 'The fingerprint of one exact version of the code.', source: 'git', confidence: 'verified' },
  { term: 'Merge · Deploy · Production write · Member-facing', plain: 'Four separate permissions. Having one never implies another.', source: 'manual §15, §24', confidence: 'verified' },
  { term: 'Ollama', plain: 'The local model server on this machine.', source: 'main.js (127.0.0.1:11434)', confidence: 'verified' },
  { term: 'Qwen / GPT-OSS / Nemotron / Inkling', plain: 'Model names. Qwen and GPT-OSS can run locally; Nemotron is an outside model; treat all as tools, never as authority.', source: 'renderer.js provider-strategy mode · R1', confidence: 'candidate' },
  { term: 'OpenCode', plain: 'The tool JARVIS uses to talk to outside models, in a sandbox.', source: 'jarvis-desktop/src/frontier-worker.js', confidence: 'verified' },
  { term: '$AIN_HOME', plain: 'Where JARVIS keeps its work records on this machine (~/.claude/ain-delegation by default).', source: 'work-unit-control.js · canonical-work-unit-v2.js', confidence: 'verified' },
  { term: 'Continuity / Recall', plain: "JARVIS's memory of prior sessions, kept only on this machine.", source: 'docs/programme/JARVIS-CONTINUITY-BRIDGE-01_2026-09-17.md', confidence: 'verified' },
  { term: 'Programme · flow · lane · stage · act · gate', plain: 'A programme is a governing question; a lane advances it; an act is one bounded step; a gate is where it is judged.', source: 'manual §2', confidence: 'verified' },
  { term: 'Cockpit (manual §24)', plain: 'The smallest written state needed to pick a programme back up. Not a dashboard.', source: 'manual §24', confidence: 'verified' },
  { term: 'Externally governed (Merge Authority)', plain: 'Governed by a record that lives outside this repository. This workspace only points at it.', source: 'F0 adjudication §V', confidence: 'verified' }
];
