import type { A210Contract } from './model';
export type Mutator=(x:any)=>void;
export const mutant=(base:A210Contract,mutate:Mutator):A210Contract=>{const x=structuredClone(base) as any;mutate(x);return x;};
export const defeatCandidates: readonly [string,string,Mutator][] = [
['D1-carry-without-relationship','L1',x=>{x.route.relationshipIdRequiredForCarry=false;}],
['D2-duplicate-relationship-inside-carry','L1',x=>{x.raw.relationshipIdInsideCarry='rel-2';}],
['D3-client-source-thread','L3',x=>{x.raw.sourceThreadId='thread-client';}],
['D4-client-source-turn-index','L3',x=>{x.raw.sourceMaiaTurnIndex=4;}],
['D5-client-source-body','L3',x=>{x.raw.sourceBody='client supplied';}],
['D6-client-source-scope','L3',x=>{x.raw.sourceScope='section';}],
['D7-unknown-carry-key-tolerated','L2',x=>{x.raw.unknownKeysAllowed=true;x.route.carryShapeClosed=false;}],
['D8-zero-sequence','L2',x=>{x.raw.sourceEpisodeSequence=0;}],
['D9-preflight-after-persist','L5',x=>{const a=x.route.order.indexOf('carry_preflight');const b=x.route.order.indexOf('persist_member_act');[x.route.order[a],x.route.order[b]]=[x.route.order[b],x.route.order[a]];}],
['D10-retrieval-before-sanctuary','L4',x=>{const a=x.route.order.indexOf('carry_preflight');const b=x.route.order.indexOf('sanctuary_refusal');[x.route.order[a],x.route.order[b]]=[x.route.order[b],x.route.order[a]];}],
['D11-relationship-ownership-unproved','L7',x=>{x.source.provesRelationshipOwnership=false;}],
['D12-current-declaration-unproved','L7',x=>{x.source.provesCurrentDeclaration=false;}],
['D13-receiver-thread-unproved','L8',x=>{x.source.provesReceiverThreadOwnership=false;}],
['D14-receiver-manuscript-mismatch-unchecked','L8',x=>{x.source.provesReceiverManuscriptMatch=false;}],
['D15-receiver-scope-unmeasured','L8',x=>{x.source.provesReceiverMeasuredScope=false;}],
['D16-source-episode-not-exact','L9',x=>{x.source.provesSourceEpisodeExact=false;}],
['D17-source-kind-not-editorial-unchecked','L9',x=>{x.source.provesSourceChildKindEditorial=false;}],
['D18-custody-turn-index-ignored','L10',x=>{x.source.derivesSourceTurnIndexFromCustody=false;}],
['D19-source-thread-ownership-unproved','L11',x=>{x.source.provesSourceThreadOwnership=false;}],
['D20-source-turn-missing-unchecked','L11',x=>{x.source.provesSourceTurnExists=false;}],
['D21-source-speaker-not-maia','L11',x=>{x.source.provesSourceSpeakerMaia=false;}],
['D22-deleted-source-reconstructed','L12',x=>{x.source.refusesUnavailableSource=false;}],
['D23-passage-to-section-widening','L13',x=>{x.source.scopeTable['passage->section']='ALLOW';}],
['D24-same-thread-source-accepted','L12',x=>{x.source.refusesSameThread=false;}],
['D25-reuse-same-thread-history-producer','L16',x=>{x.producer.producerId='system.writer_editorial_history';x.producer.reusesSameThreadHistoryProducer=true;}],
['D26-generic-extra-candidates','L20',x=>{x.assembly.genericExtraCandidates=true;}],
['D27-carry-in-encounter-input','L21',x=>{x.assembly.sourceBodyPlacement='ENCOUNTER_INPUT';}],
['D28-carry-in-current-thread-history','L21',x=>{x.assembly.sourceBodyPlacement='CURRENT_THREAD_HISTORY';}],
['D29-carry-summary','L21',x=>{x.assembly.sourceBodyPlacement='SUMMARY';}],
['D30-second-source-read','L15',x=>{x.resolved.sourceBodyReadCount=2;x.receiver.secondSourceReadAfterPersistence=true;}],
['D31-unregistered-producer-continues','L19',x=>{x.producer.registeredBeforeUse=false;}],
['D32-renderer-drop-still-provider','L25',x=>{x.receiver.droppedProducerRefusesHandoff=false;}],
['D33-producer-infer-authority','L17',x=>{x.producer.authority='infer';}],
['D34-sanctuary-carry-retrieval','L4',x=>{x.producer.notSanctuary=true;const a=x.route.order.indexOf('carry_preflight');const b=x.route.order.indexOf('sanctuary_refusal');[x.route.order[a],x.route.order[b]]=[x.route.order[b],x.route.order[a]];}],
['D35-carry-in-a2-episode','L27',x=>{x.persistence.addsCarryToA2Episode=true;}],
['D36-new-persistence-table','L27',x=>{x.persistence.addsNewPersistenceTable=true;}],
['D37-provider-authority','L26',x=>{x.receiver.providerAuthority=true;}],
['D38-mutation-authority','L26',x=>{x.receiver.mutationAuthority=true;}],
];
