import type { A210Contract, Refusal } from './model';

const refusals: readonly Refusal[] = [
  'relationship_required','relationship_not_found','current_declaration_unavailable',
  'receiver_thread_invalid','receiver_scope_unmeasured','source_episode_not_found',
  'source_kind_not_editorial','source_thread_invalid','source_turn_not_found',
  'source_turn_not_maia','source_unavailable','same_thread_source','scope_widening_forbidden',
];

/** A2-10 lawful non-executing implementation contract. */
export function referenceContract(): A210Contract {
  return {
    raw: {
      kind:'prior_maia_editorial_turn',
      sourceEpisodeSequence:2,
      unknownKeysAllowed:false,
    },
    route: {
      topKeys:['threadId','act','sanctuary','scope','relationshipId','carry'],
      relationshipIdRequiredForCarry:true,
      carryShapeClosed:true,
      positiveIntegerSequenceRequired:true,
      duplicateParentIdentityForbidden:true,
      clientSourceFactsForbidden:true,
      order:[
        'gate','identity','parse','posture','sanctuary_refusal',
        'relationship_preflight','carry_preflight','persist_member_act',
        'mint_exchange','run_turn','handoff','provider','persist_outcome',
      ],
    },
    source: {
      inputFields:['memberId','relationshipId','receiverThreadId','sourceEpisodeSequence'],
      provesRelationshipOwnership:true,
      provesCurrentDeclaration:true,
      provesReceiverThreadOwnership:true,
      provesReceiverManuscriptMatch:true,
      provesReceiverMeasuredScope:true,
      provesSourceEpisodeExact:true,
      provesSourceChildKindEditorial:true,
      derivesSourceThreadFromCustody:true,
      derivesSourceTurnIndexFromCustody:true,
      provesSourceThreadOwnership:true,
      provesSourceTurnExists:true,
      provesSourceSpeakerMaia:true,
      refusesUnavailableSource:true,
      refusesSameThread:true,
      scopeTable:{
        'passage->passage':'ALLOW',
        'passage->section':'REFUSE',
        'section->passage':'ALLOW',
        'section->section':'ALLOW',
      },
    },
    resolved: {
      kind:'PRIOR_MAIA_EDITORIAL_TURN',
      producerId:'system.writer_relationship_prior_editorial_turn',
      immutable:true,
      rawRequestMayConstruct:false,
      sourceBodyReadCount:1,
    },
    producer: {
      producerId:'system.writer_relationship_prior_editorial_turn',
      authoredBy:'system',
      participationClass:'retrieved',
      authority:'situate',
      consentBasis:'member explicitly selected this prior MAIA Editorial response for this Editorial act',
      identityRequirement:'verified',
      notSanctuary:false,
      rooms:['writers_studio'],
      mandatory:false,
      scope:'route',
      reusesSameThreadHistoryProducer:false,
      registeredBeforeUse:true,
    },
    assembly: {
      widensEditorialProducerUnion:true,
      sameThreadHistoryUnchanged:true,
      genericExtraCandidates:false,
      genericContextBag:false,
      castBypass:false,
      sourceBodyPlacement:'DEDICATED_CANDIDATE',
      sourceBodyOccurrences:1,
      preservesEarlierMaiaAuthorship:true,
      preservesFrozenTemporalStanding:true,
      labelsContextNotInstruction:true,
      grantsRereadAuthority:false,
    },
    receiver: {
      runTurnInputIsResolvedCarryOnly:true,
      rawCarryRequestAcceptedByRunTurn:false,
      receiverThreadExact:true,
      receiverRelationshipExact:true,
      sourceReadProofRequired:true,
      receiverAdmissionProofRequired:true,
      secondSourceReadAfterPersistence:false,
      mipaRequired:true,
      rendererProofRequired:true,
      droppedProducerRefusesHandoff:true,
      providerAuthority:false,
      mutationAuthority:false,
    },
    persistence: {
      addsCarryToA2Episode:false,
      addsCarryToAskTurns:false,
      addsCarryToProposalObjects:false,
      addsNewPersistenceTable:false,
    },
    refusal: {
      closedSet:refusals,
      malformed400:true,
      semantic409:true,
      notFound404WhereExistingLaw:true,
      preflightRefusalPersistedFalse:true,
      providerNotReachedOnPreflightRefusal:true,
    },
  };
}
